### ISSUE TITLE
KeyManagementService issue: 'ICoreAmazonKMS' claims it is defined in 'AWSSDK.Core', but it could not be found

### ISSUE THREAD

**Issue by SteveMadigan** [aws/aws-sdk-net#1009]
I cannot rid my project of this error, I've tried installing/uninstalling/various versions of nuget packages for awssdk.core and .keymanagementservice to no avail. Anyone else seen this?

Currently trying latest versions of each
.core: 3.3.24.4
.keymanagementservice 3.3.5.10

**Comment by vellozzi** [comment]
We've seen issues where users have unknowingly had assemblies installed in their GAC.  Then, when they try to use the AWS DSK for .NET it uses an older version from the GAC.

Is that a possibility?  We've seen cases where it was third party software installing to the GAC.  So it may not have been intentional.

This will tell you if you're using assemblies from the GAC or not:
```
Console.WriteLine(typeof(Amazon.Runtime.AWSCredentials).Assembly.Location); 
Console.WriteLine(typeof(Amazon.KeyManagementService.AmazonKeyManagementServiceClient).Assembly.Location);
```

**Comment by SteveMadigan** [comment]
Nothing in the GAC. It's got to be a version problem but I can't find it.

**Comment by vellozzi** [comment]
Did you check that the running assembly is the one you think it is?  The code snippet above will tell you that too.

Look at the file at the location that the code prints and make sure it's the version you expect.

**Comment by SteveMadigan** [comment]
I deleted all awssdk.core files from my dev machine, uninstalled aws packages and reinstalled, problem solved. thanks for the advice!
