### ISSUE TITLE
AWSSDK.Core nuget spec update for .NETStandard 2.0

### ISSUE THREAD

**Issue by JBaltika** [aws/aws-sdk-net#1013]
Hi guys,

Can you update nugets spec for .NETStandard 2.0 as some listed nuget dependencies are not required any more.

**Comment by slang25** [comment]
It sounds like progress is being made internally, [see this comment](https://github.com/aws/aws-sdk-net/issues/971#issuecomment-406202327)

**Comment by chrisdrobison** [comment]
This is important because it looks like some of the properties you took out to comply with .NET Standard 1.3 can now be put back in. For example, MaxIdleTime exists for the full framework, but you can't use it when referencing the .NET Standard 1.3 package. And the API documentation gives no indication that this is the case.

**Comment by sstevenkang** [comment]
We just added `netstandard20` target to our NuGet packages. All AWS .NET SDK NuGet packages starting with `3.3.100` should support .NET Standard 2.0!

See our announcement [here](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-now-targets-net-standard-2-0/)!
