### ISSUE TITLE
Exception in parsing Date for property Expiration

### ISSUE THREAD

**Issue by bhattfrequent** [aws/aws-sdk-net#1021]
'expiry-date="Thu, 2 Aug 2018 09:41:03 GMT" is not getting parsed if an object has this date as expiry date in the object header. Where as "Fri, 12 Oct 2018 00:00:00 GMT" is getting parsed without any issue
## Expected Behavior

If an object has Expiry date of "Thu, 2 Aug 2018 09:41:03 GMT" in the header then it should be parsed without exception in the **internal Expiration(string headerValue)** class

At the moment this function is using 
public const string RFC822DateFormat = "ddd, dd MMM yyyy HH:mm:ss \\G\\M\\T"
as dateformat for function 
DateTime expiryDate = DateTime.ParseExact(expiryDateValue, Amazon.Util.AWSSDKUtils.RFC822DateFormat, CultureInfo.InvariantCulture);
## Current Behavior

This function will work fine for "Fri, 12 Oct 2018 00:00:00 GMT" but will throw exception for "Thu, 2 Aug 2018 09:41:03 GMT"
## Possible Solution

Change the date format to
public const string RFC822DateFormat = "ddd, **d** MMM yyyy HH:mm:ss \\G\\M\\T"
this will handle both the scenarios
## Your Environment

* AWSSDK.Core version used: 3.3.24.4
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 2015
* Targeted .NET platform: 4.5

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by R7AL** [comment]
I'm seeing the same exact issue and I think it's expecting the single digit date to be "05" instead of just "5"

**Comment by R7AL** [comment]
To add to this,
in Java we specify the expiration days with setExpirationInDays, this set the date in a different format that DateTime.ParseExact in .NET -> aws-sdk-net/sdk/src/Services/S3/Custom/Model/Expiration.cs line:78, which is RFC822

This should be fixed in the Java side where it should use this format, or the .NET should handle the single digit day issue. 

** I'm mentioning Java because that where we countered the issue, we control the bucket with Java and we consume it with .NET (two different applications) so we found the issue here. We don't know if other library set the expiration date with the RFC822 format or not.
