### ISSUE TITLE
403 response from public elastic search domain 

### ISSUE THREAD

**Issue by RyanAudet** [aws/aws-sdk-net#1031]
I am having trouble accessing a public elastic search domain from AWS Lambda.  The domain belongs to a separate AWS account from mine, but it is public.  
  
I am able to access it from postman or while executing locally, anyone can access it.  However when I publish my solution which accesses it to AWS Lambda I get the response: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 403.

**Comment by RyanAudet** [comment]
I never solved this issue.  Like you said it's tough to really nail down where exactly the issue lies it could also be in NEST.  Eventually I will have to implement cross account security anyways, which hopefully will fix it.

**Comment by klaytaybai** [comment]
If you still think this may be an issue with the SDK, could you please provide some information on your environment?  Please keep us updated if you make progress with this problem.  

**Clarification**
Are you trying to connect to Elastic's Elasticsearch or Amazon's Elasticsearch service?  These are two different offerings.  If you are using the Elastic API in your lambda function but trying to access an Amazon Elasticsearch domain, that would definitely be a reason why you are having trouble authenticating.  You can see [Amazon's Elasticsearch documentation] for more info. (https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Elasticsearch/NElasticsearch.html)

**Comment by RyanAudet** [comment]
So here are the details: I have 2 amazon accounts.

I have an Amazon Elasticsearch domain version 6.2 on Account 1.  It is configured for public access.  I can access it via postman or just by web.

I have an AWS .net core  2.1 Serverless Application which uses NEST V6.2 to access the elastic search domain.  When I run it locally under my AWS credentials for Account 2 I can access the elastic search domain.  However when I publish the solution to AWS Account 2 I get the message: 

```
{"errorCode":"A server error occurred.
Elastic Search error: Invalid NEST response built from a unsuccessful low level call on POST:
 /currentexperienceelasticus-west-2/currentexperienceelastic/_search?typed_keys=true
Audit trail of this API call:
 - [1] BadResponse: 
Node: https://search-repsavvy-shared-77z4kweei27kzjs5fale45sczq.us-east-1.es.amazonaws.com/ T
ook: 00:00:02.4583753\
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: 
Status code 403 from: POST /currentexperienceelasticus-west-2/currentexperienceelastic/_search?typed_keys=true\n# Request:\r\n{\"from\":0,\"size\":50,\"query\":{\"bool\":{\"must\":[{\"bool\":{\"filter\":[{\"term\":{\"createdBy\":{\"value\":\"ryan.audet@gmail.com\"}}}]}},{\"bool\":{\"should\":[{\"match\":{\"firstName\":{\"query\":\"2\"}}},{\"match\":{\"lastName\":{\"query\":\"2\"}}},{\"match\":{\"address\":{\"query\":\"2\"}}}]}}]}}}
# Response:
{\"Message\":\"User: arn:aws:sts::[myaccount]:assumed-role/ProxyFunctionRole-10ODI5DVKJRWE/ProxyFunction-1K6TOTOKFEUI0 is not authorized to perform: es:ESHttpPost\"}\n","args":null}
```

**Comment by klaytaybai** [comment]
Hi @RyanAudet, is the domain secured with an access policy that could potentially prevent it from being accessed by the second account?  Even if you have configured the Elasticsearch domain to be publicly accessible (compared to accessible via your VPC), it is recommended that the domain be protected with an access policy that restricts usage by, for example, whitelisting IP addresses or AWS users.  You can check out the Elasticsearch Domain Access Policy Documentation [here](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-access-policies).

**Comment by RyanAudet** [comment]
It is configured for open access.  The domain is in the error message from my previous message feel free to try it.

**Comment by klaytaybai** [comment]
Hi @RyanAudet,  sorry for taking some time to get back to you.  I confirmed that the domain is publicly accessible.  That is almost certainly not the problem.  

I'm fairly confident that the problem is your lambda configuration and not any issue with the functionality of any of the services or SDK.  If you go to your AWS Console and then navigate to the Lambda service and then the specific Lambda function in question, you should see a page with your configuration details.  At the top of this page should be a chart that shows your function's triggers on the left and role permissions on the right.  If Amazon Elasticsearch Service is not in the list on the right, that is a problem.  If it is there, you should be able to click on it and then see a tab below that shows "Allow:es :ESHttpPost" under "By resource".    If that is there and this is still not working, we'll have to continue looking into next steps, and I'll reach out to others for help.

If you don't have Elasticsearch permissions on your Lambda function's role, you can add them by modifying the role you chose or creating a new execution role for the function based on the "Elasticsearch permissions" policy template.

**Comment by RyanAudet** [comment]
Thanks! That fixed it.
