### ISSUE TITLE
S3 TransferUtilityUploadDirectoryRequest does not support Headers

### ISSUE THREAD

**Issue by DeJerre** [aws/aws-sdk-net#109]
In contrast to TransferUtilityUploadRequest,  it is not possible to include headers using TransferUtilityUploadDirectoryRequest to upload a directory to S3 storage. When using Metadata to set parameters to my upload request, they include 'x-amz-meta-' and this is not valid for Cloudfront

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md

**Comment by PavelSafronov** [comment]
Specifying the same HeadersCollection for each file upload in a directory does not make sense, since most of the headers should be file-specific, for instance Content-Disposition or Content-Length.

However, in version 2.3.6 of the SDK we added a way to configure how each individual file in a directory is uploaded, including what headers are set. This can be done through the [UploadDirectoryFileRequestEvent callback](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl+pcl/Transfer/_bcl/TransferUtilityUploadDirectoryRequest.cs#L296).
