### ISSUE TITLE
MTurk SDK returning no data/incorrect data for various calls

### ISSUE THREAD

**Issue by mmmscott** [aws/aws-sdk-net#1100]
## Expected Behavior
- When creating a HIT with a SimplePlurality policy, I expect in the case of disagreement for the first two assignments, a third assignment would be created.
- When checking the Assignment Answers, I would expect that the if the Assignment Answers are in disagreement (in this case, the two options are "accept" and "reject"), the WorkerAgreementScore would not be 100. 
- When a HIT has 100% Agreement between two Turkers, I would expect to be able to get the value for the `AgreedAnswer` from the `ReviewResult`
- When I get a list of HITs by using `ListReviewableHITsAsync`, I expect the full HIT data to be returned.

## Current Behavior
- No third assignment was created in the case of disagreement.

- Assignment Answers are not equal and the WorkerAgreementScore is still 100%:
![bug3a-two-different-answers](https://user-images.githubusercontent.com/44070048/47244493-7ecc0100-d3aa-11e8-97ec-a17e8582c3c3.png)
![bug3b-agreement-score-100](https://user-images.githubusercontent.com/44070048/47244502-82f81e80-d3aa-11e8-931b-6574eccd450b.png)

 - The `AgreedAnswer` value in the `ReviewResult` is an empty string:
![bug2-no-agreedanswer](https://user-images.githubusercontent.com/44070048/47244520-999e7580-d3aa-11e8-9316-d109447f1dfc.png)

- No HIT data is returned other than the `HITId`
![bug4-no-hit-details](https://user-images.githubusercontent.com/44070048/47244537-aa4eeb80-d3aa-11e8-810d-36093f07a720.png)

## Context
We are trying to automate the ability of creating, extending and approving HITs that are in agreement with a simple majority. Although we have managed to work around it by doing things like filtering out non-Reviewable HITs and checking the individual Assignments, the SDK provides tools that don't seem to be working the way we expect. 

## Your Environment

* AWSSDK.Core version used: 3.3.3.5
* Service assembly and version used: 
* Operating System and version: Windows 10 Enterprise OS Build 17134.1
* Visual Studio version: 15.8.5
* Targeted .NET platform: .NET Standard 2.0

**Comment by klaytaybai** [comment]
Hi @marcusscott, I'd like to help you resolve these issues.  It's likely that most of the issues you are seeing are a service issue and not an SDK issue.  However, that last "No Hit data is returned..." issue is definitely something I want to verify is not an SDK issue.  Could you please run Fiddler to capture your network traffic and let us know if you are getting non-default values back from AWS? 

 Do you have a paid support plan?  If so, I suggest opening tickets through your plan for better prioritization and communication.  If not, I'll put in internal tickets soon.

**Comment by marcusscott** [comment]
Sure, I'll go ahead and run Fiddler for that last point. I can double check about the paid support plan -- do you mean filing tickets for the first three that you think are service issues? Thanks!

**Comment by marcusscott** [comment]
@klaytaybai here's some example JSON -- it looks like it is also a service problem. 
![hits](https://user-images.githubusercontent.com/44070048/47311570-f4281380-d5ee-11e8-92f6-901c4b326f5f.PNG)

**Comment by klaytaybai** [comment]
@marcusscott, thanks.  I'll put in a ticket to the service team and notify you if I get any updates.

**Comment by klaytaybai** [comment]
To go back to your previous question: yes, I suggest you file tickets with a paid support plan if you have one.  The turnaround will probably be better, and they may be able to help you out by accessing confidential account information.  

In the meantime, the process for submitting a ticket internally asks for the following details:
- What kind of business impact does this have for you?
- In what time window are you experiencing the problem?  If you can get the exact minute that this issue was occurring, that would be great.
- Are you using production or a sandbox?
- Request ids of the requests that you think are having problems.

**Comment by marcusscott** [comment]
Are you looking for specific HIT ids?

**Comment by klaytaybai** [comment]
No, the request ids of the calls to AWS service.

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TResponseMetadata.html

```
HTTP/1.1 200 OK
x-amzn-RequestId: <RequestId>
Content-Type: application/x-amz-json-1.1
Content-Length: <PayloadSizeBytes>
Date: <Date>
{
  NextToken:PaginationToken,
  NumResults:10,
  HITs:[HIT]
}
```

**Comment by marcusscott** [comment]
Ah, thanks. I'll get those to you then

**Comment by marcusscott** [comment]
@klaytaybai 
**What kind of business impact does this have for you?**
While I was able to write code to work around these service issues, it impacts our business by making the MTurk more difficult to use. Without accurately reporting whether Turkers have reached consensus or extending HITs, we lose the ability to accurately judge our content we give to MTurk. 

**Are you using production or sandbox?**
Production.

**Request Ids**
- ReviewableHITsAsync returning only HITId: d339acb0-e0dc-4991-b776-f74e6e0c389c
- No AgreedAnswer string value: c89bb138-7270-422e-8540-46058e84bb25
- Incorrect WorkerAgreementScore
  - Assignments that have answers that are in disagreement: 53cbb1a9-4d96-4b34-b50b-
  - Incorecct WorkerAgreementScore: 53cbb1a9-4d96-4b34-b50b-5927de36a2b2

**Comment by marcusscott** [comment]
Hey @klaytaybai, thanks for the responses:
1. You are correct in assuming I've already changed the MaxAssignments to 2. However, when creating the HITs, I specify the following policy: 

```
            hitRequest.HITReviewPolicy = new ReviewPolicy
            {
                PolicyName = "SimplePlurality/2011-09-01",
                Parameters = new List<PolicyParameter>
                {
                    new PolicyParameter { Key = "QuestionIds", Values = new List<string> { "<someId>" } },
                    new PolicyParameter { Key = "QuestionAgreementThreshold", Values = new List<string> { "60" } },
                    new PolicyParameter { Key = "ExtendIfHITAgreementScoreIsLessThan", Values = new List<string> { "100" } },
                    new PolicyParameter { Key = "ExtendMaximumAssignments", Values = new List<string> { "3" } },
                }
            };
```
Originally, we had this script written in Python but have since converted it over to .NET. Of note, I specified that the HIT type should have the SimplePlurality policy and have specified the ExtendMaximumAssignments to be 3. When this script was ran in Python, the policy worked fine (that is, when there was a disagreement between the two Turkers, a third assignment was created), but for whatever reason, none have been extended even though there are disagreements. 

2. This explanation makes sense to me!

3. This explanation also makes sense. 

4. This assumption is false -- I'm able to look up the individual HITs by GetHITAsync or ListHITsAsync using the same IDs returned from ListReviewableHITsAsync and still get the full HIT.
