### ISSUE TITLE
GetBucketLocation hangs 

### ISSUE THREAD

**Issue by GusevIVan** [aws/aws-sdk-net#1109]
Hi!

We are developing utility with functionality uploading files to S3.

We use AWSSDK 2.3.55.2, and this works good, but from time to time our application hangs guring executing the following instructions:

GetBucketLocationResponse bucketLocationResponse = tmpS3Client.GetBucketLocation(bucketLocationRequest);

This happens seldom and only one of our customers face it. 

If you need additional information please let us know.

Any ideas?

**Comment by klaytaybai** [comment]
If it's only one customer facing it and it is only happening sometimes, it is probably a connectivity issue.  Do you know what their network infrastructure is like?  Perhaps they are using satellites or their network connectivity is otherwise poor?

This is very unlikely to be an SDK issue.  I'll mark it as a service issue for now, and close it in a couple days unless there is reason to believe that it should be kept open.  If you have a paid support plan and wish to pursue resolving this issue for your customer, I suggest you open a ticket through your plan.  If you try that option, I suggest trying to log your requestIds and enough timestamps to be able to isolate a hanging request when asked for it later.
