### ISSUE TITLE
Net Core 2.0 AmazonServiceException: Unable to find credentials

### ISSUE THREAD

**Issue by kj1981** [aws/aws-sdk-net#1120]
I have the following code:

public void ConfigureServices(IServiceCollection services)
{
  // AWS Options
  var awsOptions = Configuration.GetAWSOptions();
  services.AddDefaultAWSOptions(awsOptions);

  var client = awsOptions.CreateServiceClient<IAmazonDynamoDB>();
  var dynamoDbOptions = new DynamoDbOptions();
  ConfigurationBinder.Bind(Configuration.GetSection("DynamoDbTables"), dynamoDbOptions);

  services.AddScoped<IDynamoDbManager<MyModel>>(provider => new 
  DynamoDbManager<MyModel>(client, dynamoDbOptions.MyModel));
}

public class DynamoDbManager<T> : DynamoDBContext, IDynamoDbManager<T> where T : class
{
    private DynamoDBOperationConfig _config;

    public DynamoDbManager(IAmazonDynamoDB client, string tableName) : base(client)
    {
        _config = new DynamoDBOperationConfig()
        {
            OverrideTableName = tableName
        };
    }       
}

My Appsettings.json is as:

{
  "AWS": {
    "Region": "us-east-1",
    "AwsId": "xxx",
    "AwsPassword": "xxx"
  },
   "DynamoDbTables": {
   "MyModel": "MyTable"
  }
}
When I run my code I am getting the error:

AmazonServiceException: Unable to find credentials
Exception 1 of 3: Amazon.Runtime.AmazonClientException: Unable to find the 'default' profile in CredentialProfileStoreChain. at Amazon.Runtime.FallbackCredentialsFactory.GetAWSCredentials(ICredentialProfileSource source) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\FallbackCredentialsFactory.cs:line 72

Exception 2 of 3: System.InvalidOperationException: The environment variables AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN were not set with AWS credentials.

Exception 3 of 3: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

I have tried many things but not getting this to work.

I can get this to work by having a local credentials file and specifying  profile location in app settings. Isnt there a way to do so without having a file. I thought there should be a simpler way of just having credentials in appsettings file.

**Comment by klaytaybai** [comment]
Hi @kj1981,

It is generally a good idea to not write your credentials directly into your application because it is too easy to accidentally share them publicly.  The recommended approach is to create a shared credentials profile and then reference whichever profile you wish to use within your app.  

[Use this link to learn more about creating a shared credentials file](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html).
[For more info, check this one out, too.](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/)

Once you have created your shared credentials profile, [configure your AWS settings in appsettings](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html)

**Comment by klaytaybai** [comment]
If you still want to put the credentials directly into your app settings, try 
```
"AWS": {
  "AccessKey": "abc",
  "SecretKey": "xyz",
  "Region": "us-east-1"
},
```
