### ISSUE TITLE
Amazon.SQS SendMessage exception

### ISSUE THREAD

**Issue by paparent** [aws/aws-sdk-net#1175]
Hi,

When I do a `SendMessage`, I get the following exception : 

`{"Could not load type 'Amazon.Runtime.Internal.InvokeOptions' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'.":"Amazon.Runtime.Internal.InvokeOptions"}`

I am using the latest version:

`AWSSDK.Core v3.3.31.2`
`AWSSDK.SQS v3.3.3.49`

**Comment by sstevenkang** [comment]
Hi. I can't repro this problem in a blank VS project.

**Comment by paparent** [comment]
@sstevenkang Were you trying with the version specified in the issue ?

**Comment by sstevenkang** [comment]
Yes.  This is what my csproj looks like:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.31.2" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.3.49" />
  </ItemGroup>

</Project>
```

**Comment by liam-careerhub** [comment]
I get the same issue when using AWSSDK.IdentityManagement 3.3.9.14 and AWSSDK.Core 3.3.31.6. When calling CreatePolicyAsync on the AmazonIdentityManagementServiceClient.
Rolling back to the previous versions I was using fixed it (3.3.5.1, 3.3.18).

I wonder if this issue is along the lines of this one, where required dependencies have been removed:

https://stackoverflow.com/questions/51315906/aws-net-sdk-dynamodb-loadasync-returning-could-not-load-type-error

**Comment by paparent** [comment]
Ok, pretty weird.. I downgraded AWSSDK.SQS to 3.3.3.17 IIRC and it worked, so didn't try further.. but since there are new versions now, i'll give it a try someday! thanks :)

**Comment by liam-careerhub** [comment]
Could you please keep the issue open? I was adding additional information about the cause of the problem and I don't believe it's fixed in AWSSDK.SQS or AWSSDK.IdentityManagement.

**Comment by sstevenkang** [comment]
Could you provide a minimal repro specifically with the latest nuget packages?

**Comment by klaytaybai** [comment]
I haven't been able to reproduce this either.  Please try updating all your AWS nuget packages and see if this still occurring.  If it is, please provide the minimal repro Steven asked for.  Be sure to not include any confidential info.  It may also be helpful to know your environment information and which framework you are targeting.

**Comment by thebeebs** [comment]
This issue is likely caused by version conflicts with Nuget and the core sdk package. I answered and solved a very similar issue on stack overflow this week https://stackoverflow.com/questions/54599210/aws-net-sdk-simpleemail-sendemail-returning-could-not-load-type-error?noredirect=1#comment95998227_54599210

**Comment by liam-careerhub** [comment]
I think you're right @thebeebs, My test repro works fine, I guess it was a nuget issue.

**Comment by klaytaybai** [comment]
Closing due to a lack of activity
