### ISSUE TITLE
DateTime properties unmarshalled as Local times

### ISSUE THREAD

**Issue by wjrogers** [aws/aws-sdk-net#1224]
https://github.com/aws/aws-sdk-net/blob/08c86fce10f9d4ef520d3f3ad23d71500d049165/sdk/src/Core/Amazon.Runtime/Internal/Transform/SimpleTypeUnmarshaller.cs#L399

From the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=netframework-4.7.2#System_DateTime_Parse_System_String_System_IFormatProvider_)
> If s contains time zone information, this method returns a DateTime value whose Kind property is DateTimeKind.Local and converts the date and time in s to local time. Otherwise, it performs no time zone conversion and returns a DateTime value whose Kind property is DateTimeKind.Unspecified.

You can see an example of this in `S3Object.LastModified` returned from `ListObjectsV2Async`. The values returned have `DateTimeKind.Local`, but the documentation comment on this property says:

> The date retrieved from S3 is in ISO8601 format. A GMT formatted date is passed back to the user.

Will you please change the `DateTimeUnmarshaller` to avoid converting the returned string to local time?

**Comment by klaytaybai** [comment]
Hi @wjrogers, thank you for reporting this.  I have confirmed that it is an issue, but I'm unsure if we're going to be able to provide a fix until we produce another major version because there will be an issue with backwards compatibility.  We could extend the documentation, but we can't totally replace that either because the response from GetObject correctly returns the UTC time.  I'll bring this up with the team and see if there is anything we can do for a workaround.

**Comment by wjrogers** [comment]
It still would be nice to see this fixed.

**Comment by wjrogers** [comment]
@ashishdhingra is it possible to re-open this issue?

**Comment by ashishdhingra** [comment]
The other issue #1885 is tracking this problem.
