### ISSUE TITLE
DoesS3BucketExistAsync returns true for a non-existing bucket

### ISSUE THREAD

**Issue by Danielovich** [aws/aws-sdk-net#1250]
This

DoesS3BucketExistAsync(client, "non-existing bucket");

returns true

The bucket does not exists though.

**Comment by sstevenkang** [comment]
This is due to eventual consistency of S3.   We already have an internal conversation going on with S3 regarding this.  We'll provide an update if there is any.

**Comment by ashishdhingra** [comment]
Reproducible using the code:
```C#
using System;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Util;

namespace S3Test
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonS3Client s3 = new AmazonS3Client();
            var exists = AmazonS3Util.DoesS3BucketExistAsync(s3, "testbucket-123456").Result;
            var existsV2 = AmazonS3Util.DoesS3BucketExistV2Async(s3, "testbucket-123456").Result;
        }
    }
}
```

Both `AmazonS3Util.DoesS3BucketExistAsync` and `AmazonS3Util.DoesS3BucketExistV2Async` return `true` for non-existent bucket.

However, AWS CLI also exhibits the similar behavior. Used the command given in the example section of https://docs.aws.amazon.com/cli/latest/reference/s3api/wait/bucket-exists.html. 
```
aws s3api wait bucket-exists --bucket my-bucket
```

The command continued which means that AWS CLI also returns true for bucket existence. Hence, it appears to be service API issue, not the .NET SDK issue.

**Comment by Kralizek** [comment]
When is the method/API call supposed to return `false`?

**Comment by ashishdhingra** [comment]
While `AmazonS3Util.DoesS3BucketExistAsync` is marked as obsolete, as mentioned in https://github.com/aws/aws-sdk-net/issues/1250#issuecomment-705138372, `AmazonS3Util.DoesS3BucketExistV2Async` also returns `true` for non-existent buckets.

**Comment by ashishdhingra** [comment]
[AmazonS3Util.DoesS3BucketExistV2Async()](https://github.com/aws/aws-sdk-net/blob/ed8e148abebbd88a8313eaf47ea207c12bcbd531/sdk/src/Services/S3/Custom/Util/AmazonS3Util.cs#L604) uses `AmazonS3Client.GetACLAsync(bucketName)` call to check for existence for bucket. While testing, for a bucket named `testbucket-123456`, it returned `StatusCode: 301, ReasonPhrase: 'Moved Permanently', hence `PermanentRedirect` exception. The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`. However, while testing for unique random bucket using `Guid.NewGuid()` for bucket name, it correctly returned exception `NoSuchBucket` and hence `false`.
```C#
using Amazon.S3;
using Amazon.S3.Util;
using System;

namespace S3BucketExists_Issue1250
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonS3Client s3 = new AmazonS3Client();
            var existsV2 = AmazonS3Util.DoesS3BucketExistV2Async(s3, Guid.NewGuid().ToString()).Result;
            Console.WriteLine($"Bucket Exists: {existsV2}");
        }
    }
}
```

The bucket `testbucket-123456` does not exist in any of the accounts. So it appears that the `GetBucketAcl` S3 service API call could return `PermanentRedirect` error for buckets in different account since S3 buckets should be unique in time and space.

@Danielovich Please use `AmazonS3Util.DoesS3BucketExistV2Async()` call to check for existence of bucket. Also take note of the above findings while relying on `DoesS3BucketExistV2Async` for any business logic. Kindly let me know if above findings provide necessary explanation of the current behavior.

Thanks,
Ashish
