### ISSUE TITLE
ACM PCA - CSR is missing required element 'attributes' 

### ISSUE THREAD

**Issue by ntthanh** [aws/aws-sdk-net#1261]
Hi,

I am using .NET SDK to call this API
https://docs.aws.amazon.com/acm-pca/latest/userguide/JavaApi-IssueCertificate.html

My code works with CSR generated openssl, but it does not work with CSR generated by BouncyCastle.  The CSR generated by bouncycastle works well with Windows CA, EJBCA.

Error message is always:
"CSR is missing required element 'attributes'."}

This is the CSR:
-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwEzERMA8GA1UEAwwIZGV2aWNlMDUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCa80T77IAd6Dlbfx2CK6tawmYXq+1XhvdNYOk2B7aY
NtFyCYSU+ZWGIpVPbea2dWSMfMO+ceUW9g7ikY3PSvkedsWpR2s8p2q4zmqTPv/t
/b77AplVTtKvWdySXFcJ/NZCum4ScGgpehZFPytP8M+bw163BOjCjbTQPkrXjnte
4Bxjp8rddg1pzegrAyF/64GKOhoo9mw2upplkGPv9zFGMfT+jU3nGGaL8iXeYhYb
nFpYpL9TIBTcfAbj51gVIxyJfc7avV2pXBG2DOpGppOz5fXXiI8GodOu6PNyNqE4
Trmk5k3TUZMLfco+XtCHLhQ8IeeelrJVqjPquVpEAUCdAgMBAAEwDQYJKoZIhvcN
AQELBQADggEBABVqpmkKkafGeNPW6mMqEBY6bdLVebJ1Rb1b4zP3BLebgbxnFTnS
eXb4MCzS4i+cwkrpjTXZ5oo8VThtvgDRrI8Wv0UzIUaMwZNL97IoGKtt9uJvUXtX
DGtHNB9n06Rd83CfPAE7tiwiCiPo8zxqfzqy75eaEy9JdgznVeG8VyR/ZC4232iR
q09m0fIjTI1AYJlJKuC7yjobYQQKXWUqz1Q3Npa+ui8n+e25R0ZrPkN+K8bxeNsI
su/gqYV0SbhJ5Y4mgBsO3Qdbiww8ohO8dsFHUTimhzQi5OVj3sQ9NlHpsj+KrJNT
rmDQemLyw7d3V338Jf7AaHcPYnubkY3fXWk=
-----END CERTIFICATE REQUEST-----

Could you please take a look?

Thanks a lot!

**Comment by klaytaybai** [comment]
Hi @ntthanh, our documentation only indicates support for OpenSSL, but I think you could use a CSR if it is in a consistent format.  You may want to verify that the specification you are using with BouncyCastle has an attributes elements (maybe PKCS10?).  If you think it does, I would suggest trying to open a ticket with Premium Support or posting in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=206) to get in contact with the Certificate Manager team.  You may also try reaching other community members via other forums, such as Stack Overflow.  This issue is unrelated to the .NET SDK, so there is not much our team is going to be able to do to help.

**Comment by ntthanh** [comment]
Thanks!
