### ISSUE TITLE
Dependency warning: "NU1603: PCLCrypto 1.0.2.15130 depends on Validation (>= 2.0.6 && < 3.0.0) but Validation 2.0.6 was not found."

### ISSUE THREAD

**Issue by ErwanJes** [aws/aws-sdk-net#1322]
When fetching `AWSSDK.Core`, I have the following warning:

```NU1603: PCLCrypto 1.0.2.15130 depends on Validation (>= 2.0.6 && < 3.0.0) but Validation 2.0.6 was not found. An approximate best match of Validation 2.0.6.15003 was resolved.```

## Expected Behavior

No warning

## Current Behavior

A lot of warnings popup with this info but it does not prevent the compilation

## Possible Solution

Update the version of `PCLCrypto` dependency.

## Your Environment

* AWSSDK.Core version used: 3.3.102.18 (but a lot of versions seem affected by this issue)
* Service assembly and version used: 
* Operating System and version: Windows 10 
* Visual Studio version: Visual Studio 2017
* Targeted .NET platform: UWP

**Comment by klaytaybai** [comment]
Hi @ErwanJes, if you want to remove the warning, you can try manually depending on Validation 2.0.6.  Otherwise, this should go away as we progress in our move from [PCL to .NET Standard](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/).

**Comment by Jacko1394** [comment]
I'm still getting this warning every morning.

**Comment by nbsoftware** [comment]
1 year later, same message still happening
