### ISSUE TITLE
API Gateway Client missing get-export call

### ISSUE THREAD

**Issue by pha3l** [aws/aws-sdk-net#1325]
The ApiGatewayV2 client does not have a method for exporting the OpenAPI documentation.  This is implemented in boto3: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigateway.html#APIGateway.Client.get_export

Is there any chance that this will be available soon?

**Comment by normj** [comment]
The export method is part of the original ApiGateway package which is what you are also using in in boto3. Currently ApiGatewayV2 is only for the websocket support. I assume the API Gateway team has future plans to merge the APIs which is why they called it V2 for now.

Use the **AWSSDK.APIGateway** NuGet package and you wiill find the GetExport method on the service client.

```csharp
using System;
using System.IO;
using System.Threading.Tasks;

using Amazon;
using Amazon.APIGateway;
using Amazon.APIGateway.Model;

namespace ConsoleApp55
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using(var client = new AmazonAPIGatewayClient(RegionEndpoint.USEast1))
            {
                var request = new GetExportRequest
                {
                    RestApiId = "t2yh6sjnmk",
                    StageName = "prod",
                    ExportType = "oas30"
                };
                var response = await client.GetExportAsync(request);
                using(var reader = new StreamReader(response.Body))
                {
                    Console.WriteLine(reader.ReadToEnd());
                }
            }
        }
    }
}
```
