### ISSUE TITLE
Can't find resource base on TrustedAdvisorResourceDetail.ResourceId

### ISSUE THREAD

**Issue by macpak** [aws/aws-sdk-net#1327]
AWSSDK.AWSSupport allows to download check results which contain a collection of TrustedAdvisorResourceDetail objects, and each of those objects contains ResourceId property.  I'd assume it's an ARN of the affected resource, but instead I get sth that looks like: 
`maFGTqmNMqTR7BhCBJukNN2fOupkHwdp75g0ef5_qKo`
Can I use some sort of API to get ARN based on that ResourceId ?

**Comment by klaytaybai** [comment]
Hi @macpak, unfortunately I don't have a great answer for you at the moment.  Since this issue is more of a usage question that is unrelated to the .NET SDK, I would typically refer you to Stack Overflow or the AWS Forums instead, but I see that you've already done that.  I've reached out to the Trusted Advisor team to see if they can provide some more guidance on this.  I'll let you know when I hear back from them and keep this open temporarily in the meantime.

**Comment by klaytaybai** [comment]
This is being treated as a feature request to add ARNs to the response from the service API.  We'll get the change when its made.  Thanks for the feedback.

**Comment by macpak** [comment]
@klaytaybai Thanks for your response, highly appreciated. One more question: with the current implementation, is there a way to get ARN based on that ResourceId (by calling some sort of API, etc.) ?

**Comment by brokenjpl** [comment]
Also interested in this but with the Java SDK. Currently the TrustedAdvisorResourceDetail value is meaningless.

**Comment by klaytaybai** [comment]
As far as I know, there isn't a way to get the ARNs based on the ResourceIds.  

@brokenjpl, the Java SDK should also get the changes if the service change is made.
