### ISSUE TITLE
region in config file profile not honored

### ISSUE THREAD

**Issue by jgardsentry** [aws/aws-sdk-net#1349]
**Expected Behavior**
Using config and credentials files together, the region defined in config is not honored.

**Current Behavior**
Unless defined elsewhere, a "no region" error is thrown.

**Steps to Reproduce (for bugs)**
~/.aws/credentials file contains (obfuscated of course):
```
[credprofile]
aws_access_key_id=ASIAABCDEFG
aws_secret_access_key=ABCDEFGHIJK012345
aws_session_token=ABCDEFGHIJK012345ABCDEFGHIJK012345ABCDEFGHIJK012345
```

~/.aws/config file contains:
```
[profile configprofile]
role_arn = arn:aws:iam::0123456789:role/my-crossaccount-role
source_profile = credprofile
region = us-east-2
```

Running an AWSPowershell cmdlet results in:
```
PS > Get-EC2Instance -ProfileName configprofile
Get-EC2Instance : No region specified or obtained from persisted/shell defaults.
```

**Your Environment**
* Affected module: AWSPowerShell **and** AWSPowerShell.NetCore 
* Module version: 3.3.509.0 for both.
* Operating System and version: Microsoft Windows 10.0.17763
* PowerShell versions: Desktop: 5.1.17763.503, Core: 6.2.1

**Comment by matteo-prosperi** [comment]
Transferring this issue to the AWS SDK for .NET repository because the root cause of the issue is there.
For reference, this is tracked internally as `DOTNET-3195`.

**Comment by matteo-prosperi** [comment]
Useful references.

Similar issues for other SDKs are here: https://github.com/aws/aws-sdk-java/issues/1707, https://github.com/boto/botocore/issues/1511.
The format of the `config` file is defined (here)[https://docs.aws.amazon.com/cli/latest/topic/config-vars.html].

**Comment by matteo-prosperi** [comment]
This is a known issue related with the AWS SDK for .NET (and possibly other SDKs) looking for a `[profile default]` entry (instead of a `[default]` entry) in the `config` file.
Fixing this issue has backward compatibility concerns: this would change the behavior for:
- users who have `[profile default]` in their `config` file because that configuration would not be used anymore (unless we allow reading `[profile default]` as fallback in case `[default]` is not present.
- users who have `[default]` in their `config` file because we would start using that configuration.
- users who have both `[default]` and `[profile default]` in their `config` file (with different configurations) because we would switch from using the latter to the former.

We will likely be able to address this only in a major version bump of the SDK when subtle backward incompatible changes are expected.

@jgardsentry You could try one of these workarounds:
- Add a `[profile default]` section to the `~/.aws/config` file. You can also leave a `[default]` section with the same configurations in the file in order not to break the behavior of the AWS CLI or other SDKs.
- Add the region configuration to the `[default]` section in the `~/.aws/credentials` file.
