### ISSUE TITLE
doesn't work unity aws sdk for android arm64(working on unity2018.2.14f1)

### ISSUE THREAD

**Issue by FirstSuns** [aws/aws-sdk-net#1351]
I use unity2018.2.14f1 and android version
google store ask support arm64 from 1.aug.2019
but it is doesn't work
please help me.
please provide the dll for arm64

**Comment by Ethan-VisualVocal** [comment]
to clarify a little more: various AWS SDK unitypackages provided include an "armeabi-v7a" compatible build of `libsqlite3.so` but are missing the "arm64-v8a" compatible build of `libsqlite3.so` -- as a result, making an Android ARM64 build is missing the libsqlite3 dependency.

**Comment by matteo-prosperi** [comment]
Android arm64 applications are not supported by the AWS Mobile SDK for Unity.
We recommend to use the AWS SDK for .NET Standard 2.0 instead. You can find some instructions on how to reference it from Unity in [this blog post](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/).
Compared to the Mobile SDK, the AWS SDK for .NET Standard 2.0 has support for all AWS services and it is updated daily.
Please consider that the AWS SDK for .NET is not API-compatible with the AWS Mobile SDK for Unity, so you will need to change some of your code to reference the new APIs.
In case some mobile-specific or Unity-specific feature are missing from the AWS SDK for .NET Standard 2.0, you can open an issue here and we will consider it for future development.

**Comment by matteo-prosperi** [comment]
Hello,
in case you decide to use the .NET Standard 2.0 version of the AWS SDK for .NET we have made available a [download in .zip format](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip) that should be more convenient for Unity users (we also have version specific downloads using a URI like [this one](https://sdk-for-net.amazonwebservices.com/releases/aws-sdk-netstandard2.0-3.3.590.0.zip)).
We have also continued our testing and, whenever using IL2CPP, we recommend to add a file named `link.xml` in your project assets and configure it so that IL2CPP doesn't strip any of the AWSSDK assemblies.
It should look like this:
```
<linker>
       <assembly fullname="AWSSDK.Core" preserve="all"/>
       <assembly fullname="AWSSDK.DynamoDBv2" preserve="all"/>
       <assembly fullname="AWSSDK.Lambda" preserve="all"/>
</linker>
```
Please make sure to include all the AWSSDK dlls that you are using.
The usage of `link.xml` is described [here](https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html).

**Comment by zhmxiaowo** [comment]
@matteo-prosperi your framework is work!!! i just can't believe it.thanks a lot!
Envirement: iOS Android li2cpp build by Unity 2018.4.14f

**Comment by NGL321** [comment]
Looks like this was resolved by @matteo-prosperi's comment!

Please leave a new comment if this is not the case, and we will keep the issue open.

😸 😷
