### ISSUE TITLE
Write-S3Object: Method Not found

### ISSUE THREAD

**Issue by campanellaf** [aws/aws-sdk-net#1357]
> Hi,
> 
> I've had a look around and I don't think this has been raised before, I've also done some searching of the internet to find similar experiences, I have found this: and neither of the responses have solved my issue.
> 
> I am trying to write an object to an S3 bucket using the following cmdlet:
> 
> Write-S3Object -Region "eu-west-1" -BucketName "bucketName" -File "X:\FileName"
> 
> I'm getting the following error:
> 
> Write-S3Object : Method not found: 'Void
> Amazon.S3.Transfer.TransferUtilityUploadRequest.set_TagSet(System.Collections.Generic.List`1<Amazon.S3.Model.Tag>)'.
> At O:\ScriptName.ps1:35 char:9
> 
>     Write-S3Object -BucketName "bucketname" -Key $ ...
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo : NotSpecified: (:) [Write-S3Object], MissingMethodException
> FullyQualifiedErrorId : System.MissingMethodException,Amazon.PowerShell.Cmdlets.S3.WriteS3ObjectCmdlet
> I've tried passing a variety of different parameters with the cmd and I've also checked that the powershell module is installed and imported by successfully executing cmdlets like:
> 
> get-s3bucket | get-s3Object
> 
> get-s3bucket | Get-S3BucketLocation
> 
> My .NET versions are: 4.6.1 and 3.5.30729
> 
> If anyone has any help, it would be greatly appreciated.
> 
> Thanks,
> Tom.

> I just had this same issue, and this spacific issue it has nothing to do with .Net 3.5 vs .Net 4.5. It has to do with the release of breaking changes being introduced between release with out a version update of the assembly to notate there is a difference between the two. I was referencing the AWSSDK.Core v3.3.101.17 in my own Cmdlet. I noticed if I ran a AWSPowerShell cmdlet first, I would get a 'Method not found' exception in my cmdlet, if ran it afterwards in the same session. I compared the SDK referenced in AWSPowerShell v3.3.509.0 to my module and noticed that the AssemblyFileVersion were different, but the AssemblyVersion were the same. I don't think you guys are versioning the assembly correctly when breaking changes are introduced. .Net only uses the AssemblyVersion value to compare if a assembly is the same or not. And, in this case, the two assemblies that are versioned as being the same are NOT the same. So PowerShell is loading the assembly from AWSPowerShell into memory and trying to use it for my cmdlet module which references a different version. This also happens in reverse if I run my cmdlet first, and then a AWSPowerShell cmdlet, it gives a similar error about not matching.
> 
> My error
> 
> Method not found: 'System.IAsyncResult Amazon.Runtime.SharedInterfaces.ICoreAmazonS3.BeginDelete(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.Object>, System.AsyncCallback, System.Object)'.
> Observation
> Interface Amazon.Runtime.SharedInterfaces.ICoreAmazonS3
> 
> SDK v3.3.101.17 (My module cmdlet)
> AssemblyVersion set to only 3.3 - Should be different
> ICoreAmazonS3 Has NO BeginDelete method
> SDK v3.3.101.9 (AWSPowerShell v3.3.509.0)
> AssemblyVersion set to only 3.3 - Should be different
> ICoreAmazonS3 Has BeginDelete method
> Side Note: Not sure why a newer version would be missing methods, looks like maybe Async calls where removed in new method?
> 
> Update: So... after much more digging, I noticed that the AWSPowerShell module is referencing the .Net 3.5 AWSSDK libraries. Again, since there is no difference in the eyes of .Net CLR between the two libraries, it chokes. There should be some difference between the libraries. Maybe naming the files with Net35 like AWSSDK.Core.Net35.dll?

I am having this problem when trying to run Get-S3Object.

The original issue was closed due to inactivity and never solved.

**Comment by klaytaybai** [comment]
#968 mentioned

**Comment by matteo-prosperi** [comment]
Hello,
Thanks for the detailed description. Changing any of the behavior you describe (e.g. changing the name of the assemblies) would be a breaking change for all our customers. But I can provide some clarification about how versions and platforms work for the SDK and some suggestions on how to work around the issues you describe.

About versioning, all SDK libraries are supposed to be backward compatible (within the same platform, more about this later). So, `AWSSDK.Core.dll v3.3.101.17` is supposed to have all methods and classes that are present in `AWSSDK.Core.dll v3.3.101.9`.
`AWSSDK.Core.dll v3.3.101.17` could have additional methods and classes not present in `AWSSDK.Core.dll v3.3.101.9`.
The behavior, except for bugfixes should also be backward compatible.
For these reason all these libraries are all marked with the same assembly version: `3.3`. You should always be able to use a newer `3.3` library in place of an older one. If possible, I would still suggest to recompile and test your application, as an extra precaution, when updating the SDK libraries.
So, if both modules target libraries for the same platform, loading the module which has the more recent SDK libraries first should solve the problem.
Whenever possible, I would suggest to try using the same versions of SDK libraries across modules that are meant to work together, this will make your life easier. Updating AWSPowerShell to the latest version and then using the same version of SDK libraries used by AWSPowerShell may be a good idea.

About different platforms, the SDK comes in different "flavors" (.NET 3.5, .NET 4.5, .NET Standard 2.0...). Mixing different "flavors" together is not supported.
If you are the author of the other module, you could consider one of these options:
- target .NET Framework 3.5 (or 4.0) 
  - consume the .NET 3.5 flavor of the AWSSDK libraries
- continue targeting a newer Framework
  - **explicitly** consume the .NET 3.5 flavor of the AWSSDK libraries
- target .NET Framework 4.7.2 (or later)
  - **explicitly** consume the .NET standard 2.0 flavor of the AWSSDK libraries
  - use [AWSPowerShell.NetCore](https://www.powershellgallery.com/packages/AWSPowerShell.NetCore) instead of AWSPowerShell
- target .NET Standard 2.0
  - consume the .NET standard 2.0 flavor of the AWSSDK libraries
  - target [PowerShell Standard](https://github.com/PowerShell/PowerShellStandard) instead of `System.Management.Automation`
  - use [AWSPowerShell.NetCore](https://www.powershellgallery.com/packages/AWSPowerShell.NetCore) instead of AWSPowerShell.

The last one would be my favorite option because it would allow your module to run on non-Windows platforms and on PowerShell 6.0+. 
Please consider that you will need  .NET Framework 4.7.2 installed to reliably use .NET Standard libraries in PowerShell 3, 4 or 5 (not needed for PowerShell 6.0+).
You can have a look at [this post](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/) about how to **explicitly** consume the .NET Standard 2.0 flavor of the SDK from a .NET Framework 4.7.2 project (the same also apply to consuming the .NET 3.5 flavor from a .NET Framework 4.5+ application).

**Comment by johnwc** [comment]
@matteo-prosperi I disagree with your statement about renaming the library would be a breaking change. These are NuGet packages, not off the shelf software updates that get pushed out. If you started producing the libraries with the correct file name convention for each .Net version, then any future project that is building off of them would automatically start using the new file name, with no user intervention needed at all. For any project that is referencing your packages, all new revisions of the app/library/module would then ship with the new file names. All older builds would still reference and ship with the old file names. (Possibly getting caught up with issues like this one described.)

No one is saying to go back and rename the existing libraries that are already published, that would cause the breaking change. Just put in a file name convention moving forward so that they are named appropriately for all new NuGet packages. What you have today is causing a lot of headaches that can be avoided fairly easliy.

Instead of all being AWSSDK.Core.dll, there should be AWSSDK.Core.Net35.dll, AWSSDK.Core.Net4.dll, AWSSDK.Core.NetStandard2.dll, etc..

Also, 4.7.1 is not a requirement to consume .Net Standard libraries in .Net Framework PS modules. Net Framework 4.6.1 is the minimalist requirement. All of my prior PS 5 modules where targeting 4.6.1 and did not have any issues using .NetStandard libraries. For reference:  https://github.com/dotnet/standard/issues/481

**Comment by matteo-prosperi** [comment]
@johnwc Please consider that some of our customers don't consume the AWS SDK for .NET as NuGet packages, they download and target the .dll files directly in their projects. Also renaming the assemblies would not solve the problem completely unless we also use different namespaces for the different platforms (and that would be an ever larger breaking change).

About 4.6.1 support for .NET Standard 2.0, I usually suggest customers to update to .NET Framework 4.7.2 (4.6.1 and 4.7.2 can be installed on the [same range of Windows Server versions](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)). Pre-4.7.2 support of .NET Standard 2.0 is somewhat spotty. As reported [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard):
```
While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0,
there are several issues with consuming .NET Standard libraries that were built for those
versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use
such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2
or higher.
```
Obviously your success will vary depending on the actual installed Framework version and which APIs you are using.

**Comment by johnwc** [comment]
@matteo-prosperi For the customers that manually download the SDKs, yes they would have to target the new name. They are already doing a manual process of getting the SDK in a fashion other than NuGet, so they would have to manually edit the project to point to the new location of the SDK anyway. I don't see how fixing the file name adds any additional steps for those types.

Also, two libraries are very much able to contain the same namespaces and be loaded and used in the same domain. You can even use them in the same project, utilizing aliases. This would not be an issue for other projects, as the library(dll) filename is bound at compile time, forcing the exe/dll to use the namespace+type of the correct library named AWSSDK.Core.Net4.dll instead of the same type in the same namespace in AWSSDK.Core.Net35.dll. The CLR does not just look to see what namespaces are loaded in domain and execute them if they match. It does this based on if the library is loaded already with the same filename, it then tries to execute the method of the type. That is exactly the error that we are seeing in this issue and trying to fix.

**Comment by ashishdhingra** [comment]
Hi @campanellaf,

Good afternoon.

I was going through the backlog and came across this issue. Could you please confirm if this is still an issue with the latest version of AWS Tools for PowerShell? If it is still an issue, kindly provide the same code to reproduce the issue.

Thanks,
Ashish
