### ISSUE TITLE
CloudWatch query with DateTime

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-sdk-net#1385]
Currently, `StartQueryRequest` `StartTime` and `EndTime` are not using DateTime, or DateTime.Ticks

From the doc, these 2 fields are 
> Specified as epoch time, the number of seconds since January 1, 1970, 00:00:00 UTC.

## Expected Behavior
Both `StartTime` and `EndTime` accept `DateTime`

## Current Behavior
``` C#
new StartQueryRequest
{
    LogGroupName = _config["LOG_GROUP_NAME"],
    StartTime = DateTime.UtcNow.AddMinutes(-1).Ticks,
    EndTime = DateTime.UtcNow.Ticks,
    QueryString = "{ $.Level=\"Error\"}"
}
```
This will return **Invalid time range specified**
And need to calculate the time on our own

``` C#
new StartQueryRequest
{
    LogGroupName = _config["LOG_GROUP_NAME"],
    StartTime = (long)(DateTime.UtcNow.AddMinutes(-1) - new DateTime(1970, 1, 1)).TotalSeconds,
    EndTime = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds,
    QueryString = "{ $.Level=\"Error\"}"
}
```

## Your Environment

* AWSSDK.Core version used: 1.1.0
* Service assembly and version used: AWSSDK.CloudWatchLogs 3.3.101.13
* Operating System and version: Windows 10
* Visual Studio version: 2019 16.2.2
* Targeted .NET platform: Core 2.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks @jasonycw.  It would need to be done with alternative properties (e.g. StartTimeDateTime).  We'll consider it.

**Comment by jasonycw** [comment]
Another suggestion from https://github.com/aws/aws-sdk-net/issues/1387

If only `StartTime` is provided, then `EndTime` will automatically set as now, so we can query the latest log from last n minutes like
``` C#
new StartQueryRequest
{
    LogGroupName = _config["LOG_GROUP_NAME"],
    StartTime = DateTime.UtcNow.AddMinutes(-n)
    QueryString = "filter Level=\"Error\""
}
```

**Comment by klaytaybai** [comment]
That seems appropriate, but users would also need to remember that it would only get the latest logs as of the StartQueryRequest.  In that regard, adding an EndTime might be clearer.

**Comment by jasonycw** [comment]
I am not sure if that's just me understanding this way.
But if I only specified EndTime only, I expect to query everything until EndTime since beginning of time
and if I only specified StartTime only, I expect to query everything from StartTime until end of time(which is now)

**Comment by gregswdl** [comment]
I would like to second this. I lost some time today because a library I was using gave me seconds instead of millisecond epoch time. Some APIs in CWL already do offer `System.DateTime`:
- GetLogEventsRequest
- InputLogEvent
- LogGroup
- LogStream
- MetricFilter
- OutputLogEvent

However, most use Long:
- CreateExportTaskRequest
- Destination
- ExportTask
- ExportTaskExecutionInfo
- FilteredLogEvent
- FilterLogEventsRequest
- GetLogGroupFieldsRequest
- QueryDefinition
- QueryInfo
- ResourcePolicy
- StartQueryRequest
- SubscriptionFilter

Consistency would at least be nice, though offering the idiomatic form would be preferred.

For new properties, you could use a suffix like `Utc` to clarify that this is not system-local time. E.g. `StartQueryRequest.StartTime` is still `long` to maintain compatibility, but `StartQueryRequest.StartTimeUtc` is `System.DateTime` and assumed to be in UTC. Setting one of those properties would also set the other with a simple conversion.
