### ISSUE TITLE
Urgent pull request that needs attention

### ISSUE THREAD

**Issue by sampaiodias** [aws/aws-sdk-net#1407]
I'm sorry to break the post guidelines, but I think it is for good reason.

The current version of the SDK for Unity does NOT work for most 2018 versions of Unity and every 2019 versions. This issue has been reported multiple times for MONTHS, and still no concrete action has been taken by aws devs.

However, the solution to this issue already exists! It is available through [this pull request](https://github.com/aws/aws-sdk-net/pull/1295), which have been tested by multiple community members as agreed to be the solution to this bug.

So please, I beg you guys to fix this: You only need to 1) merge the pull request and 2) release a new version of the SDK with the changes made by the pull request.

**Comment by klaytaybai** [comment]
Hi @sampaiodias, we're transitioning our Unity support to instead use our SDK targeted to .Net Standard 2.0.  As part of this change, the pull request that you mention would be invalid because the affected file is going to be removed.  You can find out more about this transition at this [pull request](https://github.com/aws/aws-sdk-net/pull/1394) and these blog posts:  https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/
https://aws.amazon.com/blogs/developer/aws-sdk-for-net-now-targets-net-standard-2-0/
