### ISSUE TITLE
Getting IAM security credentials blocks in Async methods

### ISSUE THREAD

**Issue by alandoherty** [aws/aws-sdk-net#1422]
## Expected Behavior

Calling asynchronous methods should never block the thread. Grabbing the security credentials from the IAM metadata service should be done asynchronously.

## Current Behavior

When calling async methods inside `AmazonSQSClient`, the method blocks when attempting to get security credentials from the EC2 instance metadata service when none are available. This underlying request should be asynchronous. The effects are most visible when running locally and the EC2 instance metadata service is not available, blocking the current thread for 10-15 seconds. This problem probably exists on other clients and other methods in `AmazonSQSClient`.

As far as I can tell this is due to a property being used to obtain the credentials, resulting in blocking when none are available in memory.

## Steps to Reproduce (for bugs)

Here is an example program which helps show the issue, I am using .NET Core 2.2 and AWSSDK.SQS 3.3.102.14. It should not matter what runtime you use as long as you run locally where no EC2 metadata service is present and no environment variables provide credentials.

```
/// <summary>
/// Does not matter what the queue URL is, as long as it is valid.
/// </summary>
static async void MessageLoop()
{
    AmazonSQSClient client = new AmazonSQSClient(RegionEndpoint.EUWest2);
    var response = await client.ReceiveMessageAsync(new ReceiveMessageRequest() {
        WaitTimeSeconds = 8,
        QueueUrl = "<insert a valid queue>"
    }).ConfigureAwait(false);
}

static void Main(string[] args)
{
    Console.WriteLine("Starting!");
    MessageLoop();
    Console.WriteLine("This should print instantly, even if the method above will throw an exception!");

    while (true) { }
}
```

## Your Environment

* AWSSDK.Core version used: v3.3.103.46
* Operating System and version: Windows 10
* Visual Studio version: 16.2.3
* Targeted .NET platform: .NET Framework 4.7.2

**Comment by klaytaybai** [comment]
We can look into this more, but you should be providing [credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) of some means.  Doing so shouldn't slow this down so much.

**Comment by alandoherty** [comment]
@klaytaybai Understood, I only ran into this when accidentally running an EC2 role based project locally. I was confused as to why an asynchronous task was blocking, while I understand this should only be ran once at the application startup it is still bad practice to have any blocking IO inside an asynchronous task method.

In a practical example a badly configured network setup on an instance OS could result in code unexpectedly blocking which could have any number of undefined side effects.

**Comment by DTTerastar** [comment]
I'm also getting this.  We need async for creds.

**Comment by ashishdhingra** [comment]
Hi @alandoherty,

Good afternoon. I was going through the issue backlog and came across this guidance question.

As @klaytaybai mentioned, credentials need to be provided by some means. The AmazonClient tries to resolve credentials from different sources and then eventually errors out if credentials are not resolved. Also, the credentials are needed for further interactions with the service. 

Looking at your program, looks like the `MessageLoop()` call inside the Main() method executes synchronously. Changing the line to the below would execute `MessageLoop` in a separate thread and print the next console message instantaneously:
```C#
Task.Run(MessageLoop);
```

Here's the complete code:

```C#
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.SQS;
using Amazon.SQS.Model;

namespace SQSTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Starting!");
            Task task = Task.Run(MessageLoop);
            Console.WriteLine("This should print instantly, even if the method above will throw an exception!");
            Task.WaitAll(task);
            while (true) { }
        }

        /// <summary>
        /// Does not matter what the queue URL is, as long as it is valid.
        /// </summary>
        static async void MessageLoop()
        {
            AmazonSQSClient client = new AmazonSQSClient(RegionEndpoint.EUWest2);
            var response = await client.ReceiveMessageAsync(new ReceiveMessageRequest()
            {
                WaitTimeSeconds = 8,
                QueueUrl = "<insert a valid queue>"
            }).ConfigureAwait(false);
        }
    }
}
```

As seen in the above code, you might want to use `Task.WaitAll()` to wait for pending tasks to complete. Also, you need to somehow handle exceptions generated in the `MessageLoop()` method.

Please let me know if this provides guidance and if this issue could be closed.

Thanks,
Ashish

**Comment by alandoherty** [comment]
Hi @ashishdhingra, the example I gave was a limited example to demonstrate the problem that could be modified to not block in asynchronous paths. There are many scenarios where it's not possible to obtain a synchronous context, for example if you dependency inject the clients or application code lives entirely in an asynchronous context. It's been a while since I reported this issue, but from what I remember the bigger problem was when failure occurs.

If the credentials are obtained synchronously they are usually only done so once (as far as I know), so a 500ms~ period where a response thread is tied down doesn't cause too many issues and isn't exploitable as a DoS attack. When credentials being obtained fails the entire thread can be blocked for 10-15 seconds.

Ideally the credentials would be obtained on the first call to an asynchronous method on a client object, instead of the constructor.

**Comment by ashishdhingra** [comment]
@alandoherty I get the point what you are saying. When using statement `AmazonSQSClient client = new AmazonSQSClient(RegionEndpoint.EUWest2)`, since credentials are not supplied to the constructor, it would try to resolve the credentials from various sources (in specific order). In the current design, the credentials resolution call takes place synchronously which could block the calling thread momentarily. That's why the workaround in the example above is provided to invoke `MessageLoop` asynchronously. Also, as @klaytaybai mentioned, the credentials need to be resolved before invoking any service operations on the client. 

The other workaround could be to have a Singleton instance of the client object which is initialized first time it is used or as part of application initialization, in a separate thread. The only special case to handle here is to refresh temporary credentials (is used) when these expire.

Kindly note that the client objects support synchronous methods as well. I'm not sure what benefit it would be to resolve the credentials during the first invocation of a method than in the constructor, other than (possible) added complexity. If credentials fail to resolve, then that would also block method invocation. As a principle, calls to service methods on client should only occur once the credentials are resolved, not otherwise.

Please let me know if this provides guidance or feel free to convert this into feature request (by selecting `feature-request` and removing `guidance` label), it could be investigated in future sprints based on developer's bandwidth.

Thanks,
Ashish
