### ISSUE TITLE
Tasks.TaskCanceledException from AmazonKinesisClient

### ISSUE THREAD

**Issue by maghis** [aws/aws-sdk-net#1446]
## Expected Behavior
The correct specific exception should be thrown.

## Current Behavior
We (adding @Frank-Krick) are occasionally getting TaskCancelledException from two API calls: `PutRecordsAsync` and `DescribeStreamAsync`.

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

This is happening on dotnet core 3.0 using AWSSDK.Kinesis v 3.3.100.93.

**Comment by klaytaybai** [comment]
Thanks for the feedback on the error message.  This can sometimes occur due to timeouts, interrupted connections if using websockets, or misconfigured VPC endpoints (should be consistent).  Do you have any more information for us to help identify your issue?

**Comment by Frank-Krick** [comment]
This started to happen after the upgrade. I see about 10 of these exceptions per hour. The weird thing is that the exception was not visible on the outside before. Maybe there were changes to the way timeouts in the client are handled or the exception is not caught anymore.

Beforehand the impression we got is that the client would retry in case of intermittent failures which should include timeouts in our opinion.

**Comment by normj** [comment]
The SDK does retry for intermittent failures. Did you mean upgrade to .NET Core 3.0 or upgraded version of the AWS SDK for .NET? If it was the SDK from which version did you upgrade from?

**Comment by Frank-Krick** [comment]
AWSSDK.DynamoDBv2 from 3.3.101.82 to 3.3.101.84
AWSSDK.Kinesis from 3.3.100.91 to 3.3.100.93

**Comment by normj** [comment]
There is nothing in these version changes that could affect retry behavior. Basically what has changed for DynamoDBv2 and Kinesis is the AWSSDK.Core has had the endpoint definitions file updated for services getting expanded into new regions.

Can you think of anything else that might have changed in your environment?

**Comment by maghis** [comment]
@normj the environment did not change at all on our side. Any chance there has been some other change in `AWSSDK.Core` that might have caused the new behavior?
It's possible that it was happening before and maybe we haven't noticed it because of low frequency.

**Comment by normj** [comment]
Version 3.3.101.82 of AWSSDK.DynamoDBv2 was released 10/28/2019 which was a release to say update to the latest AWSSDK.Core which had updated ends points file added to it. Since then we have only had commits to AWSSDK.Core for the end points file. Below are the commits I'm talking about

987d9cef4d80b542fe8e06c6933fc04f3c3b93e0
36cfc28c60150dabbf53f1e231e80a0c40d2183d
018d3237d97ea57f2bd881a599936ea5714202dc
2e433d70012310e89691df29d748e5e32a2a7453
a1ec5fa7d68662644086907f91040a754165a0bd

So I don't believe the problem is happening due to the SDK upgrade. Can you describe the environment your application is running in? Lambda, ECS, EC2 or maybe running outside of AWS? Has the traffic level changed for your application lately?
