### ISSUE TITLE
Aws Unity Sdk with Magic Leap

### ISSUE THREAD

**Issue by cribin** [aws/aws-sdk-net#1524]
Does the Aws Unity SDK work with the Magic Leap Device ? 
I'm using Unity 2019.2.19f1 and the newest Aws Sdk for Unity(aws-sdk-unity_3.3.674.0).
## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @cribin, we are deprecating support for the AWS SDK for Unity and highly encourage all Unity customers to switch to using AWS SDK for .NET dlls targeting .NET Standard 2.0.  Existing builds of the AWS SDK for Unity are known to have compatibility problems that are not going to be supported.  By switching to the .NET Standard 2.0 dlls, you get improved asynchronous support and access to all AWS services.

Please see the below blog details for more details.
https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/
https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

We recognize that references to the AWS SDK for Unity still exist in many of our docs, and we plan to remove these in the future.

**Comment by cribin** [comment]
Thanks for the reply @klaytaybai. I'm using now the AWS SDK for .Net in my project, but I receive still the same error on the Magic Leap device when trying to create the AWS credentials:
[AwsNetMagicLeapStackTrace.txt](https://github.com/aws/aws-sdk-net/files/4184823/AwsNetMagicLeapStackTrace.txt)

I'm not sure if this error is related to the AWS SDK or the Magic Leap device. Do you have an idea what the cause could be?

Best,

Ribin

**Comment by klaytaybai** [comment]
Can you please let us know which DLLs you are using?  You'll need to target .NET Standard 2.0 and use the DLLs in https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/.  

Also, are you specifying a custom endpoints.json file?  You probably shouldn't be, but that could cause your problem if it is being incorrectly done.

**Comment by cribin** [comment]
1.  
I'm using the newest dlls as specified in your link (aws-sdk-netstandard2.0-3.5.0.0-beta).

2.
I included the AWSSDK.Core,CognitoIdentity, S3, DynamoDBv2 and SecurityToken dlls to the plugins folder of my Unity project.

3.
I'm targeting the .NET standard 2.0 and I'm building with ILL2CP. Hence I have also added a link.xml to my project.(see 
[link.zip](https://github.com/aws/aws-sdk-net/files/4197005/link.zip)


4. 
The error only occurs  when I run the build on the Magic Leap Device, but in the Unity Editor there is no issue.

5. 
I'm not using a custom endpoints.json file.

**Comment by cribin** [comment]
@klaytaybai any updates on this issue. Do you require more information?

Best,

Ribin

**Comment by NGL321** [comment]
Hey @cribin,

Sorry for the delayed response. This will be very difficult for us to reproduce due to limited (or nonexistent 😉) access to a magic leap device at the moment.
If you are still experiencing this issue, I am happy to look into it further though.

I see that this was likely not a Unity SDK specific issue, but please note, [as of SDK v3.5](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-now-generally-available/) we no longer separate Unity support from regular .NET support, if you are having trouble with this transition, please make sure you are [targeting ^.NET 4.0 or ^.NET Standard 2.0](https://docs.unity3d.com/2020.1/Documentation/Manual/dotnetProfileSupport.html) using Unity 2018.0 or later. This means that you can have full access to AWS services when using the .NET SDK with Unity, but if you would still like to use the legacy SDK for Unity, you can reference it from our [archive repo](https://github.com/aws/aws-sdk-unity-net).

Let me know if you are still struggling with this and I will take a closer look!

😸 😷
