### ISSUE TITLE
MediaConvert OutputDetail missing List<string> outputFilePaths property from model

### ISSUE THREAD

**Issue by Projkt-James** [aws/aws-sdk-net#1560]
Using MediaConvert events rule via Cloudwatch the event object includes an outputFilePaths string array as part of the OutputDetail object. This property isn't modelled in the SDK object.

## Expected Behavior
Access to the object property when parent structure is serialised as MediaConvert.OutputGroupDetail

## Current Behavior
Object property isn't modelled

**Comment by ashishdhingra** [comment]
Hi @Projkt-James,

Looks like you are refering to [OutputDetail](https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Services/MediaConvert/Generated/Model/OutputDetail.cs#L34) class. Could you please point me to the source or service API reference which states that there should be an `OutputfilePaths` property of type `List<string>`. I referred to Java SDK's [OutputDetail](https://github.com/aws/aws-sdk-java/blob/dd9463550c6c2847e2688c79fd1c430278fdacfe/aws-java-sdk-mediaconvert/src/main/java/com/amazonaws/services/mediaconvert/model/OutputDetail.java#L27) class and there is no such property there as well.

Thanks,
Ashish

**Comment by Projkt-James** [comment]
Hi @ashishdhingra 

You are correct in the class I am referring to, which is wrapped by https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/MediaConvert/TOutputGroupDetail.html. Please see the [following docs ](https://docs.aws.amazon.com/mediaconvert/latest/ug/output-file-names-and-paths.html) for information about the COMPLETE CloudWatch Event which returns a result object under the name 'outputGroupDetails'.

**Comment by ashishdhingra** [comment]
Hi @Projkt-James,

Good afternoon.

I could not find any reference for `OutputDetail` class in [AWS Elemental MediaConvert API Reference](https://docs.aws.amazon.com/mediaconvert/latest/apireference/custom-endpoints.html). Also, the other SDKs model the `OutputDetail` class the same way as .NET SDK does (for example, refer Java SDK https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/mediaconvert/model/OutputDetail.html). Looks like for [Using CloudWatch Events with AWS Elemental MediaConvert](https://docs.aws.amazon.com/mediaconvert/latest/ug/cloudwatch_events.html), you would need to model custom classes since there are missing in https://github.com/aws/aws-lambda-dotnet. Given the above findings and since this appears to be the Lambda specific scenario (kindly confirm), this issue should be transferred to https://github.com/aws/aws-lambda-dotnet repository. Please confirm and advise if you would be willing to submit PR in the https://github.com/aws/aws-lambda-dotnet repo for MediaConvert CloudWatch events under https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.CloudWatchEvents.

Thanks,
Ashish
