### ISSUE TITLE
AssumeRoleWithWebIdentityCredentials throws exception on startup with credentials setup

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-sdk-net#1564]
I am trying debug my program that use AWS SDK on my Windows machine for months and it has been pretty smooth.
But recently, I start encounter strange exception when I start my project locally.
It will throw `ArgumentNullException`, saying "**The webIdentityTokenFile must be an absolute path.**" on startup no matter which project I run
![image](https://user-images.githubusercontent.com/4518597/77889499-83376180-72a0-11ea-8978-35dc73b1b1e7.png)
![image](https://user-images.githubusercontent.com/4518597/77889391-571be080-72a0-11ea-9d8d-81e319f4ee95.png)

For some projects (e.g. mvc service), I can just click continue in VS and the service will continue normally and configs are loaded properly. But some project, the exception will break the start up and nothing can continue. Currently got no clue why the exception happens.

I used AWS CLI `aws configure` to set my credential long time ago
Credential and config files are under `C:\Users\{username}\.aws`
And in my environment variable, there are only `aws_access_key_id` and `aws_secret_access_key`

## Expected Behavior
There should be no such exception during project startup with the current credential setting

## Current Behavior
The exception is thrown from here according to the stack trace
https://github.com/aws/aws-sdk-net/blob/9e4669c29cd09798a3de4700550ed495f3ace79c/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bnetstandard/AssumeRoleWithWebIdentityCredentials.cs#L95
Which is coming from 
https://github.com/aws/aws-sdk-net/blob/9e4669c29cd09798a3de4700550ed495f3ace79c/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bnetstandard/AssumeRoleWithWebIdentityCredentials.cs#L129-L132

There are no `AWS_WEB_IDENTITY_TOKEN_FILE` or `AWS_ROLE_ARN` or `AWS_ROLE_SESSION_NAME` in my environment variables

I am not sure if the cause is due to this commit (https://github.com/aws/aws-sdk-net/commit/bb5f9d3f2304a625718b3bd2a97912a9f08df518)
But I saw `AssumeRoleWithWebIdentityCredentials.FromEnvironmentVariables` is added before `GetAWSCredentials`
https://github.com/aws/aws-sdk-net/blob/bb5f9d3f2304a625718b3bd2a97912a9f08df518/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L60-L64

## Steps to Reproduce (for bugs)
1. Use AWS CLI and `aws configure` to configure the credential
2. Create a .NET Core project with the latest AWSSDK packages
3. new a `IConfigurationBuilder`
4. Add AWS related stuffs to the `IConfigurationBuilder`
5. `builder.Build()`
6. Run the project locally
7. Exception on startup

## Context
Local debugging on a Windows machine

This issue seems not happening when we deploy the code to AWS and not all PC.
Teammates who run the same set of environment variables +  projects cannot reproduce this.

AWS CLI: aws-cli/2.0.0 Python/3.7.5 Windows/10 botocore/2.0.0dev4

## Your Environment

* AWSSDK.Core version used: 3.03.105.2
* Service assembly and version used: 
   - Amazon.Extensions.Configuration.SystemsManager 1.2.0
   - AWSSDK.Extensions.NETCore.Setup 3.3.101
   - AWSSDK.SQS 3.3.102.82
   - AWSSDK.S3 3.3.110.41
* Operating System and version: Windows 10 
* Visual Studio version: 16.5.1
* Targeted .NET platform: .NET Core 3.1 or 2.1

## .NET Core Info

* .NET Core version used for development: 3.1/2.1
* .NET Core version installed in the environment where application runs: 3.1.200
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.107 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.200 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Contents of project.json/project.csproj: 
Our .NET Core 2.1 projects (simplified)
``` XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
....
  <ItemGroup>
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="1.2.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Amazon.Lambda.CloudWatchLogsEvents" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.S3Events" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.1.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.102.82" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.110.41" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
....
</Project>
```
Our .NET Core 3.1 projects (simplified)
``` XML
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>1.1.6</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>
  <ItemGroup>
....
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="1.2.0" />
    <PackageReference Include="AWS.Logger.SeriLog" Version="1.5.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="1.0.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.102.80" />
  </ItemGroup>
....
</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @jasonycw,

Good morning.

I was going through issue backlog and came across this issue.

Unfortunately, I'm unable to reproduce the issue at my end. Could you please share your minimal solution for troubleshooting? Also, could you please check if you have `AWS_SHARED_CREDENTIALS_FILE` environment variable set that might be causing this issue? As you pointed out, exception is coming from https://github.com/aws/aws-sdk-net/blob/9e4669c29cd09798a3de4700550ed495f3ace79c/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bnetstandard/AssumeRoleWithWebIdentityCredentials.cs#L95. Either the code is unable to find the credentials file or somehow the path to credentials file is not absolute path.

In case this is no longer an issue, kindly confirm if this could be closed.

Thanks,
Ashish

**Comment by jasonycw** [comment]
Hi @ashishdhingra,

I don't have `AWS_SHARED_CREDENTIALS_FILE` in my environment variable.

There are only 3 environment variables related to AWS
- aws_access_key_id
- aws_secret_access_key
- AWS_ENABLE_ENDPOINT_DISCOVERY

**Comment by ashishdhingra** [comment]
Hi @jasonycw,

Good afternoon. 

After this issue was prioritized, I was having a look at the reported problem.

Is it possible for you to share the sample code solution in order to troubleshoot the issue? Also check if you have break on all exceptions turned on in Visual Studio (`Debug` -> `Windows` -> `Exceptions Settings` -> `Common Language Runtime Exceptions` -> <All exceptions checked>).

My assumption is that `() => AssumeRoleWithWebIdentityCredentials.FromEnvironmentVariables()` in [FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/ff39138aca46449ba90959c9eaabc9c3848aaf05/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L54) always fails (in a good scenario, it is looking for environment variables `AWS_WEB_IDENTITY_TOKEN_FILE`, `AWS_ROLE_ARN`, `AWS_ROLE_SESSION_NAME`). The logic in [FallbackCredentialsFactory.GetCredentials()](https://github.com/aws/aws-sdk-net/blob/ff39138aca46449ba90959c9eaabc9c3848aaf05/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L111) is wrapped in `try{} catch{}` block, allowing all credential generators in the list to run in sequence even if any of the prior generators fail. 

You also reported that the solution works fine on your colleague's machine. Hence, the assumption about the Visual Studio setting to break on all exceptions might hold true.

Thanks,
Ashish

**Comment by jasonycw** [comment]
Hi @ashishdhingra,

I don't have a simple code sample at the moment to reproduce the issue. But it seems that the key package that may trigger this issue maybe `Amazon.Extensions.Configuration.SystemsManager`. 

Both my colleague and I do have break on all `Common Language Runtime Exceptions` turned on in Visual Studio.

If the fail is expected in a good scenario, would it be better to just log it and not throw a new exception and then continue on?

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra,
> 
> I don't have a simple code sample at the moment to reproduce the issue. But it seems that the key package that may trigger this issue maybe `Amazon.Extensions.Configuration.SystemsManager`.
> 
> Both my colleague and I do have break on all `Common Language Runtime Exceptions` turned on in Visual Studio.
> 
> If the fail is expected in a good scenario, would it be better to just log it and not throw a new exception and then continue on?

Hi @jasonycw,

Thanks for your reply.

Per the code in [FallbackCredentialsFactory.Reset()](https://github.com/aws/aws-sdk-net/blob/7383c1cb9a929408d4340756b5d15b8022ecff56/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L54), the credential generators are configured in the specific order, starting from `AssumeRoleWithWebIdentityCredentials.FromEnvironmentVariables()`. When the instance of `IAmazonService` is created (e.g. `IAmazonS3`) without supplying the credentials, the methods [FallbackCredentialsFactory.GetCredentials()](https://github.com/aws/aws-sdk-net/blob/7383c1cb9a929408d4340756b5d15b8022ecff56/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L106) is invoked to query the credential generators one-by-one in the configured order. The call to each generator is wrapped in the `try{}catch{}` block. The first generator to return the credentials successfully stops the chain. The failed generators call errors are stored in a collection and is only thrown in case credentials are not retrieved from any of the generators.

For successful credential retrieval, it doesn't make sense to log the errors since user might not have configured the credentials at the generator specific location.

When Visual Studio exception settings to break on all exceptions are turned on, the handled exceptions also cause Visual Studio debugger to break and pause program execution. The break you are getting in this scenario is the handled exception (check [code](https://github.com/aws/aws-sdk-net/blob/7383c1cb9a929408d4340756b5d15b8022ecff56/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L134)) and is due to the Visual Studio specific setting.

Hope this provides input to your scenario. Kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by jasonycw** [comment]
So is this an expected behavior to sometime get that error during startup?
No way to bypassing the exception?

As a workaround, I can ignore this exception if I want though
![image](https://user-images.githubusercontent.com/4518597/111284590-36989200-867b-11eb-91b3-37c690037ab4.png)

**Comment by ashishdhingra** [comment]
> So is this an expected behavior to sometime get that error during startup?
> 
> No way to bypassing the exception?
> 
> 
> 
> As a workaround, I can ignore this exception if I want though
> 
> ![image](https://user-images.githubusercontent.com/4518597/111284590-36989200-867b-11eb-91b3-37c690037ab4.png)
> 
> 

Hi @jasonycw,

The exception is handled in the SDK code and the behaviour you are getting is due to the Visual Studio exception settings which breaks even on handled exceptions. 

Please refer URL https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019, it provides more details on this behaviour due to Visual Studio specific setting.

Thanks,
Ashish
