### ISSUE TITLE
AmazonS3Client uses a high amount of CPU

### ISSUE THREAD

**Issue by miryamGSM** [aws/aws-sdk-net#1566]
We have detected that the AmazonS3Client is using a high amount of CPU during tests that we are doing in our product.

The test executes 100 concurrent threads and each thread performs 100 operations. In total, the test performs 10000 operations. Each operation basically does the following against the S3:
- Async uploads 8 small files. Each file has a size smaller than 200 bytes. For each file, we create a task to upload the file and wait for all tasks.
- Async gets the metadata of those files. For each file, we create a task to get the metadata of the file and wait for all tasks.
- Async downloads those files. For each file, we create a task to download the file and wait for all tasks.

During the tests, the CPU usage is about 80% on an m5d.2xlarge instance (Windows OS). That seems too high for us. Removing the S3 calls the CPU usage is less than 10%.
We have tested the following options without any change on the test time, the CPU usage and the memory usage:
- Setting DisableLogging=true, LogMetrics=false & LogResponse=false.
- Setting ThrottleRetries=false.
- Setting ServicePointManager.DefaultConnectionLimit to 50, 100 & 500.
- Setting UseHttp=true
## Expected Behavior
We expected that the S3 client requires less CPU usage for doing it.
## Context
This is a small load test for our product. The standard load is much higher. The problem that it's not going to support the expected load because the S3 is going to reach the CPU limit earlier.
## Your Environment
* AWSSDK.Core version used: 3.3.104.27
* Service assembly and version used: AWSSDK.S3 3.3.110.25
* Targeted .NET platform: .Net core 3.1
## .NET Core Info
* .NET Core version used for development: .Net core 3.1
* .NET Core version installed in the environment where the application runs: None. Used dotnet publish result.

**Comment by NGL321** [comment]
Hey @miryamGSM,

I am switching this to a feature-request since the behavior is not incorrect for the SDK. @boblodgett may have an update in the near future.

😸 😷

**Comment by boblodgett** [comment]
As of AWSSDK.Core 3.5.1.28 and AWSSDK.S3 3.5.3.6:

TransferUtilityUploadRequest, PutObjectRequest, and UploadPartRequest have two additional properties:
   1. DisableMD5Stream
   2. DisablePayloadSigning

In addition, AWSConfigsS3.DisableMD5Stream is a global property to disable MD5Stream so that it does not need to be set on each request.

These properties each disable a data integrity check which consumes some percentage of the CPU during upload. Before use, view the comments on each property to get a better understanding of the effect of disabling one of these checks.

As mentioned in the property comments, disabling both checks results in HTTPS being the only remaining source of data integrity verification.

https://github.com/aws/aws-sdk-net/commit/1d005dbefb3bc1f8d74966d1da1203b20f342530
