### ISSUE TITLE
Documentation outdated on DynamoDBv2 document model

### ISSUE THREAD

**Issue by winzig** [aws/aws-sdk-net#1578]
Looking at the ["latest" documentation on DynamoDB document model](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryMidLevelDotNet.html), I am seeing references to Table.Query which takes something called a `RangeFilter`. 

Took me a while to realize `RangeFilter` is something in the v1 SDK for DDB. DynamoDBv2 has a different API for querying, but I'm not finding any documentation on it. Does the documentation need to be updated?

**Comment by ashishdhingra** [comment]
Hi @winzig,

Please refer to example at [Querying Tables and Indexes: .NET](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetQuerying.html). Queries are executed using the `QueryRequest` object and executing the same against the `AmazonDynamoDBClient` object. Please let me know if it helps.

Thanks,
Ashish

**Comment by Doug-AWS** [comment]
We're trying to refactor our code examples to include unit tests so that we know when an example no longer works with the latest version of the SDK (currently 3.5). If you find a bad example, such as this one, please click the Feedback link on the bottom of the page and tell us. I've added your feedback to the page to which you refer, so we *should* get it fixed *shortly*.
