### ISSUE TITLE
IsLSet, IsMSet, IsBOOLSet values not respected when deserializing AttributeValue

### ISSUE THREAD

**Issue by emergentSushi** [aws/aws-sdk-net#1640]
## Description
IsLSet, IsMSet and IsBOOLSet values on DynamoDBv2.Model.AttributeValue don't work as expected when creating a Document with Dictionary<string, AttributeValue> via Document.FromAttributeMap(). IsBOOLSet being set when creating will cause the BOOL value to always be false, IsLSet and IsMSet when used with their corresponding L/M value seem to cause the Document property to be dropped and return a DynamoDBNull on that document property.

## Reproduction Steps
See test cases.
https://gist.github.com/emergentSushi/434cac9f626e522198f44a4ac1e7aff5

### Logs
N/A, see unit tests that replicate the issue with XUnit tests.

### Environment
* SDK Version: AWSSDKDynamoDBv2 3.3.105.40
* Package Version: 3.3.105.40
* OS Info: Dev machine is Windows, but the prod environment is in a dotnet core 3.1 lambda
* Build Environment VS2019
* Targeted .NET Platform:  netcoreapp3.1

## Resolution
We ran across this issue because we have a replication service stores data from a Dynamo stream in S3 and then a lambda that runs on demand to copy that data into lower (staging, etc) environments. We found that certain properties were getting silently dropped in the process. Our serialization format for each Dynamo record is the Dictionary<string, AttributeValue> that is provided by the stream.

I believe that the issue is connected to https://github.com/aws/aws-sdk-net/issues/1116 and has something to do with the nullable fields that back the Is*Set properties on AttributeValue, but I'm not sure.

We have a workaround that uses a custom json serializer that omits the IsLSet, IsMSet and IsBOOLSet from the JSON as it's parsed and avoids the issue.

Or if serializing AttributeValue from the dynamo stream isn't a supported way of storing the stream output, then we can always change our implementation.

---

This is a :bug: bug-report

**Comment by pavlalexandr** [comment]
I can approve of this behavior. 
We created a lambda for DynamoDb stream and fetch new and old images from it.  But after Document.FromAttributeMap() it seems that all M type fields persisted as DynamoDBNull values.

**Comment by pavlalexandr** [comment]
The problem related with Document.TryToDynamoDBNull method, because it executed before M and L conventions. 
It uses IsSetNULL() which returns true even the _null field = false, but should use the NULL property for this check. 

`
private static bool TryToDynamoDBNull(AttributeValue attributeValue, out DynamoDBNull ddbNull)
        {
            ddbNull = null;
            if (attributeValue.NULL)
            {
                ddbNull = new DynamoDBNull();
            }
            return (ddbNull != null);
        }
`

**Comment by ashishdhingra** [comment]
Hi @emergentSushi, 

Thanks for posting the question.

I had a look at your code and looks like in both Xunit tests, you are trying to manually set [IsBOOLSet](https://github.com/aws/aws-sdk-net/blob/4377951e3fcab348561af631ef2651433ca1c189/sdk/src/Services/DynamoDBv2/Generated/Model/AttributeValue.cs#L129), [IsLSet](https://github.com/aws/aws-sdk-net/blob/4377951e3fcab348561af631ef2651433ca1c189/sdk/src/Services/DynamoDBv2/Generated/Model/AttributeValue.cs#L195) and [IsMSet](https://github.com/aws/aws-sdk-net/blob/4377951e3fcab348561af631ef2651433ca1c189/sdk/src/Services/DynamoDBv2/Generated/Model/AttributeValue.cs#L239) properties. Setting these properties appears to call [Amazon.Util.Internal.InternalSDKUtils.SetIsSet()](https://github.com/aws/aws-sdk-net/blob/4377951e3fcab348561af631ef2651433ca1c189/sdk/src/Core/Amazon.Util/Internal/InternalSDKUtils.cs#L263) method which sets the value of OUT Nullable type to default value (which is null) if isSet is true and null otherwise. I'm not sure if this behavior is by design due to some specific reason. Looks like (even though I'm not sure) these are control fields and should not be set manually.

Workaround is, as you also mentioned, is not to set these fields manually. The API documentation for [AttributeValue](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TAttributeValue.html) also mentions, for example for IsSetBOOL,

```
This property is set to true if the property Amazon.DynamoDBv2.Model.AttributeValue.BOOL is set; false otherwise. 
This property can be used to determine if the related property was returned by a service response or if the related property should be sent to the service during a service call.
```

I understand your use case, however, I'm not sure if manually setting these properties to true would be a supported scenario (setting property to false anyway sets them to NULL, which above note from documentation anyway indicates the corresponding property should not be sent to server).

Thanks,
Ashish

**Comment by emergentSushi** [comment]
Hi @ashishdhingra,

Thank-you for your response, please note that the tests aren't representative of our actual code, they're there to demonstrate the root cause of the problem (which is that JSON de/serializing collections of AttributeValue's taken from a stream causes some entries to drop).

However, I understand what you mean, this probably isn't a use case that was originally anticipated. As I stated in the initial comment we've resolved this internally with a custom deserializer for the affected types.

Cheers,
Mat

**Comment by ashishdhingra** [comment]
@emergentSushi Thanks for your response. Please confirm this issue could be closed.

Thanks,
Ashish

**Comment by emergentSushi** [comment]
I would really like it if you fix it (it'd be nice to not need custom deserializers), but I understand that changing this behaviour could introduce huge regressions and that the AWS SDK team has limited resources.

Please close the issue.

Cheers
