### ISSUE TITLE
xamarin lambda function issue

### ISSUE THREAD

**Issue by Shraddha996** [aws/aws-sdk-net#1641]
Am using AWS lambda function in Xamarin to get the places data but unable to get data in res
Please help me as am new to xamarin and AWS services 

```c#
AmazonLambdaClient client = new AmazonLambdaClient("xxx", "yyy", RegionEndpoint.USEast1);
InvokeRequest ir = new InvokeRequest
{
    FunctionName = "fn_SS_GetPlaces",
    InvocationType = InvocationType.RequestResponse
};
InvokeResponse response = client.Invoke(ir);///////[invoke getting error as AmazonLambdaClient.Invoke(InvokeRequest) is inaccessible due to its protection level]

System.Threading.Tasks.Task<Amazon.Lambda.Model.InvokeResponse> res = client.InvokeAsync(ir);
```

**Comment by ashishdhingra** [comment]
Hi Shraddha,

Thanks for the posting the guidance question. Since you are using Xamarin, you would be targeting .NET Core framework. As per API documentation for [AmazonLambdaClient.Invoke](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Lambda/MLambdaInvokeInvokeRequest.html), there is a Note that "_For .NET Core, PCL and Unity this operation is only available in asynchronous form._". So the only option is to use _Invoke_**Async**.

Please let me know if this answers your question.

Thanks,
Ashish
