### ISSUE TITLE
How to call API gateway with x-api-key

### ISSUE THREAD

**Issue by deadislove** [aws/aws-sdk-net#1644]
## The Question
I want to call the AWS API gateway URL with x-api-key by ASP.NET MVC. I try to use the WebClient of ASP.NET to call the API gateway URL, but it returns the 403 error code. I have checked this URL with x-api-key is OK by Postman.

```
WebClient webClient = new WebClient();

webClient.Headers.Add(HttpRequestHeader.ContentType, "application/json");
webClient.Headers.Add("x-api-key", "8xSeyaErG44xxxxxxzqGt33xxxxexxxxxxxxxx");

AWSSingleImage singleImageInfo = new AWSSingleImage
{
 	category = sCategory,
	key = Name
 };
var Data = JsonConvert.SerializeObject(singleImageInfo);
var vResponse = webClient.UploadString("AWS API Gateway URL", "post", Data.ToString());
Response_msg = JsonConvert.DeserializeObject<string>(vResponse);
```

### Environment

* SDK Version: 
* Package Version: 
* OS Info: Windows
* Build Environment: Visual Studio 2017
* Targeted .NET Platform:  ASP.NET MVC 4.7 framework.

---

This is a :question: general question

**Comment by deadislove** [comment]
I try to deploy the API gateway URL for four times. I find out this problem can be solved. 
I don't understand what happened in the program?

**Comment by ashishdhingra** [comment]
Hi @deadislove, 

Please share your exact scenario and detailed sample code in order to troubleshoot the issue. Also see if the article [How do I troubleshoot HTTP 403 Forbidden errors when using a Lambda authorizer with an API Gateway REST API?](https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-403-error-lambda-authorizer/) is helpful.

If this is no longer an issue, please confirm if this could be closed.

Thanks,
Ashish
