### ISSUE TITLE
Inconsistent AmazonS3URI parsing?

### ISSUE THREAD

**Issue by dhruv-balakrishnan** [aws/aws-sdk-net#1661]
## Description
AmazonS3Uri is inconsistent in its parsing. On certain instances, it fails to parse a given HTTP URL correctly. This seems to happen when the file path includes a '#'. Is this by design? 

## Reproduction Steps
1. Given some example HTTP paths in these formats:
- https://bucket.name.s3.amazonaws.com/user_input/20200101/test.py
- https://bucket.name.s3.amazon.aws.com/output/20200101/7765aa8b-d19a-4f6f-8e89-e56b14fd638a#baac7b41-c11c-4056-b937-3e2c6e12bf88.py

2. Attempt to create an AmazonS3Uri object:
`s3Uri = new AmazonS3Uri(input);`

3. Inconsistent (by design?) outputs are created.

✅ In the first instance, a correct S3Uri object is created:
```
Bucket: bucket.name
Key: user_input/20200101/test.py
```

:heavy_exclamation_mark: In the second instance, an incorrect S3Uri object is created:
```
Bucket: bucket.name
Key: output/20200101/7765aa8b-d19a-4f6f-8e89-e56b14fd638a
```

Expected:
```
Bucket: bucket.name
Key: output/20200101/7765aa8b-d19a-4f6f-8e89-e56b14fd638a#baac7b41-c11c-4056-b937-3e2c6e12bf88.py
```

### Logs
No logs at the moment, as there's no failures and I'm encountering these in integration tests. Will update if I'm able to capture them.

### Environment

- SDK Version: 3.5.0 beta
- Package Version: 3.3.107.3
- OS Info: OSX Catalina
- Build Environment: Jetbrains Rider
- Targeted .NET Platform: .netstandard 2.0

## Resolution

None from me.

---

This is a :bug: bug-report

**Comment by Trisped** [comment]
I am having a similar problem (# in key causes incomplete key to be returned).
I am primarily using s3:// protocol to instead of http:// or https:// protocols, which is not yet supported by AmazonS3Uri.

Looking in [the code](https://github.com/aws/aws-sdk-net/blob/e18165285c61fbc381ae0108343ef503bdbe6ef8/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs), they are trying to use the built in Uri class which treats ? and # differently

If you look in the following image showing the contents of a Uri instance, you can see that everything starting the first ? till the first # is url encoded and placed in Query.  Everything from the first # through the end is in Fragment.

![image showing values of the Uri instance](https://user-images.githubusercontent.com/20877262/87834670-e1805400-c83f-11ea-845f-a7ed98a416ea.png)

Of course using UrlDecode on the Query and Fragment properties will not work because it does not escape the % (see the end of OriginalString where it says "%25 ~.mxf" and the end of Fragment is "%25%20~.mxf"

I was hoping the code for the C# URI would be simple (so I could build my own AmazonS3Uri that worked) but it is over 5500 lines:
[Reference 1](https://referencesource.microsoft.com/#system/net/System/URI.cs)
[Reference 2](https://github.com/microsoft/referencesource/blob/master/System/net/System/URI.cs)


Environment
- Package Version: 3.3.111.26
- Targeted .NET Platform: .Net Core 2.1

Let me know if the s3:// protocol support needs to be a new issue.

**Comment by philasmar** [comment]
Hello,

The AmazonS3Uri expects the passed URL to be encoded to take into account characters such as "#" in the S3 file name, which includes both initializing the AmazonS3Uri with a string URI or a URI object.
This is due to the fact that AmazonS3Uri is using the URI class which handles everything after the "#" as a fragment portion of the URI.

Feel free to open a new issue/reopen this one if passing an encoded URI does not work for you.
