### ISSUE TITLE
InvalidOperationException when querying index that does not exist

### ISSUE THREAD

**Issue by malaqueueit** [aws/aws-sdk-net#168]
Hi

When I query a table using the dynamo db context with an index that does not exist on the table I get a System.InvalidOperationException. I was expecting some kind of Amazon wrapped exception. Is this by design or is it an error? Located in version 2.3.8.1.

**Comment by PavelSafronov** [comment]
This is by design. The DynamoDBContext has the table description and can detect if a call is against a non-existent index (in addition to other validation checks, like making sure that the keys are of the correct type or that a query is being issued against a hash-range table, etc.), so it will throw an exception without making a service call.

**Comment by malaqueueit** [comment]
I understand the exception, but an InvalidOperationException is not easy to catch (could be anything). I'm just suggesting something like a NonExistingIndexException that inherits from InvalidOperationException.

I see now that I can use the API to determine if the index exists so the exception will not be thrown. I still think there is a point in using a more specific exception, but I see that is just an opinion. Fell free to close the ticket.
