### ISSUE TITLE
Error when posting data to Gateway Websocket API using AmazonApiGatewayManagementApiClient .

### ISSUE THREAD

**Issue by mingshi98** [aws/aws-sdk-net#1771]
Issue Summary
--------------------------
Our application(running on .NET Core) uses Gateway Websocket API.  When using AmazonApiGatewayManagementApiClient to post data back to the connected client, it runs into web proxy issue.  Here is our code
```C#
            var credential = new NetworkCredential("xxx", "xxxx");
            var proxyConfig = new AmazonApiGatewayManagementApiConfig {
                ServiceURL = url, 
                ProxyHost = "xxxxx",
                ProxyPort = 3128,
                ProxyCredentials = credential,
                AllowAutoRedirect = true,
                UseHttp = true,
                RegionEndpoint = RegionEndpoint.USEast1
            };

            var apiClient = new AmazonApiGatewayManagementApiClient(proxyConfig);
            apiClient.PostToConnectionAsync(postConnectionRequest).Result;
```

then we got the following exception.  Can you provide some guidance on how proxy should be set?  Thanks
"GSSAPI operation failed with error - An invalid name was supplied (Configuration file does not specify default realm)

Our environment
-----------------------------------------
1) version of AWS SDK
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="2.0.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.2.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.2.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.5.1.50" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.5.4.9" />
    <PackageReference Include="AWSSDK.S3" Version="3.5.6.6" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.5.7.1" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.4.0" />
    <PackageReference Include="AWSSDK.ApiGatewayManagementApi" Version="3.5.0.50" />

2) ARN of the lambda that does the posting
arn:aws:lambda:us-east-1:970151717376:function:ShortSellDeltaPublishTestDev

3) I am trying to do basic authentication.  I have explored all possible options when setting up NetworkCredential (with/without specifying domain name).  

More observation
-----------------------------
While debugging this, I did a Python lambda that makes the same POST to the api gateway endpoint, using proxy authentication. It worked successfully.  Worse, because our proxy caches authentication, if we run the DotNet lambda within a period of the python one running, it works correctly- presumably because the DotNet SDK does everything correctly except answering the authentication challenge.

The code we used comes directly from the AWS documentation on https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html  (the subsection entitle "Using proxy credentials")

The application is currently running in Lambda. The reason we are using the proxy in the first place is that the websocket API does not respond on the private vpc endpoint that is in the VPC to support existing rest apis. As I said, we verified that the api call works from a separate lambda in the same vpc- so long as it is using the python SDK instead of the dotnet one. As for your links- [1] is the config for nuget, which doesn't apply to the aws sdk. [2] has no solution except "I switched to a windows container".

**Comment by ashishdhingra** [comment]
Hi @mingshi98,

Good morning.

Not sure if your I understand your issue correctly. Does the issue happens when using `AmazonApiGatewayManagementApiClient` inside your Lambda function. If yes, I'm not sure how `NetworkCredential` would work here since Lambda runs in a minimal Linux instance behind the scenes. The page [Identity and access management for Lambda](https://docs.aws.amazon.com/lambda/latest/dg/security-iam.html) provides some details on how IAM works from Lambda. You may try granting Lambda function appropriate role with necessary permissions.

Also refer the following for example(s):
- [Getting started with WebSockets on API Gateway with .NET and the Serverless Framework](https://medium.com/@gavinlewis/getting-started-with-websockets-on-api-gateway-with-net-and-the-serverless-framework-9065f37d06e0)
- [Stackoverflow issue](https://stackoverflow.com/questions/56298464/api-gateway-websocket-connection-endpoint-not-found)

In case we are missing anything, request you to provide any other issue details in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html


Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> Hi @mingshi98,
> 
> Good morning.
> 
> Not sure if your I understand your issue correctly. Does the issue happens when using `AmazonApiGatewayManagementApiClient` inside your Lambda function. If yes, I'm not sure how `NetworkCredential` would work here since Lambda runs in a minimal Linux instance behind the scenes. The page [Identity and access management for Lambda](https://docs.aws.amazon.com/lambda/latest/dg/security-iam.html) provides some details on how IAM works from Lambda. You may try granting Lambda function appropriate role with necessary permissions.
> 
> Also refer the following for example(s):
> 
> * [Getting started with WebSockets on API Gateway with .NET and the Serverless Framework](https://medium.com/@gavinlewis/getting-started-with-websockets-on-api-gateway-with-net-and-the-serverless-framework-9065f37d06e0)
> * [Stackoverflow issue](https://stackoverflow.com/questions/56298464/api-gateway-websocket-connection-endpoint-not-found)
> 
> In case we are missing anything, request you to provide any other issue details in the following format:
> 
> ## Expected Behavior
> ## Current Behavior
> ## Possible Solution
> ## Steps to Reproduce (for bugs)
> ## Context
> ## Your Environment
> * AWSSDK.Core version used:
> * Service assembly and version used:
> * Operating System and version:
> * Visual Studio version:
> * Targeted .NET platform:
> 
> ## .NET Core Info
> * .NET Core version used for development:
> * .NET Core version installed in the environment where application runs:
> * Output of `dotnet --info`:
> * Contents of project.json/project.csproj:
> 
> Thanks,
> Ashish

Hi @mingshi98,

In addition to above, please check the following issues:
- https://github.com/aws/aws-sdk-net/issues/1637
- https://github.com/aws/aws-sdk-net/issues/1264

Both talk about IAM permissions, VPC and case sensitivity of ServiceURL. Let me know if this provides guidance.

Thanks,
Ashish

**Comment by pbecotte** [comment]
> Not sure if your I understand your issue correctly. Does the issue happens when using AmazonApiGatewayManagementApiClient inside your Lambda function. If yes, I'm not sure how NetworkCredential would work here since Lambda runs in a minimal Linux instance behind the scenes. The page Identity and access management for Lambda provides some details on how IAM works from Lambda. You may try granting Lambda function appropriate role with necessary permissions.

To send traffic to the api, we have to route it through our internet proxy. Our proxy is using basic-auth authentication (username password).  From your docs-

> If your software communicates with AWS through a proxy, you can specify credentials for the proxy by using the ProxyCredentials property of the Config class of a service ...
> 
> AmazonS3Config config = new AmazonS3Config();
> config.ProxyCredentials = new NetworkCredential("my-username", "my-password");

So the NetworkCredential is basically username/password for our proxy. When configuring the proxy as shown, we get a 407 error from the proxy (not the aws api). 

In python using

`   c = boto3.client("apigatewaymanagementapi", endpoint_url=api, verify=False, config=Config(proxies={"https": "http:/USERNAME:PASSWORD@proxy.ourorg.com:3128"}))`

allows the lambda to communicate with the API. The issue just seems to be with dotnet- instead of answering the auth challenge with the username password from the NetworkCredential, it seems to be trying to use kerberos or something and failing (since as you said, lambdas don't have a full linux instance).
