### ISSUE TITLE
Self signed certificate issue (The remote certificate is invalid because of errors in the certificate chain)

### ISSUE THREAD

**Issue by giacomorebonato** [aws/aws-sdk-net#1785]
## The Question

Hi, I am reporting an issue that I am struggling to solve, I hope that someone can point me out the right direction.

### Environment

* SDK Version: 3.5.2
* Package Version: 3.5.2.5
* OS Info: `public.ecr.aws/lambda/dotnet:5.0` on Docker
* Build Environment: dotnet cli
* Targeted .NET Platform:  5.0

---

I have a dotnet Lambda handler that writes to DynamoDB and reads/writes files from/to S3.
Everything works out perfectly at first, but then there is another thing that I need: [Matlab Runtime](https://it.mathworks.com/help/compiler/install-the-matlab-runtime.html).
After I install the Matlab runtime it asks me to append values to `LD_LIBRARY_PATH`.
This action breaks SSL connection to both DynamoDB and S3:

```
INNER EXCEPTION: The remote certificate is invalid because of errors in the certificate chain: PartialChain
```

If I change the communication over http everything works again, but this is not acceptable.
Do you have any suggestions?

**Comment by ashishdhingra** [comment]
Hi @giacomorebonato,

Thanks for reporting the issue. This appears to be an issue with 3rd party runtime which after installing is having certificate issues. Have you tried contacting MatLab Runtime support? There was similar issue reported in Microsoft's .NET repository https://github.com/dotnet/runtime/issues/27703#issuecomment-485334384, not sure if it might help.

Also, could you provide the exact repro steps in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by giacomorebonato** [comment]
Hi, it wasn't an issue with this SDK of course.
Here's the solution that I have found: https://stackoverflow.com/questions/65961176/ssl-broken-with-ld-library-path-and-matlab
