### ISSUE TITLE
How do I pass a custom VPC endpoint URL to Amazon.Runtime.AssumeRoleAWSCredentials

### ISSUE THREAD

**Issue by aaronlahey** [aws/aws-sdk-net#1792]
## The Question

We are needing to receive messages from an SQS queue over an SQS VPC endpoint but first we need to assume a role over another STS VPC endpoint. Setting up the SQS client with the `ServiceURL` seems straightforward, but I can't figure out a way to instantiate the `Amazon.Runtime.AssumeRoleAWSCredentials` such that it makes requests to STS over a VPC endpoint. I noticed there is another `Amazon.SecurityToken.STSAssumeRoleAWSCredentials` class which allows me to pass my own STS client that can be configured any way I want, but it is marked as `Obsolete`. Is this missing behavior in `STSAssumeRoleAWSCredentials`'s suggested replacement, or is there some other way of configuring the `AssumeRoleAWSCredentials` with a VPC endpoint that I haven't found?

Thanks!

### Environment

AWSSDK.SQS 3.5.1.14
AWSSDK.SecurityToken 3.5..1.45

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @aaronlahey,

Good morning.

Thanks for posting the guidance issue. The example usage of `Amazon.Runtime.AssumeRoleAWSCredentials` could be find in the issue https://github.com/aws/aws-sdk-net/issues/1063. I'm not sure if you would be able to pass custom VPC endpoint URL. I'm not sure if the use case you are mentioning is a valid scenario since the `AmazonSecurityTokenServiceClient` is used to fetch credentials from STS service (see example https://github.com/aws/aws-sdk-net/blob/6d0f7f91920db3cc9af65ebc6ee2cfde04c591b0/docgenerator/AWSSDKDocSamples/SecurityToken/SecurityToken.GeneratedSamples.cs#L14). Could you post a working example where you are able to use custom VPC endpoint with  `Amazon.SecurityToken.STSAssumeRoleAWSCredentials` class?

Thanks,
Ashish

**Comment by aaronlahey** [comment]
Hi @ashishdhingra! I'm not able to verify this code is working. I'm actually asking this question on behalf of someone we're working with. But, the `STSAssumeRoleAWSCredentials` takes a `AmazonSecurityTokenServiceClient` in the constructor which (I assume) can be configured any way one would like:

```
var userCredentials = new BasicAWSCredentials("awsAccessKeyId", "awsSecretAccessKey");
var stsClientConfiguration = new AmazonSecurityTokenServiceConfig
{
    ServiceURL = "stsVpcEndpoint"
};
var stsClient = new AmazonSecurityTokenServiceClient(userCredentials, stsClientConfiguration);
var assumeRoleRequest = new AssumeRoleRequest
{
  RoleArn = "roleArn",
  RoleSessionName = "roleSessionName"
};
var assumeRoleCredentials = new STSAssumeRoleAWSCredentials(stsClient, assumeRoleRequest);
```

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra! I'm not able to verify this code is working. I'm actually asking this question on behalf of someone we're working with. But, the `STSAssumeRoleAWSCredentials` takes a `AmazonSecurityTokenServiceClient` in the constructor which (I assume) can be configured any way one would like:
> 
> ```
> var userCredentials = new BasicAWSCredentials("awsAccessKeyId", "awsSecretAccessKey");
> var stsClientConfiguration = new AmazonSecurityTokenServiceConfig
> {
>     ServiceURL = "stsVpcEndpoint"
> };
> var stsClient = new AmazonSecurityTokenServiceClient(userCredentials, stsClientConfiguration);
> var assumeRoleRequest = new AssumeRoleRequest
> {
>   RoleArn = "roleArn",
>   RoleSessionName = "roleSessionName"
> };
> var assumeRoleCredentials = new STSAssumeRoleAWSCredentials(stsClient, assumeRoleRequest);
> ```

Hi @aaronlahey,

I'm not sure if using the STS VPC Endpoint in `AmazonSecurityTokenServiceConfig` is correct. Please refer section **Create a VPC for AWS STS** in documentation [Using AWS STS interface VPC endpoints](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_sts_vpce.html). It mentions that `After you create the VPC endpoint, you must use the matching regional endpoint to send your AWS STS requests.`. So you should be able to use existing client or credentials classes with the region set in the application profile. The STS VPC endpoint appears to be more like configuration thing at VPC level so that it can interface with AWS STS.

Thanks,
Ashish

**Comment by aaronlahey** [comment]
@ashishdhingra I think I understand what you're saying. From what I've read you don't always need to set "Private DNS names enabled" to `true`. Enabling private DNS names says this:

>Associates a private hosted zone with the VPC that contains a record set that enables you to leverage Amazon’s private network connectivity to the service while making requests to the service’s default public endpoint DNS name.

I think you can explicitly provide the `vpce-xxxxxxxx.whatever.vpce.amazonaws.com` endpoints to most services.

Enabling private DNS names, unfortunately, will not work in our case. We need to explicitly configure this endpoint.

The API docs for `AmazonSecurityTokenServiceConfig` say...

>This is an optional property; change it only if you want to try a different service endpoint.

Is that not the right property to expclitly provide the `vpce-xxxxxx` URL?

**Comment by ashishdhingra** [comment]
@aaronlahey All config classes derive from [Amazon.Runtime.ClientConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html). The `ServiceURL` property points to the service endpoint, in this case STS service endpoint. The documentation [AWS Security Token Service endpoints and quotas](https://docs.aws.amazon.com/general/latest/gr/sts.html) provides list of service endpoints. The VPC endpoint in essence is not a STS service endpoint, hence, not valid for `ServiceURL` property for STS client.
