### ISSUE TITLE
Apparent lack of SDK support for multipart upload to presigned URL

### ISSUE THREAD

**Issue by LBensman** [aws/aws-sdk-net#1832]
### Preface
I'm working on a component that will need to upload long video streams to S3, and thus needs to use multipart upload.  This component, however, does not have knowledge of credentials or buckets or keys as this is the job of a different part of the system.  Instead, that system will generate pre-signed URL and pass that URL to the component that will generate and upload the video.

### SDK issue
I see that SDK has great support for multi-part uploads, especially the parts where I can either provide a single input stream to multiple part requests and it'll read the stream and upload the part and not close or dispose of the source stream so I can pass it further to the next part of request (as example for `InitiateMultipartUpload (InitiateMultipartUploadRequest)`) demonstrates; or even use `TransferUtility` that seems like I can just give stream to upload, and it itself will figure out how to multi-part it and upload it in parts, and I don't even have to manage parts (I'm assuming it figures out and properly performs completion or abort?)

However, both of these methods seems to require creds/bucket input.  I can't seem to find a way to use SDK when all I have is a presigned URL as destination, and am otherwise an outsider to S3 account.

Can SDK be used to multi-part upload based purely on presigned URL as the sole identifier of the operation?

If not, this seems to be lacking in SDK and presigned URLs seem to be treated as second-class citizens.

P.S. I've looked at #717, but that one seems to be about generation of presigned URLs, and in my case someone else will generate the URL (and they shouldn't really care about whether upload will be multipart or not).  And even if they do generate url with multipart attributes in it, still the question stands of how to use SDK to actually do the upload when all I have is the URL.

### Environment

* SDK Version: Just looking at latest docs atm.
* Package Version: n/a
* OS Info: macOS
* Build Environment dotnet on macOS
* Targeted .NET Platform:  .NET Core

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @LBensman,

Good morning.

Thanks for posting guidance question. Uploading file using multipart upload using pre-signed URL should not differ as much as opposed to upload using normal single operation. The only thing is generating pre-signed URLs for each part. Following articles might provide some guidance:

- [Multipart Upload for Large Files using Pre-Signed URLs - AWS
 ](https://dev.to/traindex/multipart-upload-for-large-files-using-pre-signed-urls-aws-4hg4)
- [AWS Forums: S3 Multipart upload using Presigned url](https://forums.aws.amazon.com/thread.jspa?threadID=254534)
- [Multipart uploads with S3 pre-signed URLs](https://www.altostra.com/blog/multipart-uploads-with-s3-presigned-url)
- [Uploading objects using presigned URLs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html)

Please try the approach in above articles in .NET code. Hope this helps.

Thanks,
Ashish

**Comment by LBensman** [comment]
@ashishdhingra, I think you misunderstood the question.  The question is not about how to _manually_ craft raw HTTP requests (I can do that, and with lack of support in SDK, that's what I'm basically working on now), but rather how to use SDK and its convenience for it. 

In other words, had I had bucket and other info, I can just as well manually craft HTTP requests and upload content without SDK. But SDK makes it easier, and thus it would be easier to use SDK to multi-part upload to some bucket/key with creds.  The SDK helps take care of a few things automagically, requiring less code writing.

But the same convenience seems to be lacking if the same multipart upload needs to happen for presigned URL.  In this case, everything has to be done manually, and the convenience of functions such as `InitiateMultipartUpload (InitiateMultipartUploadRequest)`, `UploadPartAsync(...)`, `CompleteUpload(...)`, `AbortUpload(...)` etc is denied for uploads to presigned URLs.

Looking at it another way: ask yourself a question why would somebody want to use SDK's `UploadPart()`, etc., as opposed to manually crafting HTTP request (for any and all functionalities of S3)?  Then apply the same question only to the scenario where one has presigned url instead of creds/bucket/key for identifying destination object.  Just because I have presigned URL instead of creds/bucket/key, doesn't really change the nature of the operation itself all that much.  Hence the same reasons why one would want to use SDK to perform those operations when they do have creds/bucket/key apply just as well to the scenario when one has presigned URL as well?  Makes sense?

Please reopen the question as it hasn't really be answered (I think it needs to evolve into feature request, TBH, unless I'm missing something from SDK that I'm not seeing for this case)

**Comment by ashishdhingra** [comment]
@LBensman Is your scenario that you get a single pre-signed URL from a system that generates it and you would like SDK to take care of using it for the multi-part upload? If yes, I do not think it is feasible. Pre-signed URL generation involves several steps. At high level, one of the steps if to use request parameters (this includes part number and upload ID for multipart upload) and use it to calculate the signature, before generating the pre-signed URL. The client can then use the presigned URL to perform operation specified by HTTP Verb. Also, the uploading of object using presigned URL is a client operation.

Since the pre-signed URL is signed with all the request parameters and the whole intent is that the client could use it without the knowledge of credentials (obviously the creator of the presigned URL should have permissions to perform the operation), it's not possible to use it to decode it and generate individual URLs for multipart upload. 

Just for reference, if you refer the articles, it mentions multi-part upload using presigned URL as the 4-step operation:

1. Initiate a multipart upload
2. Create pre-signed URLs for each part
3. Upload the object’s parts
4. Complete multipart upload

Stages 1,2, and 4 are server-side stages, which require an AWS access key id & secret, where stage number 3 is client-side.

For your scenario, you need some way for the system that generates presigned URL to have an API to provide above operations, including providing pre-signed URL for individual parts depending on the granulity required.

**Comment by LBensman** [comment]
@ashishdhingra I see.  The example for presigned URL upload at https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html is not multipart, and makes it look like a single URL is enough, and then if client decides to upload in parts, then it tacks on part identifiers and all that.  I see where confusion is now.  TBH, this seems a bit of a flaw to include part numbers in presigned URLs as it locks in methodology of upload and somewhat ahead knowledge of how big the file (but not exactly how big) is, which server may not know, or even client may not know until the upload, but that's flaw of API design, not SDK's, and so out of scope for this forum.

I see, and need to get back to the other team to figure out solution on our side.
