### ISSUE TITLE
Arn does not support AWS resources eg. AWS-managed prefix lists

### ISSUE THREAD

**Issue by TibbsTerry** [aws/aws-sdk-net#1836]
## Description
Arn does not support AWS resources eg AWS-managed prefix lists
Any arn strings with AccountId = 'aws' are an issue
eg
arn:aws:ec2:ap-southeast-2:aws:prefix-list/pl-xxxxxxxx

**Comment by ashishdhingra** [comment]
Hi @TibbsTerry,

Good afternoon.

In order to investigate the issue, could you please share the sample code and the version of SDK used, preferably in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by TibbsTerry** [comment]
```
// netcoreapp3.1
// PackageReference Include="AWSSDK.Core" Version="3.7.0.18" 
static void Main(string[] args)
{
    //arn:aws:ec2:ap-southeast-2:aws:prefix-list/pl-xxxxxxxx
    try
    {
        var arn = new Amazon.Arn
        {
            Partition = "aws",
            Service = "ec2",
            Region = Amazon.RegionEndpoint.APSoutheast2.SystemName,
            AccountId = "aws",
            Resource = "prefix-list/pl-xxxxxxxx"
        };
    }
    catch (Exception e)
    {
        // The AccountId length should be 12 and only contain numeric characters with no spaces or periods
        Console.WriteLine(e);
    }

    try
    {
        var arn = Amazon.Arn.Parse("arn:aws:ec2:ap-southeast-2:aws:prefix-list/pl-xxxxxxxx");
    }
    catch (Exception e)
    {
        // The AccountId length should be 12 and only contain numeric characters with no spaces or periods
        Console.WriteLine(e);
    }

    Console.ReadLine();
}
```

**Comment by ashishdhingra** [comment]
TBD: Check how other SDKs are handling this scenario (may be in CDK).

**Comment by ashishdhingra** [comment]
Fixed in the following:
- [AWSSDK.Core 3.7.3.6](https://www.nuget.org/packages/AWSSDK.Core/3.7.3.6)
- [AWSSDK.S3Control 3.7.3.7](https://www.nuget.org/packages/AWSSDK.S3Control/3.7.3.7)
- [AWSSDK.S3 3.7.2.6](https://www.nuget.org/packages/AWSSDK.S3/3.7.2.6)
