### ISSUE TITLE
rds:CreateDBClusterSnapshot Fails to Create Duplicate Cluster Snapshot

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#1875]
## Description

Occassionally, when calling `IAmazonRDS.CreateDBClusterSnapshot`, the client will throw an exception:

> Cannot create the cluster snapshot because one with the identifier &lt;ID&gt; already exists.

When this happens, before the method is called, the snapshot in question **does not exist**. Also, when logging times, an execution time of upwards of 30 seconds is witnessed.

My guess: the RDS API returned an error result, and the AWS SDK "retried the request". However, the snapshot was indeed created by the first request. The retry then fails because the snapshot now exists.

In other AWS APIs, a "client token" is used to ensure duplicate requests like these are avoided.

## Reproduction Steps

It's difficult to make it happen dependably.

Call `IAmazonRDS.CreateDBClusterSnapshot` and have the RDS API fail :smile:

Because hourly snapshots are being created, we have seen this happening daily lately.

### Logs

From our own logs:

```
I:6/30/2021 12:01:09 AM: Creating snapshot for proddb...
D:6/30/2021 12:01:09 AM: DB Cluster ID: proddb
D:6/30/2021 12:01:09 AM: Snapshot ID: proddb-hourly-2021-06-29-17-00-00
D:6/30/2021 12:01:09 AM: Calling rds:CreateDBClusterSnapshot()
D:6/30/2021 12:01:40 AM: Request ID: d68962bb-99b4-43a1-b64a-bd513791c020
E:6/30/2021 12:01:40 AM: Error executing request: Cannot create the cluster snapshot because one with the identifier proddb-hourly-2021-06-29-17-00-00 already exists.
```

Notice the 30 second delay between "Calling rds:CreateDBClusterSnapshot()" and the "Request ID". That's where `CreateDBClusterSnapshot` is sitting and waiting.

### Environment

* SDK Version: Amazon.RDS 3.7.0.13
* Package Version: Amazon.RDS 3.7.0.13
* OS Info: Windows 10, Windows Server 2019
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  .NET Framework 4.7.2

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

One of the following should be implemented:

1. A "client token" used to uniquely identify "the same request", or
2. Avoid retries on this API call (or allow the caller to indicate that retries should not be used).

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @mwhouser,

Good morning.

Could you please share sample code that creates snapshot to see what might be going wrong? I'm not sure how we can consistently reproduce it. As with other AWS SDK for .NET APIs, the call `IAmazonRDS.CreateDBClusterSnapshot()` would either pass or fail due to errors mentioned at [CreateDBClusterSnapshot](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBClusterSnapshot.html). There could be other for multiple calls such as failed network connectivity after invoking `IAmazonRDS.CreateDBClusterSnapshot()` in which case the call is already in pipeline to be processed by service, and another call could result in such error. Also, could you confirm if your logic to create snapshot is being executed from multi-process configuration where more than one agent/process could trigger this call with same snapshot identifier.

Also, there is `MaxErrorRetry` property for [IClientConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TIClientConfig.html) which indicates how many retry HTTP requests an SDK should make for a single SDK operation invocation before giving up.

Thanks,
Ashish

**Comment by mwhouser** [comment]
Hi @ashishdhingra 

Here's our method that creates the snapshots:

```csharp
public DbClusterSnapshotInformation CreateClusterSnapshot(
	string dbClusterId, 
	string snapshotId, 
	ILog log)
{
  var request = new Amazon.RDS.Model.CreateDBClusterSnapshotRequest();

  LogParameter("DB Cluster ID", dbClusterId, log);
  request.DBClusterIdentifier = dbClusterId;

  LogParameter("Snapshot ID", snapshotId, log);
  request.DBClusterSnapshotIdentifier = snapshotId;

  LogInvoke("CreateDBClusterSnapshot", log);
  var response = _client.CreateDBClusterSnapshot(request);

  // Save the request id
  LogRequestId(response.ResponseMetadata, log);

  return FillClusterSnapshotInformation(response.DBClusterSnapshot);
}
```

This is **not** a multi-threaded situation. It's a single-threaded case.

> There could be other for multiple calls such as failed network connectivity after invoking IAmazonRDS.CreateDBClusterSnapshot() in which case the call is already in pipeline to be processed by service, and another call could result in such error.

I think this is exactly the case and I am hoping a solution to avoid this can be created.

> Also, there is MaxErrorRetry property for IClientConfig which indicates how many retry HTTP requests an SDK should make for a single SDK operation invocation before giving up.

Yes, but this is at the **client level**. Not the **method level**. IMO, it makes 100% sense to retry default number of times for "describe" calls, but "create" should not retry. The retry is masked behind the "duplicate" error result.

As a caller, when I receive the "duplicate" result, I don't know whether it's a failed network case, or a true duplicate case.

If the retry could be set to 1 for "create" and use the default value for "describe", that would be very helpful: I could catch the network error and handle it appropriately for my application.

**Comment by ashishdhingra** [comment]
@mwhouser There is no such property to control the retry mechanism at method level. The `MaxErrorRetry` is set at the service client level and affects all operations. Also, the models in SDK are based on service API models. I also notice that once the service client is constructed with `MaxErrorRetry` in config parameter, its value cannot be modified. I'm not sure if using the environment variable `AWS_MAX_ATTEMPTS` and dynamically changing it would help since the service client configuration is read-only once set. So you might have to use separate client for creating snapshot for your use case.

**Comment by mwhouser** [comment]
@ashishdhingra  OK. I can try using a dedicated client setting `MaxErrorRetry` to 1 for `CreateDBClusterSnapshot`.
