### ISSUE TITLE
How to set Parameters in Amazon.RedshiftDataAPIService.Model.BatchExecuteStatementRequest?

### ISSUE THREAD

**Issue by hmsca** [aws/aws-sdk-net#1889]
### How to set Parameters in Amazon.RedshiftDataAPIService.Model.BatchExecuteStatementRequest?

The "Parameters" property is missing: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/RedshiftDataAPIService/TBatchExecuteStatementRequest.html

Thanks

**Comment by ashishdhingra** [comment]
Hi @hmsca,

Good afternoon.

Thanks for posting guidance question.

Amazon RedShift Data API doesn't support parameterized SQL statements via BatchExecuteStatementRequest. For more details, refer the [BatchExecuteStatement](https://docs.aws.amazon.com/redshift-data/latest/APIReference/API_BatchExecuteStatement.html) service API operation. I'm not sure on how you would bind parameters to multiple SQL statements executed as a batch together. You could instead use [ ExecuteStatementRequest](https://docs.aws.amazon.com/it_it/sdkfornet/v3/apidocs/items/RedshiftDataAPIService/TExecuteStatementRequest.html) since this is supported by [ExecuteStatement](https://docs.aws.amazon.com/redshift-data/latest/APIReference/API_ExecuteStatement.html) service operation.

Thanks,
Ashish

**Comment by hmsca** [comment]
Thanks for your answer @ashishdhingra! I will look into ExecuteStatementRequest instead.
