### ISSUE TITLE
How to list all owner ids?

### ISSUE THREAD

**Issue by kibernetik542** [aws/aws-sdk-net#1911]
I would like list images by owner ids:

This my code:

```
 static async Task<object> AwsImagesList(string awsAccessKeyId, string awsSecretAccessKey, string awsRegion)
        {
            AmazonEC2Client client = new AmazonEC2Client(awsAccessKeyId, awsSecretAccessKey, RegionEndpoint.GetBySystemName(awsRegion));

            DescribeImagesRequest request = new DescribeImagesRequest
            {
                Filters = new List<Filter>
                {
                    new() {Name = "architecture", Values = new List<string> {"x86_64"}},
                    new() {Name = "state", Values = new List<string> {"available"}},
                    new() {Name = "virtualization-type", Values = new List<string> {"hvm"}},
                    new() {Name = "image-type", Values = new List<string> {"machine"}}
                },
               // Owners = new List<string>{"id"}
                
            };

            try
            {
                DescribeImagesResponse response = await client.DescribeImagesAsync(request);

                var images = response.Images.ToList();
                Console.WriteLine(images.Count);
                return images;
            }
            catch (Exception)
            {
                return "Bad Credentials";
            }
        }
```

I tried to list all but it takes very very long time, so we would like to list by ownerid in filtering, I suppose it is same as aws account id, question is how we can get owner id list?

P.S.   If I add platform windows it will be already more than 7000 result which is long, we need list ownerids and paste as owners filter.

**Comment by ashishdhingra** [comment]
Hi @kibernetik542,

Good morning. 

I'm not sure why this issue was classified as a feature request, changing it to guidance. There is no direct way of listing the Owner ID(s) since it is tied to an AMI image. Following articles provide a way to list Owner ID(s) when using AWS CLI:
- [Locating AWS Marketplace AMI Owner Id and Image Name for Packer Builds](https://blog.gruntwork.io/locating-aws-ami-owner-id-and-image-name-for-packer-builds-7616fe46b49a)
- [Find AWS EC2 AMI owner ID](https://michaelheap.com/aws-find-ami-owner-id/)

Implementing the similar logic in C# is pretty straightforward, reusing your code below:
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.EC2;
using Amazon.EC2.Model;

namespace EC2ImageOwnerIdTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            AmazonEC2Client client = new AmazonEC2Client();

            var images = await AwsImagesList(client);
            Console.WriteLine("{0} Images found.", images?.Count ?? 0);

            var ownerIds = images?.Select(i => i.OwnerId).Distinct();
            Console.WriteLine("{0} Owner Ids found.", ownerIds?.Count() ?? 0);
            Console.WriteLine(string.Join(", ", ownerIds));

            Console.ReadLine();
        }

        private static async Task<List<Image>> AwsImagesList(AmazonEC2Client client)
        {
            List<Image> images = null;

            if (client != null)
            {
                DescribeImagesRequest request = new DescribeImagesRequest
                {
                    Filters = new List<Filter>
                    {
                        new Filter {Name = "architecture", Values = new List<string> {"x86_64"}},
                        new Filter {Name = "state", Values = new List<string> {"available"}},
                        new Filter {Name = "virtualization-type", Values = new List<string> {"hvm"}},
                        new Filter {Name = "image-type", Values = new List<string> {"machine"}}
                    },
                    // Owners = new List<string>{"id"}
                };

                DescribeImagesResponse response = await client.DescribeImagesAsync(request);

                images = response.Images.ToList();
            }

            return images;
        }
    }
}
```

Hope this helps.

Thanks,
Ashish

**Comment by kibernetik542** [comment]
Thanks Ashish, it works fine, so after all investigating, it seems we need platform in filtering and ownerid's.
Owner id's we can get with your solution. But now we need also initially pass platform to get results faster. I tried windows and it is reasonable to wait 30-40 seconds, but I tried linux and ubuntu as platform value, it returned 0 result for me.

So simply
1 - we need to get platform values
2 - then add platform name as value to filtering
3 - get owner ids
4 - use platform+owner id to get results faster

P.S. If I try remove platform from filtering and try to execute to get all platform values, it will be infinite loop as I suppose it is a lot of results.

Is it any another way to get platform values faster?

Thanks in advance.

**Comment by ashishdhingra** [comment]
> Thanks Ashish, it works fine, so after all investigating, it seems we need platform in filtering and ownerid's.
> Owner id's we can get with your solution. But now we need also initially pass platform to get results faster. I tried windows and it is reasonable to wait 30-40 seconds, but I tried linux and ubuntu as platform value, it returned 0 result for me.
> 
> So simply
> 1 - we need to get platform values
> 2 - then add platform name as value to filtering
> 3 - get owner ids
> 4 - use platform+owner id to get results faster
> 
> P.S. If I try remove platform from filtering and try to execute to get all platform values, it will be infinite loop as I suppose it is a lot of results.
> 
> Is it any another way to get platform values faster?
> 
> Thanks in advance.

@kibernetik542 If you refer the AWS .NET SDK API reference at https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TImage.html, the `Platform` field is set to `windows` for Windows AMIs; otherwise, it is blank. This is also as per [EC2 -> DescribeImages](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeImages.html) API documentation which states that `platform` parameter is used to only list Windows-based AMIs. This is a limitation of the service API, not an issue with AWS SDK for .NET. I came across one StackOverflow article [AWS - finding a Linux AMI](https://stackoverflow.com/questions/43391715/aws-finding-a-linux-ami). You may try using the similar approach in .NET code as shown below:
```C#
private static async Task<List<Image>> AwsImagesList(AmazonEC2Client client)
        {
            List<Image> images = null;

            if (client != null)
            {
                DescribeImagesRequest request = new DescribeImagesRequest
                {
                    Filters = new List<Filter>
                    {
                        new Filter {Name = "architecture", Values = new List<string> {"x86_64"}},
                        new Filter {Name = "state", Values = new List<string> {"available"}},
                        new Filter {Name = "virtualization-type", Values = new List<string> {"hvm"}},
                        new Filter {Name = "image-type", Values = new List<string> {"machine"}},
                        new Filter {Name = "description", Values = new List<string>{ "*ubuntu*", "*linux*" } }
                    },
                    // Owners = new List<string>{"id"}
                };

                DescribeImagesResponse response = await client.DescribeImagesAsync(request);

                images = response.Images.ToList();
            }

            return images;
        }
```

I tried above code, the results might not be consistent since there was image with `Platform` as `windows` (could be easily found using LINQ expression `images.Where(i => i.Platform == "windows")`) but had Description as `[Copied ami-04f990ec619254ab6 from us-east-1] mps-r2019a-linux-vm1-1904101140`. However, upon further examination, in this case `RootDeviceName` was set as `/dev/sda1`, so it appears that it had incorrect platform label.

Feel free to explore properties of `Image` type and see how you could use filters that suits your scenario.

Hope this helps. Closing this issue since appropriate guidance has been provided.

Thanks,
Ashish
