### ISSUE TITLE
DKIM verification using SES for 2048 bit key is stuck

### ISSUE THREAD

**Issue by efizitoom** [aws/aws-sdk-net#1917]
Trying to upgrade DKIM signature  to 2048 bits in Amazon simple service by Manual DKIM Signing in Amazon SES
## Describe the Feature

Followed the steps 
[1] https://docs.aws.amazon.com/cli/latest/reference/ses/send-raw-email.html  
[2] http://www.dkim.org/  
[3] https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-authentication-dkim-manual.html  
### Describe alternatives you've considered

SES providing "SendRawEmail" to send the email for manual DKIM Signing in Amazon. There is no method to add dkim_private_key to send"SendRawEmail".
## Additional Context

How do we add headers using SendRawEmail function?
### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @efizitoom,

Good morning.

I'm not sure if this is the feature request for SDK since the API for Simple Email Service is autogenerated and maps with the service API. The link https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-authentication-dkim-manual.html you shared corresponds to Amazon SES Classic. You could follow these links for details related to DKIM:
- [Authenticating Email with DKIM in Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-dkim.html)
- [Provide your own DKIM authentication token in Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-dkim-bring-your-own.html)
- [Manual DKIM signing in Amazon SES](https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-dkim-manual.html)

Also, refer https://github.com/awsdocs/amazon-ses-developer-guide/blob/master/doc-source/send-email-authentication-dkim.md, the DKIM signature should be added in `DKIM-Signature` header field.

If you refer the [SendRawEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html) API reference, `RawMessage` specifies that `The message has to contain a header and a body, separated by a blank line.`. Since this is a raw message, you would need to supply `DKIM-Signature` in this property itself.

Hope this helps.

Thanks,
Ashish

**Comment by efizitoom** [comment]
Hi @ashishdhingra 
Good morning ,
Your  co-operation is highly appreciated. 
I tried the steps you have provided but failed in case of  2048 bits. As per your respond "If you refer the SendRawEmail API reference, RawMessage specifies that The message has to contain a header and a body, separated by a blank line."can you please provide any sample or link of adding DKIM-Signature in the header of RawMessage .

Thanks 
efizitoom,

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra
> Good morning ,
> Your co-operation is highly appreciated.
> I tried the steps you have provided but failed in case of 2048 bits. As per your respond "If you refer the SendRawEmail API reference, RawMessage specifies that The message has to contain a header and a body, separated by a blank line."can you please provide any sample or link of adding DKIM-Signature in the header of RawMessage .
> 
> Thanks
> efizitoom,

@efizitoom Good morning. Please refer following links for examples of composing raw message (which is of type `string`):
- [Sending Emails for the Identity Owner for Amazon SES Sending Authorization](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-delegate-sender-tasks-email.html)
- [Sending raw email using the Amazon SES API](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-raw.html)

Kindly refer [DKIM Explained](https://mailtrap.io/blog/dkim/) for details around DKIM.

My assumption is that you need to specify properly formatted `DKIM-Signature` header in the raw message.

Hope this helps.

Thanks,
Ashish
