### ISSUE TITLE
Xamarin IOS System.DllNotFoundException: 'Crypt32.dll assembly:<unknown assembly> type:<unknown type> member:(null)' 

### ISSUE THREAD

**Issue by briancfertig** [aws/aws-sdk-net#1931]
I am working on an IOS application and everything is going swimmingly until I went to initialize my s3client.  When I do I get the error above.  I launch it in the sim and it fails.  I have searched high and low looked a various articles and white papers.  No go.  I wrote a .net WinForms app that works just fine.  Any ideas?  Is there some other way I should be doing this?

**Comment by csm101** [comment]
I am getting the same DLLNotFound exception in my Xamarin.Android app.
 it happens when I try to initialize a new AmazonSQSClient
   SqsClient = new AmazonSQSClient(AwsAccessKeyId, AwsSecretAccessKey, RegionEndpoint.EUWest1);

The weird thing is that this works fine if I build the same project using VS 2019... the bug happens only if use VS 2022

**Comment by doclemo** [comment]
I ended up bailing on the SDK for xamarin and rewrote my API using the API gateway and lambda.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by quibenefacit** [comment]
I too am encountering the same error with the latest version of Visual Studio 2022 (17.3.6) when deploying a Debug build onto an Android device or emulator.

**Comment by dscpinheiro** [comment]
We just released an update (included in `Core 3.7.303.23`) where the SDK won't attempt to load `Crypt32.dll` when not running on Windows. 

It does require targeting .NET 8 (or greater), but should prevent this error from happening in iOS or Android.
