### ISSUE TITLE
Mono with KMS and HttpWebRequest (403 Forbidden: Server)

### ISSUE THREAD

**Issue by knguyen0928** [aws/aws-sdk-net#196]
Hello, I'm using KMS part of the SDK 2.3.29 with Mono 3.12.1.

KMS uses HttpWebRequest to communicate with the server to encrypt/decrypt data, in my use the uri is "https://kms.us-east-1.amazonaws.com/". But this problem can be reproduced *without* using the SDK

```csharp
var uri = "https://kms.us-east-1.amazonaws.com/";
var request = WebRequest.Create(uri) as HttpWebRequest;
try
{
	using (var reader = new StreamReader(request.GetResponse().GetResponseStream ()))
		Console.WriteLine(reader.ReadToEnd());
}
catch(WebException ex)
{
	Console.WriteLine(ex.Message);
	using (var reader = new StreamReader(ex.Response.GetResponseStream ()))
		Console.WriteLine(reader.ReadToEnd());
}
```

This is the output
```
The remote server returned an error: (403) Forbidden.
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>Server</center>
</body>
</html>
```

The correct response would be (as running on Windows)
```
The remote server returned an error: (403) Forbidden.
<MissingAuthenticationTokenException>
  <Message>Missing Authentication Token</Message>
</MissingAuthenticationTokenException>
``` 

When running under Mono, the server *refused* to talk to the client (the Mono app), no matter what the request method (GET, POST,...) or the content (containing Auth Token or not). I'm guessing the server requires a specific set of ciphers to be used and Mono can't cope with that.

Also, this *only* happens with KMS endpoint, other endpoints like EC2 or S3 work under Mono perfectly consistent with Windows.

Another interesting fact to note: If I run the same code, but through a proxy, it works perfectly with Mono.

**Comment by jimfl** [comment]
It looks like the first response is from a proxy and not from the service. Are your proxy settings on the system running with Mono?

**Comment by knguyen0928** [comment]
@jimfl thank you for your prompt response. To answer your question, no, the first response is from the service itself. I've tried on two different CentOS boxes and two different Macs, they all return the same response: 403 Forbidden - Server. They are not through a proxy. If I make the request through a proxy, the service returns correctly (Missing Authentication Token).

**Comment by jimfl** [comment]
In working with the KMS team, the issue appears to center on the fact that KMS requires the use of TLS ciphersuites that support perfect forward secrecy (essentially, ones that contain ECDHE or DHE within the name) due to the highly sensitive nature of the data being passed between the service and applications.

Mono 3.x can not presently negotiate a TLS connection with a ciphpersuite that has the perfect forward-secrecy property, and so the connection is rejected. The KMS team is looking into making the error message for this condition more helpful.

There is a project called [mono-tls](https://github.com/mono/mono-tls) which looks like it has supports DHE ciphersuites, but it requires Mono 4.0, and has other external dependencies, so it isn't a drop-in upgrade.

**Comment by knguyen0928** [comment]
@jimfl Thank you, this is very helpful.

**Comment by akotranza** [comment]
This is not a solution.

Why is the KMS SDK even available for Mono 4.x (via nuget, etc) if it is completely unusable?

AWS team needs to fix this, either support a platform all the way or don't support it at all. It is very difficult to build production applications using AWS SDKs other than S3, EC2 because so much of the SDK functionality is only halfway done.

**Comment by jimfl** [comment]
I agree that this problem is not solved. It seems to me that the problem is outside the scope of this project.

The SDK does not explicitly support Mono, except via Xamarin.

The requirement for forward secrecy was an explicit security design decision by the AWS KMS team. There's nothing that can be added to the SDK to make this work for Mono as it is currently implemented.

**Comment by akotranza** [comment]
Note that calling KMS API endpoints using v4 signed POST or GET requests also appears to have the same issue.

Thus rendering KMS completely unusable from Mono.
