### ISSUE TITLE
PutObjectRequest is missing Timeout & ReadWriteTimeout in .net core 3.1 version of AWSSDK.S3 3.7.7.14

### ISSUE THREAD

**Issue by eangelov** [aws/aws-sdk-net#1970]
## The Question
In the AWSSDK.S3 for .net 4.5 the Timeout & ReadWriteTimeout properties are present on PutObjectRequest. Those same properties are missing in the sdk for .net core 3.1.
![image](https://user-images.githubusercontent.com/3601104/149946760-f01400f7-a728-4ba0-b679-a80ff42b0ea2.png)
![image](https://user-images.githubusercontent.com/3601104/149946543-a9821ef8-d3af-46c8-8b29-e0c874a0109c.png)

Does anyone know if this is intentional or is this bug?

### Environment

* SDK Version: AWSSDK.S3 3.7.7.14
* Package Version: AWSSDK.S3 3.7.7.14
* OS Info: Windows 10
* Build Environment: Visual Studio 2019 
* Targeted .NET Platform:  .net core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @eangelov,

Good morning.

You are correct, `BCL` version of some of the request objects, e.g. [PutObjectRequest](https://github.com/aws/aws-sdk-net/blob/82ec756de374a6a2d0dce55df00b537a6929a577/sdk/src/Services/S3/Custom/Model/_bcl/PutObjectRequest.bcl.cs#L69), provide the `Timeout` & `ReadWriteTimeout` properties which are missing in corresponding `NETSTANDARD` version. 

For setting the `Timeout` & `ReadWriteTimeout` values, you could use `AmazonS3Config` object that could be configured for `AmazonS3Client`. The `Timeouts` section in https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html provides an example. However, please note that the `ReadWriteTimeout` is **obsolete for versions of the AWS SDK for .NET that target .NET Core.** The reason is that the version of the AWS SDK for .NET that targets the portable class library (PCL) uses the [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) class instead of the `HttpWebRequest class`, and supports the [Timeout](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout) property only.



The probably reason on why these properties were not removed from `BCL` version is to maintain backwards compatibility.

Hope this helps.

Thanks,
Ashish

**Comment by eangelov** [comment]
> Hi @eangelov,
> 
> Good morning.
> 
> You are correct, `BCL` version of some of the request objects, e.g. [PutObjectRequest](https://github.com/aws/aws-sdk-net/blob/82ec756de374a6a2d0dce55df00b537a6929a577/sdk/src/Services/S3/Custom/Model/_bcl/PutObjectRequest.bcl.cs#L69), provide the `Timeout` & `ReadWriteTimeout` properties which are missing in corresponding `NETSTANDARD` version.
> 
> For setting the `Timeout` & `ReadWriteTimeout` values, you could use `AmazonS3Config` object that could be configured for `AmazonS3Client`. The `Timeouts` section in https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html provides an example. However, please note that the `ReadWriteTimeout` is **obsolete for versions of the AWS SDK for .NET that target .NET Core.** The reason is that the version of the AWS SDK for .NET that targets the portable class library (PCL) uses the [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient) class instead of the `HttpWebRequest class`, and supports the [Timeout](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout) property only.
> 
> The probably reason on why these properties were not removed from `BCL` version is to maintain backwards compatibility.
> 
> Hope this helps.
> 
> Thanks, Ashish

Thanks for the info.
