### ISSUE TITLE
Not possible to distinguish populated and not populated ExistingVersion in RejectedRecordsException (Timestream)

### ISSUE THREAD

**Issue by nicollaas94** [aws/aws-sdk-net#1976]
## Description
I'd like to catch and handle Timetream RejectedRecordsException, one of the scenarios is that a message already exists in the database.

For that, the documentation states the following:

> ExistingVersion
The existing version of the record. This value is populated in scenarios where an identical record exists with a higher version than the version in the write request.

However, when trying to check if ExistingVersion is populated, it is impossible to distinguish between the not-populated version and version 0.

`ex.RejectedRecords.Any(r => r.ExistingVersion != default)`

the only alternative is to then check the Reason field instead.

`ex.RejectedRecords.Any(r => r.Reason.Contains("record already exists"))`

## Reproduction Steps
Insert 2 items with the same time, dimensions, measure name, and record version.
Catch the exception and try to verify if ExistingVersion is populated.

## Resolution
Make ExistingVersion nullable 

## Workaround
check reason string instead (far from ideal)

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @nicollaas94,

Good morning.

Upon investigating, it looks like that the [RejectedRecord](https://github.com/aws/aws-sdk-net/blob/718a11159658675257bb63c0aa0712e6cf3380f8/sdk/src/Services/TimestreamWrite/Generated/Model/RejectedRecord.cs#L35) class is auto-generated from [timestream-write](https://github.com/aws/aws-sdk-net/blob/718a11159658675257bb63c0aa0712e6cf3380f8/generator/ServiceModels/timestream-write/timestream-write-2018-11-01.api.json#L611) service model. The [ExistingVersion](https://github.com/aws/aws-sdk-net/blob/718a11159658675257bb63c0aa0712e6cf3380f8/generator/ServiceModels/timestream-write/timestream-write-2018-11-01.api.json#L591)(RecordVersion) is of type `long` and correctly modeled in the `RejectedRecord` class. The service model doesn't specify anything that indicates nullable data type in the shape. Also, due to backwards compatibility, this has been limitation in other model classes as well, something which team is aware of.

As pointed by you, [RejectedRecord API](https://docs.aws.amazon.com/timestream/latest/developerguide/API_RejectedRecord.html) specifies that `ExistingVersion` value is populated in scenarios where an identical record exists with a higher version than the version in the write request. However, I also see that in [Record](https://docs.aws.amazon.com/timestream/latest/developerguide/API_Record.html) data type, the value of `Version` must be `1` or greater, with default value `1`. Hence, it appears that you should be able to distinguish if the `ExistingVersion` is populated or not in `RejectedRecordsException` by comparing with the value `0`. Please correct me if this is not the case and you have somehow value `0` for `Version` for existing records.

Thanks,
Ashish

**Comment by nicollaas94** [comment]
Hey @ashishdhingra, sorry for the late reply, yes I am **having value 0 for version for existing records**, this is what triggered my confusion :D.

Wasn't aware that the version starts from 1, so it is a problem in the Timestream itself I suppose?
Can I help with some log, account id, should I open ticket support at AWS instead?
