### ISSUE TITLE
ScanOperationConfig.ScanFilter does not work as expected with nested properties

### ISSUE THREAD

**Issue by denxorz** [aws/aws-sdk-net#2003]
## Description
When scanning on a nested property using the `ScanFilter` no results will be returned. Using the same expression in `FilterExpression` does result in results. So there seems to be a difference in using the `ScanFilter` and `FilterExpression` properties of the `ScanOperationConfig`. The `ScanFilter` does not seem to handle nested properties as expected. 

Could be related to https://github.com/aws/aws-sdk-net/issues/1805 . But `FilterExpression` actually gives the correct result without splitting the nested property name as explained in #1805. 

## Reproduction Steps
Example data structure:
```
{
  "id": {
    "S": "23a19237-960b-476a-86c0-42eafa2bb1e8"
  },
  "info": {
    "M": {
      "lastMeasurementTimestamp": {
        "S": "2022-04-07T04:34:02+00:00"
      }
    }
  }
}
```

With `ScanFilter` (which does NOT give results):
```
var filter = new ScanFilter();
filter.AddCondition("info.lastMeasurementTimestamp", ScanOperator.LessThan, date);

var search = table.Scan(new ScanOperationConfig
{
	Filter = filter,
});
```

With `FilterExpression` (gives results):
```
var search = table.Scan(new ScanOperationConfig
{
	FilterExpression = new()
	{
		ExpressionStatement = "info.lastMeasurementTimestamp < :date",
		ExpressionAttributeValues = new() { {":date", date} }
	},
});
```

### Logs
-

### Environment

* SDK Version: -
* Package Version: 3.7.3.14
* OS Info: AmazonLinux
* Build Environment: Visual Studio
* Targeted .NET Platform: net5 

## Resolution
- 

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @denxorz,

Good morning.

Thanks for reporting the issue. Going by the https://github.com/aws/aws-sdk-net/issues/1805#issuecomment-788125181, this behavior is by design. AWS SDK for .NET has the same behavior as AWS Console. Also refer https://github.com/aws/aws-sdk-net/issues/1872#issuecomment-863455320, which has a note that per https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html, the ScanFilter is a legacy parameter. Recommended technique is to use Filter Expression, example at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetScanning.html.

Thanks,
Ashish
