### ISSUE TITLE
Modularised SDK and AWS.SessionProvider

### ISSUE THREAD

**Issue by amitatgit** [aws/aws-sdk-net#205]
I am trying to upgrade to modularised version of sdk and having trouble with a project which uses AWS DynamoDB Session Provider (AWS.SessionProvider.dll). AWS.SessionProvider still has a dependency on AWSSDK.dll. If i add AWSSDK.dll then it conflicts with AWSSDK.Core.dll.

Any suggestions?

**Comment by normj** [comment]
We haven't moved the session provider over to V3 yet. It is on our list to do before we take V3 out of preview. I understand this is probably blocking you, we'll try and get the priority of this bumped up.

**Comment by IainCole** [comment]
I made a pretty hacky port here https://github.com/IainCole/aws-sdk-net/tree/modularization Had to make some internal stuff public so probably isn't the best solution so I'd wait until it's done properly but if you're really stuck it might work.

**Comment by amitatgit** [comment]
Thanks Iain! I will wait for next release from aws...

**Comment by normj** [comment]
A new version of the session provider has just been released to NuGet that is based on the modularized SDK. Note this version is marked as preview since the SDK is still preview.

http://www.nuget.org/packages/AWS.SessionProvider/3.0.0-preview

Also the source for the session provider has moved to a separate repository.

https://github.com/aws/aws-dotnet-session-provider
