### ISSUE TITLE
SuppressNextMessage in DialogState must have ability to be null

### ISSUE THREAD

**Issue by var1ap-WA** [aws/aws-sdk-net#2128]
### Describe the bug

It's not possible to create DialogState with SuppressNextMessage with null value

### Expected Behavior

SuppressNextMessage in DialogState must have ability to be null

### Current Behavior

![image](https://user-images.githubusercontent.com/63446336/195190548-79b3a8c0-a0f4-4fdb-92d9-379888e10ffb.png)
in `CreateIntentAsync` method

### Reproduction Steps

try to call `DescribeIntentAsync` method where 
`InitialResponseSetting.CodeHook.PostCodeHookSpecification.SuccessNextStep.DialogAction.SuppressNextMessage` is null but default value become **false**

### Possible Solution

Change type for `SuppressNextMessage` from **bool** to **bool?**

### AWS .NET SDK and/or Package version used

"AWSSDK.LexModelsV2" Version="3.7.17.9"

### Targeted .NET Platform

 .NET Core 3.1

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
This is the side-effect of the detailed explanation mentioned in https://github.com/aws/aws-sdk-net/issues/1721#issuecomment-702969647 where in current version of SDK, it is not possible to assign `null` value to backing nullable field. Also LexV2 model classes are auto-generated. Might not be fixed in current SDK version, should be fixed in next version of SDK.

@var1ap-WA The model specification for [DialogAction](https://docs.aws.amazon.com/lexv2/latest/dg/API_DialogAction.html) specifies that `suppressNextMessage` is not a required property and when set to `true`, the next message for the intent is not used. It doesn't specify the behavior if this property is not specified (so default value appears to be `false`). So could you please elaborate your use case where you need to explicitly set it to `null` rather than relying on default `false` value.

Thanks,
Ashish

**Comment by var1ap-WA** [comment]
@ashishdhingra thank you for your answer
I am trying to create bots based on my template bot.
In my bot template, this field is null and everything works as it should
![image](https://user-images.githubusercontent.com/63446336/195302246-f3af6624-20ca-4b7c-ac1b-48730f229be0.png)

, but when I try to create a clone based on this template, this is what happens
![image](https://user-images.githubusercontent.com/63446336/195302371-37743434-5070-4df8-bc28-d42bdcad6207.png)

and it's not possible to build the clone bot, because of this `SuppressNextMessage` field

**Comment by ashishdhingra** [comment]
> @ashishdhingra thank you for your answer I am trying to create bots based on my template bot. In my bot template, this field is null and everything works as it should ![image](https://user-images.githubusercontent.com/63446336/195302246-f3af6624-20ca-4b7c-ac1b-48730f229be0.png)
> 
> , but when I try to create a clone based on this template, this is what happens ![image](https://user-images.githubusercontent.com/63446336/195302371-37743434-5070-4df8-bc28-d42bdcad6207.png)
> 
> and it's not possible to build the clone bot, because of this `SuppressNextMessage` field

@var1ap-WA Thanks for your reply. Just curious on how your bot template are created. Are they manually crafted? Could these be modified to have default value of `false` for `SuppressNextMessage` field? Since this property is not mandated by the service and there is the limitation in the current version of SDK on how nullable fields are handled, we do not have other workaround and possible fix soon.

Thanks,
Ashish
