### ISSUE TITLE
Using DynamoDB local hangs in VS 2015, throws unknown error (Win 10).

### ISSUE THREAD

**Issue by VictorySquareAdmin** [aws/aws-sdk-net#237]
Hello

I am using Visual Studio 2015 with Windows 10. DynamoDB local appears to start up successfully, and tables can be created as normal. However attempting to open a table for viewing causes VS to hang for +30 seconds, followed by:

```
Error executing query: The request processing has failed because of 
an unknown error, exception or failure
```

Further, attempting to access 'stream properties...' on any table throws the following error:

```
Unknown Error: Object reference not set to an instance of an object.
```

I appear to have my Java/JDK runtimes up to date, and I've already tried reinstalling the plugin & the DynamoDB local add-in. This appears to have started after I upgraded to Windows 10, unfortunately I don't have a Windows 8 device to confirm this.

**Comment by normj** [comment]
I just reproduced the issue. Digging into the code to see what is going on.

**Comment by normj** [comment]
The problem was the latest version of DynamoDB local that the toolkit was offering to install was out of date and incompatible with the version of the SDK that the toolkit uses. I updated the manifest so that the next time you go to start DynamoDB local you should see version 2015-07-16. Install and run that version and then you should be good.
