### ISSUE TITLE
Xamarin S3 Upload more than one file at once

### ISSUE THREAD

**Issue by ceichin** [aws/aws-sdk-net#239]
I need to upload a directory or upload more than one file at once to an S3 bucket. I found this: http://docs.aws.amazon.com/AmazonS3/latest/dev/HLuploadDirDotNet.html but there is no such method in TransferUtility using the .NET SDK in Xamarin.

Is there a way to upload many files at once easily? Or, is that method being implemented?

I'm using Xamarin.iOS with SDK .NET Nuget v3.1.2.1 on Xamarin Studio. Thanks.

**Comment by MichaelMcGlothlin** [comment]
It should be there. Using the right namespace? If I remember right it isn't directly under S3.

📱 Michael McGlothlin

**Comment by ceichin** [comment]
Thanks for your response Michael. 

I checked the TransferUtility class and I can't find the UploadDirectory or UploadDirectoryAsync methods (see attached image). The documentation (the link in my first post) says the namespaces are Amazon.S3 and Amazon.S3.Transfer (where TransferUtiliy class is located). I also tried intellisense to suggest me but no luck.

Maybe it's the fact that is not available for Xamarin? Or do I need to do something more? No need to be a directory, if there is a way to upload many files at once is more than enough for me.

Thanks!

![screen shot 2015-08-30 at 7 33 31 pm](https://cloud.githubusercontent.com/assets/4664664/9569908/da7fedb8-4f50-11e5-8492-187d7815ae90.png)

**Comment by cyberguild** [comment]
ceichin,

Are you needing an S3 SDK or a command line utility?

There are 2 utilities/tools that provide a host of operations for AWS overall and S3 in particular. One is executed from a command line and one is a set of PowerShell cmdlets.

There 2 command line utilities that are confusing because they are both named CLI. One is CLI *Tools* and the other is CLI. 
1) CLI is very high level and basic - it has several useful S3 services, including file and directory upload/download, plus file synchronization. 
2) CLI Tools on the other hand functions at a lower level, but only has services for EC2, AMIs, and some VPC - not S3. 
3) Both CLI utilities rely on credentials being stored in clear text on the instance (a file for CLI and environment variables for CLI Tools), or an Instance Role assigned to the instance upon launch (you can't reboot an instance to pick up an Instance Role).  Clear text credentials is less of an issue if you are using the utility locally on your PC/Mac, but consider API calls and log files may contain commands with credentials.

AWS Tools for Windows PowerShell supports a broad array of AWS services - including S3.  Credentials are encrypted and stored in the SDK Store.  The advantage of AWS PowerShell cmdlets is the VERY broad array of AWS and Microsoft services supported.  The disadvantage is the learning curve and scripting complexity, plus the lack of adequate AWS documentation showing examples of common activities using a variety of cmdlet options.

If you want something "quick and dirty", CLI will probably get the S3 job done.  If you need to include Microsoft .NET methods/commands/services - PowerShell is the way to go.  I mostly use PowerShell because of its encrypted credentials (but I have found bugs - like lack of an accurate file count for uploading files over 1GB to S3 - it reports 0 for all files greater than about 1 GB, but I have a workaround that requires scripting to verify all objects were uploaded).

Hope this helps.


Tools for Amazon Web Services 
* This index highlights the primary SDKs, IDE Toolkits, and Command Line Tools for developing and managing your AWS applications: https://aws.amazon.com/tools/?nc1=f_dr
* AWS Command Line Interface: https://aws.amazon.com/cli/
* AWS Tools for Windows PowerShell: http://aws.amazon.com/powershell/
* AWS Command Line Tools: http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/Welcome.html

**Comment by PavelSafronov** [comment]
At the moment the Xamarin version of the SDK does not have directory/multi-file upload/download support. For now, you will have to manually loop through multiple files and call UploadAsync for each one.

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
