### ISSUE TITLE
DynamoDB object persistence of class hierarchies

### ISSUE THREAD

**Issue by corruptmem** [aws/aws-sdk-net#245]
I'm using the object persistence model as documented here: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetSDKHighLevel.html in V2 conversion schema mode as documented here https://blogs.aws.amazon.com/net/post/Tx2TCOGWG7ARUH5/DynamoDB-Series-Conversion-Schemas

I have a class hierarchy (as in, class Animal; class Dog : Animal; class Cat : Animal) that share some base properties but also have their own properties in the derived classes. I'm mapping them all to the same table using DynamoDBTable as the documentation mentions you can do here: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DeclarativeTagsList.html

So, although it is possible to store the objects and it saves all the properties. However, if I try to load them out with context.Load<Animal>(...), it will only try to deserialize into the parent class. This either means I lose the child properties, or if Animal is abstract I get an InvalidOperationException. It would appear that I actually need to know ahead of time what type object is before deserializing it, which doesn't easily work if query/scan the table rather than just loading a single object..

With most ORMs, you can get it to save a type discriminator column so that it knows what type to deserialize into at runtime.

**Comment by PavelSafronov** [comment]
This is a limitation of the Object Persistence Model: source type is not stored and you must explicitly specify the non-abstract class that the item should be serialized into. All of the functionality of the DynamoDBContext is implemented with this in mind. For example, if you specify the base class as the type for Scan, but then attempt to use a property that is present only on a child class, the context will throw an exception because it is unable to find the child property, which it needs in order to understand how to convert the property value.

That being said, you can implement the type discriminator column on your own using the [Document Model API](http://blogs.aws.amazon.com/net/post/Tx17SQHVEMW8MXC/DynamoDB-APIs) to make the service calls, then use DynamoDBContext to convert between Document objects and your classes. Below is a quick implementation of what this would look like for saving and loading items with the type discriminator. This can be added as a wrapper class built on top of the DynamoDBContext.

```
// class definitions
[DynamoDBTable("Animals")]
public class Animal
{
    public string Name { get; set; }
    public int Id { get; set; }
}
public class Dog : Animal
{
    public string FavoriteHydrant { get; set; }
}
public class Cat : Animal
{
    public int HoursOfSleepPerDay { get; set; }
}

// Load method
private static Animal LoadAnimal(DynamoDBContext context, Primitive hashKey, Primitive rangeKey)
{
    // get target table
    var table = context.GetTargetTable<Animal>();

    // load item from DynamoDB
    var doc = table.GetItem(hashKey, rangeKey);

    // get type discriminator
    var type = doc["__type__"];

    // create correct Animal instance
    Animal animal;
    if (type == typeof(Cat).FullName)
    {
        // convert document to appropriate class
        animal = context.FromDocument<Cat>(doc);
    }
    else
    {
        // convert document to default/base class
        animal = context.FromDocument<Animal>(doc);
    }

    return animal;
}

// Save method
private static void SaveAnimal<T>(DynamoDBContext context, T animal)
    where T : Animal
{
    // convert object to Document
    var doc = context.ToDocument<T>(animal);

    // add type discriminator
    doc["__type__"] = animal.GetType().FullName;

    // get target table
    var table = context.GetTargetTable<T>();

    // save item in DynamoDB
    table.UpdateItem(doc);
}

// Using the methods to save and load a Cat
using(var client = new AmazonDynamoDBClient())
{
    using(var context = new DynamoDBContext(client))
    {
        var panther = new Cat
        {
            Name = "Bagheera",
            Id = 42,
            HoursOfSleepPerDay = 20
        };
        SaveAnimal(context, panther);

        Animal animal = LoadAnimal(context, panther.Name, panther.Id);
        Cat cat = animal as Cat;
        // verify instance type
        System.Diagnostics.Debug.Assert(cat != null);
        // verify subclass data
        System.Diagnostics.Debug.Assert(cat.HoursOfSleepPerDay == 20);
    }
}
```
