### ISSUE TITLE
AmazonS3Client.GetPreSignedURL blocks the thread and there is no async option

### ISSUE THREAD

**Issue by saintarian** [aws/aws-sdk-net#2466]
### Describe the bug

We see our threads getting blocked with the call stack pasted below, causing thread starvation for our async code. 

We see this when running on ECS fargate, but only occasionally - probably when the credential refresh is slow for some reason. 

```
at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32 millisecondsTimeout, UInt32 startTime, CancellationToken cancellationToken)
at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials()
at Amazon.S3.AmazonS3Client.GetPreSignedURLInternal(GetPreSignedUrlRequest request, Boolean useSigV2Fallback)
```

### Expected Behavior

Calling AmazonS3Client.GetPreSignedURL doesn't block the thread, or there is a AmazonS3Client.GetPreSignedURLAsync version available. 

### Current Behavior

Calling AmazonS3Client.GetPreSignedURL blocks the thread. 

### Reproduction Steps

Reproducing this requires the following:
* Run code on an EC2/fargate instance to get a pre-signed url for a private S3 object in a loop. Running locally using access-key/secret won't cause credentials refresh to happen. 
* Use https://github.com/benaadams/Ben.BlockingDetector to log thread blocking

### Possible Solution

Implement AmazonS3Client.GetPreSignedURLAsync() that calls Credentials.GetCredentialsAsync() internally

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.0.18

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux (on ECS Fargate v1.4)

**Comment by ashishdhingra** [comment]
@saintarian Thanks for reporting the issue. This is more likely a feature request to implement `async` version of `AmazonS3Client.GetPreSignedURLAsync()`. Needs review with the team.

**Comment by jxwaters** [comment]
It seems there are async versions of ALL the other S3 client operations except this. Does that mean there are no http requests issued and this is all done client side?

**Comment by normj** [comment]
@jxwaters There is no service call to S3 which is why there is no `async` version. There is some value in us adding an `async` version because depending how the credentials are sourced a network call could be made. For example if the credential source was an assume role credentials or coming from EC2 instance metadata it is potential a network call could be made if the credentials have to be refreshed.

**Comment by mickdelaney** [comment]
+1

**Comment by Esther-St** [comment]
+1

**Comment by jedieaston** [comment]
I think this was resolved in https://github.com/aws/aws-sdk-net/commit/374a36f3a27bfd09daee844552ea987e5826eda8

Here's the method: https://github.com/aws/aws-sdk-net/blame/374a36f3a27bfd09daee844552ea987e5826eda8/sdk/src/Services/S3/Custom/IAmazonS3.Extensions.cs#L52

**Comment by muhammad-othman** [comment]
Thank you for mentioning that @jedieaston.
We did add GetPreSignedURLAsync as part of supporting `S3 Express One Zone` since Directory buckets calls can refresh the credentials via a service call if they expire. The `Async` version supports non directory buckets too, so it should work for this case.
@saintarian Please switch to `GetPreSignedURLAsync` and let us know if you need any further assistance.

**Comment by grippstick** [comment]
Can you please allow a CancellationToken to be passed in?
