### ISSUE TITLE
Code Generator Usage

### ISSUE THREAD

**Issue by sezhiyant** [aws/aws-sdk-net#251]
Hi All,

I have started working on adding Transaction support to DynamoDB.
I understand that some components are associated with automatic code generation. And i find this part a little cryptic.

Can someone please help me out with any pointers as how to add the required interfaces to the automatic code generation please ?

Thanks and Regards,
Sezhiyan

**Comment by PavelSafronov** [comment]
The code generation only impacts the low-level client code. For DynamoDB, you can see the generated client code [here](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/DynamoDBv2/Generated). The hand-coded bits of the DynamoDB SDK (notably TableModel and DataModel namespaces), are located under the "Custom" folder [here](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/DynamoDBv2/Custom) and are thus not impacted by the generation process. This is a quick summary of the generation process, you can get a deeper understanding by taking a deeper look through the codebase.

That being said, if you are planning on building a Transaction library, it's more appropriate to put this code into a separate package and repo, comparable to the [aws-dotnet-session-provider](https://github.com/aws/aws-dotnet-session-provider) tool, instead of adding this functionality to the SDK itself.

**Comment by sezhiyant** [comment]
Thanks Pavel.
I will create a separate package and submit my changes for review.
