### ISSUE TITLE
ICoreAmazonS3.DoesS3BucketExistAsync(string bucketName) is obsoleted and points to a faulty implementation

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#2536]
### Describe the bug

Why is [ICoreAmazonS3.DoesS3BucketExistAsync(string bucketName) obsoleted](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_async/AmazonS3Client.Extensions.cs#L151) and the implementation points to the also obsoleted `AmazonS3Util.DoesS3BucketExistAsync`?

As a client of the SDK, it is very hard to see the obsolete because it is not an obsolete that seems to propagate into the user code (at least our builds didn't get a warning, and we have warnings as errors).

I don't understand why the implementation uses a broken method while the implementation could be switched to use the correct version, which would also allow removing the obsolete. Was it done for backward compat reasons? 

### Expected Behavior

Having a version that works and it not obsoleted on the interface

### Current Behavior

The version is unreliable as described in the obsolete method

### Reproduction Steps

Use the IAmazonS3 DoesS3BucketExistAsync method

### AWS .NET SDK and/or Package version used

AWSSDK.S3 latest

### Targeted .NET Platform

All

### Operating System and version

All

**Comment by ashishdhingra** [comment]
Hi @danielmarbach,

Good morning.

Upon investigating further, from the obsolete message it appears that [Task<bool> ICoreAmazonS3.DoesS3BucketExistAsync(string bucketName)](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_async/AmazonS3Client.Extensions.cs#L151) has message `This method is deprecated: its behavior is inconsistent and always uses HTTP.`. I'm unsure why it was not updated to point to `AmazonS3Util.DoesS3BucketExistV2Async()`, perhaps as you mentioned, for backwards compatibility or consistent naming (notice `V2`) in method name.

(I'm unsure why this is opened as a bug, instead this should have been opened as `Q&A` discussion.)

Also refer https://github.com/aws/aws-sdk-net/issues/1250#issuecomment-868083409 for detailed findings on the behavior of `AmazonS3Util.DoesS3BucketExistV2Async()`.

Thanks,
Ashish

**Comment by danielmarbach** [comment]
Well the problem is that the first method in intellisense is the interface method which I pointed out is not obvious that it should not be used. Snd given that it uses an unreliable mechanism under the covers which there is one but that one is not obvious I filed it as a bug. We have spent quite a bit of time to find out we should not be using this method but the static utils one.

**Comment by ashishdhingra** [comment]
> Task ICoreAmazonS3.DoesS3BucketExistAsync(string bucketName)

@danielmarbach Thanks for your reply. The only way to mark a method as `Obsolete` in C# is to use the `ObsoleteAttribute`. Does Visual Studio not give intellisense that it's obsolete? 
![Screen Shot 2023-02-08 at 10 53 02 AM](https://user-images.githubusercontent.com/67916761/217626274-cb68459b-9250-49ff-824d-5a4479205a6f.png)

I also see the `warning` in the build output when compiling the solution:
```
Rebuild started...
1>------ Rebuild All started: Project: S3WriteGetObjectResponseTest, Configuration: Debug Any CPU ------
Restored D:\source\repros\S3WriteGetObjectResponseTest\S3WriteGetObjectResponseTest\S3WriteGetObjectResponseTest.csproj (in 6 ms).
Restored D:\source\CodeCommit\Repos\AWSDotNetPublic\sdk\src\Services\S3\AWSSDK.S3.NetStandard.csproj (in 29 ms).
1>D:\source\repros\S3WriteGetObjectResponseTest\S3WriteGetObjectResponseTest\Program.cs(9,13,9,60): warning CS0618: 'AmazonS3Util.DoesS3BucketExistAsync(IAmazonS3, string)' is obsolete: 'This method is deprecated: its behavior is inconsistent and always uses HTTP. Please use DoesS3BucketExistV2Async instead.'
1>S3WriteGetObjectResponseTest -> D:\source\repros\S3WriteGetObjectResponseTest\S3WriteGetObjectResponseTest\bin\Debug\net6.0\S3WriteGetObjectResponseTest.dll
1>Done building project "S3WriteGetObjectResponseTest.csproj".
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
========== Elapsed 00:00.618 ==========
```

I do see that [ObsoleteAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=net-7.0) has an overloaded constructor a Boolean value indicating whether the obsolete element usage is considered an error, but that's something we do not want to flag due to backwards compatibility.

I'm unsure what workaround we could give, I'm getting build warning for use of obsolete method.

Thanks,
Ashish

**Comment by danielmarbach** [comment]
> I do see that in [ICoreAmazonS3](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/SharedInterfaces/_async/ICoreAmazonS3.cs) interface, the declared method [DoesS3BucketExistAsync](https://github.com/aws/aws-sdk-net/blob/ffefae1aaf61b5cb515abcb65f8dfd52b2945435/sdk/src/Core/Amazon.Runtime/SharedInterfaces/_async/ICoreAmazonS3.cs#L109) is not marked as obsolete. This might be giving customer reported result as mentioned [here](https://grantwinney.com/the-effect-of-the-obsolete-attribute-on-a-class-is-ignored-when-theres-an-interface-involved/) as an example. Appears to be valid issue. 

That's precisely the problem. When you use it through the interface, you don't get the obsolete. That is what we stumbled into because even though we have newed up an S3Client we have used it "through the interface" which then doesn't trigger the obsolete warning

> So might be the fix for this issue would be to mark method as Obsolete at interface level as well.

That or as I said fix the implementation and remove the obsolete on the client hierarchy and change the implementation to use internally the v2 version. Keep the obsolete on the Util.

**Comment by normj** [comment]
Hi @danielmarbach 

We definitely could/should update the `DoesS3BucketExistAsync` as obsolete on the `ICoreAmazonS3` interface like it is in the implementation. 

I am  curious why are you using the `ICoreAmazonS3` interface? The docs for the interface say it is not meant for direct use. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/SharedInterfaces/ICoreAmazonS3.cs#L11

The `ICoreX` interfaces are really just meant for the SDK to get around some of the circular dependency challenges we have. The biggest and most obvious use case is Core has the logic for an assume role credential provider but in order to actually assume we need access to the Security Token service (STS) but STS depends on Core. So to get around these circular issues we define a generic interface in Core and then use explicit interface implementation on the service clients to sort of hide the extra generic interface methods.

So there is no reason for a direct usage of the interface because the service client's like S3 already have a more specific method to call. I can't remember why we didn't put the `ICore` interfaces in an internal namespaces like we do with most things that we only mean to share between Core and service packages.

**Comment by danielmarbach** [comment]
```csharp
IAmazonS3 s3Client = new AmazonS3Client();
await s3Client.DoesS3BucketExistAsync();
```

when you use the IAmazonS3 interface, you get all the interface methods of `ICoreAmazonS3` directly with intellisense.

![image](https://user-images.githubusercontent.com/174258/217661110-a235c8e8-e548-4cbd-b2af-3d23fc75c10b.png)

```csharp
public interface IAmazonS3 : IDisposable, ICoreAmazonS3, IAmazonService
```
> The docs for the interface say it is not meant for direct use. 

If that is the case why does the `IAmazonS3` implement then that interface? The client already does implement the interface explicitly.

```csharp
  public class AmazonS3Client : 
    AmazonServiceClient,
    IAmazonS3,
    IDisposable,
    ICoreAmazonS3,
    IAmazonService
  {

Task<bool> ICoreAmazonS3.DoesS3BucketExistAsync(string bucketName) => AmazonS3Util.DoesS3BucketExistAsync((IAmazonS3) this, bucketName);
```

which would mean I would normally not see this method in intellisense, but because the IAmazonS3 also implements ICoreAmazonS3 I get all those "internal methods" as well. 

There is really nothing special we are doing here :dancers:

**Comment by normj** [comment]
You are right, we should not have had the service interfaces extend from the `ICoreX` interfaces. That misses the point of us doing explicit interface implementation. Not sure if we can change that right now till we have a significant version bump since like you are pointing out we have no guarantees people aren't calling these methods. For now I'll copy over the obsolete from the implementation onto the interface.

**Comment by danielmarbach** [comment]
> For now I'll copy over the obsolete from the implementation onto the interface.

if you do that because you cannot fix the implementation due to backward compatibility I would suggest to make the obsoletion message point towards how to resolve this. So instead of

```
[Obsolete("This method is deprecated: its behavior is inconsistent and always uses HTTP.")]
```

say something like

```
[("This method is deprecated: its behavior is inconsistent and always uses HTTP. Please use AmazonS3Util.DoesS3BucketExistV2Async instead.")]
```

or even better

```
[("This method is deprecated: its behavior is inconsistent and always uses HTTP. Please use AmazonS3Util.DoesS3BucketExistV2Async instead. Will be treated as an error from version xxx. Will be removed in version yyy")]
```

FYI we use https://github.com/Fody/Obsolete to roll out obsoletions over multiple versions

**Comment by normj** [comment]
The obsolete message has been added as part of version [3.7.105](https://www.nuget.org/packages/AWSSDK.Core/3.7.105)
