### ISSUE TITLE
Suggestion: Support for ModernHttpClient

### ISSUE THREAD

**Issue by habermeier** [aws/aws-sdk-net#254]
I've not looked at it very deeply, but it would be good if the library could support (optionally) ModernHttpClient: https://github.com/paulcbetts/ModernHttpClient

Given it uses the optimal native implementations for Android and iOS.

**Comment by gokarnm** [comment]
Hi, I've added this feature request to our backlog and will update you when we implement it. In the meanwhile, if you want to try ModernHttpClient, you can easily modify the code to use ModernHttpClient. ModernHttpClient is implemented as a custom HttpClient handler, so you can use it instead of the default HttpClientHandler here -  https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L340 . 

```
var httpClient = new HttpClient(new NativeMessageHandler());
```

You can additionally set configuration options which ModernHttpClient supports similar to this code - https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L333-L338

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
