### ISSUE TITLE
Is there a way to check the ServiceUrl is valid for AmazonS3Config?

### ISSUE THREAD

**Issue by egormarkov** [aws/aws-sdk-net#257]
Now if i enter custom service url with some relative path like 'http://192.168.0.1/app/' (with ForcePathStyle = true) and try to use GetBucketLocationRequest it will hang and eat CPU. So far I'm doing check that url should not have relative path, but question is there an API method to allow me validate service url before using AWS? Thank you

**Comment by PavelSafronov** [comment]
There is no API in the .NET SDK to do this check.

**Comment by egormarkov** [comment]
Ok, then take a look at this case, i think it should be fixed in sdk, because it hang at all

**Comment by PavelSafronov** [comment]
I don't believe adding this functionality to the SDK would serve most users of the SDK.

For your specific case, you can force the SDK to fail faster with a configuration similar to one below. Currently, you're seeing the "hang" because the SDK is taking 120 seconds waiting for a response from a server that will never send one. The below approach simply cuts that time down to 5 seconds, though you can set an even shorter time when testing if a url works. (Keep in mind, that this config should only be used to determine if an endpoint is valid, not for actual service calls.)

```
var config = new AmazonS3Config
{
    ServiceURL = "http://192.168.0.1/app/",
    ForcePathStyle = true,
    Timeout = TimeSpan.FromSeconds(5)
};
```
