### ISSUE TITLE
AWS_DEFAULT_REGION environment variable not being read.

### ISSUE THREAD

**Issue by aaronolds** [aws/aws-sdk-net#2589]
### Describe the bug

When calling the EnvironmentVariableAWSRegion, the code is only looking at AWS_REGION it should also look at AWS_DEFAULT_REGION as well.

### Expected Behavior

The code should look at both environment variables AWS_DEFAULT_REGION and AWS_REGION

### Current Behavior

The code only looks at AWS_REGION environment variable

### Reproduction Steps

Remove AWS_REGION environment variable and add AWS_DEFAULT_REGION environment variable.  Then try to instantiate an AmazonServiceClient.

### Possible Solution

If the AWS_REGION environment variable is not set check the AWS_DEFAULT_REGION environment variable before throwing exception.

### AWS .NET SDK and/or Package version used

AWSSDK.Core -Version 3.7.106.24

### Targeted .NET Platform

.NET 6, .NET 7

### Operating System and version

ALL

**Comment by ashishdhingra** [comment]
Per [Environment variables to configure the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html), `AWS_DEFAULT_REGION` identifies the AWS Region whose servers you want to send your requests to by default.

The constant `ENVIRONMENT_VARIABLE_DEFAULT_REGION` was added in commit https://github.com/aws/aws-sdk-net/commit/3d41f4bdec4d3fab0b2ad804fedb945b5e051364 as part of adding support for Default Configuration Modes. This needs review with the team since the utility class [EnvironmentVariableAWSRegion](https://github.com/aws/aws-sdk-net/blob/47433ba029bdd2821d9e8091eb2b4c1490ce113e/sdk/src/Core/Amazon.Runtime/AWSRegion.cs#L72) hasn't changed in years and the new constant was introduced when adding support for default configuration mode. Needs review with the team.

**Comment by dscpinheiro** [comment]
Hi @aaronolds, I'm going to resolve this as not planned. 

`AWS_DEFAULT_REGION` is a variable the previous version of the CLI (V1) used, but all other SDKs have standardized on using `AWS_REGION` instead: https://docs.aws.amazon.com/sdkref/latest/guide/feature-region.html (including the CLI V2: `AWS CLI v2 uses any value in AWS_REGION before any value in AWS_DEFAULT_REGION`).
