### ISSUE TITLE
TokenRefresh callback for AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by pergardebrink** [aws/aws-sdk-net#2601]
### Describe the feature

Add a callback method to AssumeRoleWithWebIdentity that can be used to provide a fresh token, both on first request as well as when the credential is expiring and needs to be refreshed.

### Use Case

I want to fetch a new token from my IdP when the credential is about to expire. The current AssumeRoleWithWebIdentity credential accepts either a token (cannot be refreshed later), or a filepath containing a token. 

When the token expires, there's no callback method I can provide to get a new token from my IdP, unless I write the token to the webIdentityTokenFile, which feels like a weird workaround.

### Proposed Solution

Implement a "token fetcher", similar to how the Go AWS SDK does it: https://github.com/aws/aws-sdk-go/blob/c741f7708a53e32659fc0fdd4c039966f64eb26a/aws/credentials/stscreds/web_identity_provider.go#L102

For example, implemented using a delegate or Func<string> or similar.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

3.7.106.34

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows/Linux

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by ashishdhingra** [comment]
We probably need a callback mechanism in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleWithWebIdentityCredentialsOptions.cs, similar to what we have in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentialsOptions.cs.

**Comment by aslatter** [comment]
My use-case for requesting something like this is that I will be obtaining my OIDC token via an API call in the same program as I'm making calls to AWS.

Specifically, my service has a Microsoft Entra identity with their version of temporary credentials, and I would like to exchange those temporary Entra credentials for temporary AWS IAM credentials. Managing this via refreshing a temp-file is awkward.

If there were a version of `AssumeRoleWithWebIdentityCredentials` which took a web-identity-credential-callback instead of a filename this would be much simpler to construct on my end.

**Comment by gabeluci** [comment]
Shame this was close. I need this exact thing. Sounds like I'll have to roll my own.
