### ISSUE TITLE
Support S3 Unity Editor Integration

### ISSUE THREAD

**Issue by doubleday** [aws/aws-sdk-net#261]
In order to allow easy uploading of asset to cdn I'm trying to integrate S3 support into the unity3d (http://unity3d.com/) editor.

Unfortunately unity is mono / 3.5 and it seems that the HttpResponse object reacts differently on Dispose than its supposed to.

That's whats happening:

```
ObjectDisposedException: The object was used after being disposed. 
System.Net.HttpWebResponse.CheckDisposed () 
System.Net.HttpWebResponse.GetResponseHeader (System.String headerName) 
(wrapper remoting-invoke-with-check) System.Net.HttpWebResponse:GetResponseHeader (string) 
Amazon.Runtime.Internal.Transform.HttpWebRequestResponseData.GetHeaderValue (System.String name) 
Amazon.S3.Internal.AmazonS3ResponseHandler.HasSSEHeaders (IWebResponseData webResponseData) 
Amazon.S3.Internal.AmazonS3ResponseHandler.ProcessResponseHandlers (IExecutionContext executionContext) 
Amazon.S3.Internal.AmazonS3ResponseHandler.PostInvoke (IExecutionContext executionContext) 
Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync (IExecutionContext executionContext) 
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (IExecutionContext executionContext) 
Amazon.Runtime.Internal.ErrorHandler.InvokeSync (IExecutionContext executionContext) 
UnityEngine.EventSystems.EventSystem:Update()
```

The `HttpHandler` invoke methods dispose the response. This makes the subsequent `AmazonS3ResponseHandler` invoke fail when accessing the response object.

My 'quick fix' which is of course not a fix is simply not disposing the response object. Then the integration in unity works fine. So if you see any chance of fixing this the right way like postponing the disposing to a PostInvoke method or something like that it would be actually possible to use the 3.5 version of the framework in unity.

**Comment by gokarnm** [comment]
The version of the SDK that targets .NET 3.5 and 4.5 are not supported on Unity. Have you checked the [AWS Mobile SDK for Unity](http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/)? This SDK is built specifically for Unity.

**Comment by doubleday** [comment]
Yes I understand - but I understand that the mobile sdk is aimed to be used as an access lib from within a game to download assets from s3. That's not want I want.

My aim is to upload / synchronise assets that are created in the asset pipeline. So it's only used from within the editor / authoring environment. For using those assets in the game I don't need any sdk. I just download them. 

But I understand that you don't want to officially support unity in the standard sdk. I can live with my workaround so that's fine. I just thought that since the 'only' problem using the 3.5 version of the lib in the editor is the early disposing of the response object I give it a shot and open a ticket since other people wanted to use this as well. see here: http://stackoverflow.com/questions/30755452/objectdisposedexception-on-aws-listbuckets-call-in-unity3d

Lets just hope that unity supports a proper .net version soon.

**Comment by gokarnm** [comment]
Are you commenting out this [line](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Unmarshaller.cs#L195)? This code eventually calls [HttpWebResponse.Close()](https://msdn.microsoft.com/en-us/library/system.net.httpwebresponse.close%28v=vs.110%29.aspx). If you skip this, you may have issues with connections not being released.

Even though the reported issue does not cause any exceptions on .NET 3.5, the current implementation is incorrect where it's possible to use a disposed instance of HttpResponse to [retrieve a header value](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Transform/_bcl/HttpWebRequestResponseData.cs#L73). I'll make a fix where it loads up the header keys and values in the [constructor](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Transform/_bcl/HttpWebRequestResponseData.cs#L31) for HttpWebRequestResponseData instead of lazily loading it. I'll let you know when this fix is available.

Do note that we do not build or test this version of the SDK against the mono version used by Unity.

**Comment by doubleday** [comment]
Thanks! Almost it's actually [this one](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Unmarshaller.cs#L155).

I'm aware of the resource leak but hoped to get away with it since the underlying connection will be either keep alive or closed automatically so I should not run into a socket problem. Of course I would not do this in a long running server app :-) But this is really 'only' a desktop utility and sadly unity is not the most solid thing out there so people are used to the pain.

I understand that you are not testing against the mono versions and don't expect you to! And most of all from my understanding your fix *will* fix my problem so yes please ping when you have something!

Thanks!

**Comment by gokarnm** [comment]
The latest version of AWSSDK.Core (3.1.3.4) package contains a fix to this issue.

 How are you consuming the SDK binaries (installer/nuget)? Because this change does not affect any of the service packages, we have not incremented the minimum version in the service packages for the Core dependency. If you are consuming the binaries through NuGet you would have to explicitly pick this version of Core package.
