### ISSUE TITLE
Amazon.Runtime.ConstantClass thread-safety bug

### ISSUE THREAD

**Issue by GSPP** [aws/aws-sdk-net#303]
`staticFields` is being written to under a lock but it is being read without holding that lock. That's not allowed because `Dictionary` does not support reads with concurrent writes.

Using `ConcurrentDictionary` and removing that lock should work.

**Comment by PavelSafronov** [comment]
You are correct, reads are done without locks, which can result in ```ContainsKey``` returning ```false``` when indeed that key exists in the dictionary. However, in that case ```LoadFields``` will be called, which will end up making a ```ContainsKey``` and an locked ```ContainsKey``` call. In all, that will amount to an extra ```lock``` call and two extra ```ContainsKey``` calls when two or more threads are using new constant values. Call this *Case A*.
The use of ```ConcurrentDictionary```, which we will call *Case B*, will add the overhead of a ```lock``` call to each read.

Since the constant values are cached and it's unlikely for new constants to be frequently added, *Case A* will occur very infrequently. On the other hand, look-up for *Case B* can happen very often, as the ```FindValue``` method is called whenever the SDK implicitly converts ```String``` types to ```ConstantClass``` types. Depending on how the SDK is used, this can happen *very* often, across any number of threads.

All that being said, I don't believe there is an issue with the current code, and the current implementation is better and more performant than using ```ConcurrentDictionary```. If you feel that this is not the case, please feel free to correct me.

**Comment by GSPP** [comment]
Dictionary simply does not support reads in the presence of concurrent writes. The behavior is not guaranteed in that case. By accident it's working fine right now but it might not in the future, or break very rarely.

If you want a practical scenario how this could happen: The write could trigger a resize causing the read to see inconsistent internal state.

But that scenario should even be necessary to convince you since *all code* is thread-unsafe if not documented otherwise. Dictionary does not document that you are allowed to do this.

**Comment by PavelSafronov** [comment]
Thanks for the follow-up. ```ConcurrentDictionary``` is not available on all the platforms that the SDK supports, so we are looking at a different approach to this thread safety issue.

**Comment by GSPP** [comment]
If writes are rare you could create an entirely new dictionary and CAS that into place using `Interlocked.Exchange`. That way there is zero penalty for reads but writes are expensive (O(N)).

**Comment by PavelSafronov** [comment]
We've updated the ConstantClass code to remove this vulnerability. Thank you for bringing this to our attention and helping understand the issue.
