### ISSUE TITLE
Allow x-amz-tagging-directive to be null on CopyObject

### ISSUE THREAD

**Issue by Elantrus** [aws/aws-sdk-net#3125]
### Describe the feature

A way to let 'x-amz-tagging-directive' not be used in request headers. This header is always being set on CopyObject according to
CopyObjectRequestMarshaller : 77 
```csharp

if (copyObjectRequest.IsSetTagSet())
            {
                request.Headers.Add(S3Constants.AmzHeaderTagging, AmazonS3Util.TagSetToQueryString(copyObjectRequest.TagSet));
                request.Headers.Add(S3Constants.AmzHeaderTaggingDirective, TaggingDirective.REPLACE.Value);
            }
            else
            {
                request.Headers.Add(S3Constants.AmzHeaderTaggingDirective, TaggingDirective.COPY.Value);
            }
```

### Use Case

The header '**x-amz-tagging-directive**' is always being set. But some service like Cloudflare R2 doesn't have an implementation for it yet, then the request fail. According to S3 Documentation:

[API_CopyObject](https://docs.aws.amazon.com/pt_br/AmazonS3/latest/userguide/object-tagging.html)
`When you don't set the x-amz-tagging-directive header and the source object has non-empty tags. This is because the default value of x-amz-tagging-directive is COPY.`

### Proposed Solution

Remove the else from CopyObjectRequestMarshaller : 82

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWS SDK 3.7.303

### Targeted .NET Platform

.NET8

### Operating System and version

Linux

**Comment by ashovlin** [comment]
Re-opening, we noticed via an internal ticket that this may be an obstacle when copying an object with tags from a general purpose bucket to a directory bucket when using S3 Express One Zone.

From https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestBody
> Directory buckets - For directory buckets in a CopyObject operation, only the empty tag-set is supported. Any requests that attempt to write non-empty tags into directory buckets will receive a 501 Not Implemented status code. 

The following scenarios should be supported when copying from either a general purpose or directory bucket to a directory bucket, and clearing the tags.
> When you attempt to REPLACE the tag-set of a directory bucket source object and set the x-amz-tagging value of the directory bucket destination object to empty.
> When you attempt to REPLACE the tag-set of a general purpose bucket source object that has non-empty tags and set the x-amz-tagging value of the directory bucket destination object to empty.

However because the .NET SDK does not currently let you set `REPLACE` alongside an empty tag-set, it's challenging to copy an object that has tags originally. I think we ought to expose `x-amz-tagging-directive` independently.

**Comment by dscpinheiro** [comment]
Resolving as the latest preview version of the S3 package (https://www.nuget.org/packages/AWSSDK.S3/4.0.0-preview.3) allows `TaggingDirective` to be set by customers when copying objects.
