### ISSUE TITLE
Validation error when using S3StorageClass constants

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#321]
This is an inconsistency in the SDK I found, I don't know what your policy on this sort of thing is but figured its best to raise it and let you decide.

When creating a Pipeline for Elastic Transcoder:

```
Client.CreatePipeline(new CreatePipelineRequest
            {
                *snip*
                ContentConfig = new PipelineOutputConfig
                {
                    Bucket = bucket,
                    StorageClass = S3StorageClass.Standard
                },
                ThumbnailConfig = new PipelineOutputConfig
                {
                    Bucket = bucket,
                    StorageClass = S3StorageClass.Standard
                }
            })
```

I opted for using the S3 SDK's constants for the storage class. 

This results in a validation exception:

> {"2 validation errors detected: Value 'STANDARD' at 'thumbnailConfig.storageClass' failed to satisfy constraint: Member must satisfy regular expression pattern: (^ReducedRedundancy$)|(^Standard$); Value 'STANDARD' at 'contentConfig.storageClass' failed to satisfy constraint: Member must satisfy regular expression pattern: (^ReducedRedundancy$)|(^Standard$)"}

Since the constant uses `STANDARD` while the Elastic Transcoder api expects `Standard`

**Comment by PavelSafronov** [comment]
```S3StorageClass``` is an object which is mostly used in S3, and should not be used with the ```StorageClass``` fields in Elastic Transcoder, which are strings and have different limitations on them. The [documentation](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/ElasticTranscoder/Generated/Model/PipelineOutputConfig.cs#L102-L110) on the field calls out what values are supported.

You are able to use ```S3StorageClass``` as shown above, but that is because there is an implicit conversion which converts the object to a string. Sorry about the confusion.

**Comment by phillip-haydon** [comment]
Ahh ok, good to know, when I looked at the definition it looked different so assumed it was constants. 

Will close this as its a non issue.
