### ISSUE TITLE
AWSSDK.S3 3.7.307.4 escapes colon in bucket name in GetPreSignedURL

### ISSUE THREAD

**Issue by desdoades** [aws/aws-sdk-net#3239]
### Describe the bug

We use ceph S3 where bucket names are not a subdomain but after the domain, e.g. https://example.com/11213ef55:mybucket/path/to/file.jpg.
When using AWSSDK.S3 3.7.307.4 it percent-encodes a colon in the bucket name (which is a valid character in an URL path) when calling GetPreSignedURL(request).
This breaks the upload to our S3 file host since it can not match to the correct bucket.

Can this be fixed on your end or would you say thats a problem of the ceph S3?

### Expected Behavior

We are currently on AWSSDK 3.7.103.13 where it does not percent-encode a colon in the bucket name.
In this version the file upload to S3 works.

### Current Behavior

Because of the colon percent-encode the s3 ceph file server returns a 

> Forbidden <Error><Code>AccessDenied</Code>...
when trying to upload a file to the pre signed URL.

### Reproduction Steps

That should not be neccessary

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.307.4

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@desdoades Good morning. Thanks for reporting the issue. Could you please share if you are using AWS S3 service or simulated service that mimics S3?

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Need reproduction with actual AWS S3 service.

**Comment by ashishdhingra** [comment]
@desdoades Good afternoon. Please confirm if your bucket is named `11213ef55:mybucket`. AWS S3 console doesn't allow `:` (colon) character in bucket name. I'm unsure how CEPH S3 service is allowing it. So it appears be an issue with CEPH S3 side, not SDK side since `:` is not a valid character in bucket name.

Thanks,
Ashish

**Comment by desdoades** [comment]
Dear @ashishdhingra, 

we are not using AWS S3 but netways S3 which uses ceph. As I said it does not have the bucketname in the subdomain but in the path. 
Our actual bucket is not named `11213ef55:mybucket` but very similar, so it does contain a colon.

**Comment by ashishdhingra** [comment]
> Dear @ashishdhingra,
> 
> we are not using AWS S3 but netways S3 which uses ceph. As I said it does not have the bucketname in the subdomain but in the path. Our actual bucket is not named `11213ef55:mybucket` but very similar, so it does contain a colon.

@desdoades Thanks for the reply. As mentioned in my previous comment, colon `:` character is not supported in AWS bucket names. The colon `:` is a reserved character in a URL and it has a special meaning in identifying the protocol used in the URL (http:, https:, ftp: etc.). However, you can still add a colon in other parts of a URL by using URL encoding. URL encoding is a process of converting reserved characters into their corresponding hexadecimal code so that they can be safely transmitted over the internet.

Please contact Ceph S3 support to handle this character at their end (this may be as simple as decoding the URL before processing various segments).

Thanks,
Ashish

**Comment by desdoades** [comment]
Dear @ashishdhingra,

While AWS might not support them many site allow colons in the URL.
Still thank you, I understand you wont do anything about it. I will try to reach our ceph S3 support.

**Comment by nickeeex** [comment]
If anyone else runs into this issue, here is a work around

```csharp
    public class CustomAmazonS3Client : AmazonS3Client
    {
        public CustomAmazonS3Client(AWSCredentials creds, AmazonS3Config config) : base(creds, config)
        {
        }

        protected override void CustomizeRuntimePipeline(RuntimePipeline pipeline)
        {
            base.CustomizeRuntimePipeline(pipeline);
            pipeline.AddHandlerAfter<AmazonS3EndpointResolver>(new ColonDecoderHandler());
        }
    }

    public class ColonDecoderHandler : PipelineHandler
    {
        public override async Task<T> InvokeAsync<T>(IExecutionContext executionContext)
        {
            DecodeColon(executionContext);

            return await base.InvokeAsync<T>(executionContext);
        }

        private void DecodeColon(IExecutionContext executionContext)
        {
            var request = executionContext.RequestContext.Request;
            var originalPath = request.Endpoint.AbsolutePath;

            // Ceph based S3 requires tenant:bucketname format, which is not supported by AmazonS3Client as it encodes it to tenant%3Abucketname format.
            // This causes ceph to not recognize the bucket name and return 403 for no access.
            if (originalPath.Contains("%3A"))
            {
                var fixedUri = new UriBuilder(request.Endpoint)
                {
                    Path = originalPath.Replace("%3A", ":")
                }.Uri;
                request.Endpoint = fixedUri;
            }
        }
    }
```
