### ISSUE TITLE
Unity WebGL support

### ISSUE THREAD

**Issue by AlexVK79** [aws/aws-sdk-net#326]
Really need it ASAP.

There is already "Unity - Webgl Support" item in FEATURE_REQUESTS.md,
but it links to https://github.com/aws/aws-sdk-unity/issues/50
which is a - 404 page not found.

So there is really no information on progression or problems with this feature.

As long as SDK is pure C# what is the problem with WebGL target considering
iOS (IL2CPP) is supported?

Thanks!

**Comment by karthiksaligrama** [comment]
@AlexVK79 your feedback is appreciated on the webgl, in the meantime we are happy to accept pull requests.

The link that is present on the FEATURE_REQUEST.md points to the issue on our older git repo which is no longer maintained. I'll update the link to the current issue.

**Comment by Half** [comment]
I'm waiting for the WebGL support too.

I made a couple of changes in the SDK to support Amazon Cognito (credentials, datasets, sync) and generic Async request (only tested for Dynamo) for WebGL.
The high level API for Dynamo is too complex to be patched.

The main issue was WebGL didn't support Threads (lock, WaitHandle, ThreadPool, ...) and synchronous request.

I had to remove any call to "InvokeSync" and use only one thread (main thread).
This implies to add callbacks in a lot of methods, remove call to others threads and only use the *ASync methods.

The codebase became messy that's why I can't make a pull request here. If you want a version of my updated version PM me.

Also I tried to compile the SDK for Windows Universal 10 with IL2CPP (.NET is not compatible due to the lack of System..... namespace used in the SDK).
It worked well for Cognito (credentials, dataset, sync) , I didn't test the other services.

**Comment by PavelSafronov** [comment]
If you have a working codebase, consider uploading that as a GitHub repo and linking it here. That will help us or a community member to get started on this work.

This issue was added to FEATURE_REQUESTS.md, closing it. Feel free to comment, of course.

**Comment by Deathwing** [comment]
Hey guys, I added a pull request for unity WebGL. It is not covering every aspect, but I think it is at least a beginning on which we can build :)

https://github.com/aws/aws-sdk-net/pull/898

**Comment by adambielecki** [comment]
Any progress with that feature?

**Comment by BatteryAcid** [comment]
Any updates on supporting this feature request?  Or does anyone know of a shim to get this to work?  thanks

**Comment by lagatun54** [comment]
up
