### ISSUE TITLE
TransferUtility is missing from 3.2.3-beta for dotnetcore

### ISSUE THREAD

**Issue by bryanroscoe** [aws/aws-sdk-net#339]
When updating our AWS S3 library version to 3.2.3-beta I noticed that `Amazon.S3.Transfer` is missing, which includes the TransferUtility. Was this intentional? Will it be re added soon or is this change permanent?

**Comment by normj** [comment]
It was not intentional and I'll be adding it back in.

**Comment by bryanroscoe** [comment]
Ok, thanks is a new versions expected soon?

I also noticed the EC2Metadata utility class is missing in dot net core as well.

**Comment by normj** [comment]
I'm working on a patch release now for getting TransferUtility. So fingers crossed I should have that released today or tomorrow.

EC2Metadata will probably be out for awhile because it is based on System.Net.HttpWebRequest which isn't available CoreCLR. We have a few utility classes like this in the SDK that uses the HttpWebRequest directly so we had to remove them out of the CoreCLR version. We need to work on a common abstraction between System.Net.HttpWebRequest and System.Net.Http.HttpClient that our utility classes can use and then we can add back the utility classes.

TransferUtility wraps the AmazonS3Client the low level service client and our service clients do have an abstraction around the different HTTP clients.

**Comment by bryanroscoe** [comment]
Thanks for the prompt response on this.

One more thing I noticed that we use that was also missing from S3 was the `GetPreSignedURL` function.

**Comment by normj** [comment]
I just pushed version 3.2.3.1 to NuGet which adds TransferUtility and GetPreSignedURL to the CoreCLR version of the SDK.

**Comment by bryanroscoe** [comment]
Awesome, thanks! Everything seems to be working for us now.
