### ISSUE TITLE
Bug: Aws Explorer - SNS - Creating a Topic whilst the endpoint is down creates an undeletable topic that doesnt' poll subscription endpoiont

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#350]
Step:
1) in Aws Explorer | Amazon SNSCreate a topic with an endpoint that is not currently up
2) Make the endpoint live (start iis)
The endpoint 'ConfirmSubscription'  method is not invoked
The Subscription ID says "PendingConfirmation"
3) Try to click Delete Subscription.  in order to recreate
This is disallowed an error message dialog is shown.

A workaround is to click 'Create New Subscription ', create a new Topic with the same endpoint, which then works, overwriting the one that you have currently created and the ConfirmSubscription method is then invoked.
So although it is not possible to delete  the initial topic through the gui, it gets overwritten by creation of a new one with the same endpoint url.

**Comment by normj** [comment]
The error that is returned when you attempted to delete the subscription is coming from the SNS service. The SNS service does not allow you to delete pending confirmation subscriptions. The toolkit can't do anything more then the service allows. I'd suggest you bring this up in the SNS forums so that team gets the visibility of this pain point.

**Comment by damiangreen** [comment]
thanks for your feedback
