### ISSUE TITLE
The types in the ThirdParty namespace are externally visible

### ISSUE THREAD

**Issue by AnthonyMastrean** [aws/aws-sdk-net#3515]
### Describe the bug

The types in the [`ThirdParty`](https://github.com/aws/aws-sdk-net/tree/main/sdk/src/Core/ThirdParty) namespace are externally visible.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I should not see these types exposed in some utility namespace.

### Current Behavior

I see these types exposed in some utility namespace.

### Reproduction Steps

Install the package, use a type that can be resolved from multiple packages/namespaces (such as `JsonException`) and note that `ThirdParty` shows up in the list of possible imports.

### Possible Solution

Mark these types `internal`.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.400.35

### Targeted .NET Platform

.NET 8

### Operating System and version

All platforms

**Comment by ashishdhingra** [comment]
@AnthonyMastrean Good morning. Thanks for opening the issue. While it makes sense to mark them as `internal`, however, doing so in current version of SDK would be a breaking change for existing customers that might be using these public members. This needs review with the team if these could be marked them as `internal` in new major version `v4` in development.

Thanks,
Ashish

**Comment by normj** [comment]
I understand your concern but it is something we can not do, at least without more effort then we can spend on it. There are cases where the services packages like `AWSSDK.EC2` need to access to the code in `ThirdParty`. We can't rely on the `InternalsVisibleToAttribute` attribute because sometimes the service package is being used with a version `AWSSDK.Core` that didn't exist when the service package was created.
