### ISSUE TITLE
SendEmailAsync does not document AmazonSimpleEmailServiceV2Exception

### ISSUE THREAD

**Issue by lonix1** [aws/aws-sdk-net#3550]
### Describe the issue

I'm using SES v2.

I used `SendEmailAsync` with an identity that has a default configuration set. The policy was not correct and so prevented my app from sending the mail:

This exception was thrown: `AmazonSimpleEmailServiceV2Exception`:
> Amazon.SimpleEmailV2.AmazonSimpleEmailServiceV2Exception: User 'arn:aws:iam::000000000000:user/foo' is not authorized to perform 'ses:SendEmail' on resource `arn:aws:ses:region:000000000000:configuration-set/bar'

That exception is not documented - neither in the [API docs](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/MSimpleEmailServiceV2SendEmailAsyncSendEmailRequestCancellationToken.html) nor in the [doc-comments](https://github.com/aws/aws-sdk-net/blob/939ed2c7a124425b40de1de7e1deb277c050e171/sdk/src/Services/SimpleEmailV2/Generated/_netstandard/AmazonSimpleEmailServiceV2Client.cs#L4352) that show in my IDE.

### Links

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/MSimpleEmailServiceV2SendEmailAsyncSendEmailRequestCancellationToken.html

**Comment by ashishdhingra** [comment]
@lonix1 Good morning. The mentioned exception is thrown by the incorrect policy configuration per your issue description. It is the IAM issue, not SES issue. In fact any service would throw this exception if the IAM policy does not allow a role or service to invoke certain service API operations. Hence, such exceptions are not documented in specific service (in this case SES) API page. The page [SESv2 > Common Errors](https://docs.aws.amazon.com/ses/latest/APIReference-V2/CommonErrors.html) lists the errors common to the API actions of all AWS services. It specifically states that `For errors specific to an API action for this service, see the topic for that API action.`. The AWS .NET SDK (or any other language SDK) and it's respective service API documentation are generated from models shared by AWS services (refer [here](https://github.com/aws/aws-sdk-net/tree/main/generator/ServiceModels)).

In your use case, policy was misconfigured and hence it caused IAM exception which is returned as `AmazonSimpleEmailServiceV2Exception` since you are invoking SESv2 API operation.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
@lonix1 Tysnks for the suggestions. For specific error wrapped by `AmazonSimpleEmailServiceV2Exception`, you may inspect `InnerException` property.

Regarding documentation issue, all SDK(s) rely on service models (not just .NET SDK). Until and unless there is some information in these models to include common exceptions, it's not feasible to have these linked from API reference pages. I would discuss with relevant teams on how to further improve documentation as you suggested.

Thanks,
Ashish
