### ISSUE TITLE
StaticValue constructor not returning nullable DateTime

### ISSUE THREAD

**Issue by colmkavs** [aws/aws-sdk-net#3582]
### Describe the bug
https://github.com/aws/aws-sdk-net/blob/37492aabe9e9bab68f5ed548eb444ea75b405181/sdk/src/Services/QuickSight/Generated/Model/TimeRangeFilterValue.cs#L90

AWSSDK.QuickSight
TimeRangeFilterValue.StaticValue

When retrieving the object via the SDK, the constructor is not returning a nullable DateTime. It gets initialized as new DateTime() and if you have set the RollingDate property also, then a validation error is returned when using the object in CreateDashboardAsync()

`_{"4 validation errors detected: Value 'TimeRangeFilterValue(staticValue=Mon Jan 03 00:00:00 UTC 1, rollingDate=RollingDateConfiguration(dataSetIdentifier=null, expression=*** REDACTED ***), parameter=null)' at 'definition.filterGroups.11.member.filters.1.member.timeRangeFilter.rangeMaximumValue' failed to satisfy constraint: Only 1 member of [staticValue, rollingDate, parameter] should be provided for structure TimeRangeFilterValue; Value 'TimeRangeFilterValue(staticValue=Mon Jan 03 00:00:00 UTC 1, rollingDate=RollingDateConfiguration(dataSetIdentifier=null, expression=*** REDACTED ***), parameter=null)' at_ `

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

A Nullable DateTime value is allowed

### Current Behavior

Initialised as a new DateTime

### Reproduction Steps

Create the Dashboard via the CLI or UI with a rollingDateTime filter configured

Retrieve the Dashboard via the SDK `DescribeDashboardDefinitionAsync`
Publish the Dasboard (change its name to pass naming validation) using `CreateDashboardAsync`
Catch Validation Error Exception

### AWS .NET SDK and/or Package version used

AWSSDK.QuickSight 3.7.411.5

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows

**Comment by ashishdhingra** [comment]
@colmkavs Good morning. Thanks for opening the issue. You are perhaps affected by the side effect of AWS SDK for .NET `v3` where such properties, although having `Nullable` backing field, always return `GetValueOrDefault()`. This behavior would be fixed in next major version `v4` of AWS .NET SDK (which is currently in preview), please check code [here](https://github.com/aws/aws-sdk-net/blob/af13bc7b96c39fca3d070a2370d1bca8ba2f042d/sdk/src/Services/QuickSight/Generated/Model/TimeRangeFilterValue.cs#L90).

Thanks,
Ashish

**Comment by colmkavs** [comment]
Thank you @ashishdhingra the v4 generated models have it addressed.
