### ISSUE TITLE
How do I get or set the max connection limit for dynamodb - for dnx/dotnet core?

### ISSUE THREAD

**Issue by bilal-fazlani** [aws/aws-sdk-net#362]
The current limit seems to be very low. and my web application is slowing down because of it. It has become a bottleneck.

What is the current limit ?
How can I modify it ?

**Comment by bilal-fazlani** [comment]
@normj

**Comment by bilal-fazlani** [comment]
Here: https://github.com/aws/aws-sdk-net/blob/c04da99b43ebe6c918d6cb46be9414d34a9cca01/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L46

I can see that its 50. and it's not accessible to me. 
Can I submit a pull request that has a public getter and setter around this property ?

**Comment by bilal-fazlani** [comment]
I can see this method 

```c#
        internal static int GetConnectionLimit(int? clientConfigValue)
        {
            if (clientConfigValue.HasValue)
                return clientConfigValue.Value;

            return AWSSDKUtils.DefaultConnectionLimit;
        }
```

but no references of it.

**Comment by vellozzi** [comment]
Have you been able to fix this problem?  If not, can you give some details on how you diagnosed the issue?

**Comment by vellozzi** [comment]
In .NET 3.5/4.5 that value makes its way into HttpWebRequest.ServicePoint.ConnectionLimit here: https://github.com/aws/aws-sdk-net/blob/37b2546044248de151a6ce47641ba096728fb5cb/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_bcl/HttpWebRequestFactory.cs#L368

In .NET Core we would set HttpClientHandler.MaxConnectionsPerServer here: https://github.com/aws/aws-sdk-net/blob/d22d603e39f6125a851fe245cb36baa09c3491ef/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L176, except the default value for that property is int.MaxValue.

That's why I'm interested to see how you diagnosed /fixed this issue.  I'm not able to find how that limit would be imposed in .NET Core.

**Comment by vellozzi** [comment]
IClientConfig.MaxConnectionsPerServer was added for .NET Core in SDK Version 3.3.84.1, NuGet package AWSSDK.Core version 3.3.13.4.

From your description this still may not solve your problem.  Please reopen this issue if you're still seeing the same problem.
