### ISSUE TITLE
`ProfileManager.GetAWSCredentials()` not working with `.aws/credentials` files

### ISSUE THREAD

**Issue by eiriktsarpalis** [aws/aws-sdk-net#363]
Quoting from #358:

I neglected to mention that fetching credentials does not work either, even with the credential file in-place:
```csharp
Amazon.Util.ProfileManager.GetAWSCredentials("default");
```
results in
```
Amazon.Runtime.AmazonClientException: A profile named default has not been registered or contains invalid data.
   at Amazon.Util.ProfileManager.GetAWSCredentials (System.String profileName) <0x6cb9910 + 0x000df> in <filename unknown>:0 
```
I believe that my credentials file is set up properly since the aws cli seems to be working fine.

**Comment by steveataws** [comment]
Is the credential file located in what the SDK considers the default location (c:\users\userid\.aws) and using default name ("credentials")?

**Comment by eiriktsarpalis** [comment]
Yes, it's located in `~/.aws/credentials`. It must be right since awscli
recognizes it.

**Comment by steveataws** [comment]
My bad, I should have spotted you were using the wrong class. The ProfileManager as it stands today only supports the encrypted .NET-specific credential file (c:\users\userid\AppData\Local\AWSToolkit\RegisteredAccounts.json). It does not support reading credentials from the plain-text credentials file shared with other AWS SDKs and tools.

If you need to explicitly load credentials from the shared file use the StoredProfileAWSCredentials class; it will search the .NET-specific file first before then searching the shared credential file. It has additional constructor overloads that allow you to specify that it should search the shared file only by passing the location of the credential file. For example:

```csharp
// searches both .NET specific and then shared credential files
using Amazon.Runtime;
...
var creds = new StoredProfileAWSCredentials("default");
Console.WriteLine(creds.GetCredentials().AccessKey);

// searches only the shared credential file (in default location)
using Amazon.Runtime;
...
var creds = new StoredProfileAWSCredentials("default", StoredProfileCredentials.DefaultSharedCredentialLocation);
Console.WriteLine(creds.GetCredentials().AccessKey);
```
You might however find it easier to simply specify the profile name in appsettings in your app.config or web.config files, and let the SDK take care of finding and loading the profile data. Also, since the profile name is 'default', the SDK will automatically search for a corresponding profile (in both credential files) if no other profile is requested so you can even omit that and just instantiate whatever client(s) you need:

```csharp
// searches for profile named 'default' in .NET-specific and shared credential files
// to supply credentials to the client instance
var ec2Client = new Amazon.EC2.AmazonEC2Client(RegionEndpoint.USWest2);
```
