### ISSUE TITLE
SubscribeQueue available for .net core

### ISSUE THREAD

**Issue by Edu115** [aws/aws-sdk-net#368]
I see that, along with the (announced) deprecation of sync methods for AWS service calls, specifically within the SQS service the SubscribeQueue method is not available for .net core, and as far as I could see, there are no other alternatives.

Is there a strong reason why this isn't supported? And can we expect it to be supported in the near future?

**Comment by normj** [comment]
Sync methods aren't deprecated and will continue exist in the main .NET 3.5 and 4.5 version of the SDK. The .net core version of the SDK is based around System.Net.Http.HttpClient which only suports async calls which is why that version of the SDK only exposes async calls. The .NET 3.5 and 4.5 version of the SDK are build around HttpWebRequest which supports both sync and async in .NET 3.5 and 4.5 but in .net core HttpWebRequest has greatly reduced functionality.


SubscribeQueue is a utility method we added to the SDK and is not an actual service method. There are many of these utility methods that are missing in the .net core version because of the async only nature but we are looking into reworking them so we can add them back. It is our intention of getting most of the utility classes and methods available in the .net core version.

**Comment by Edu115** [comment]
@normj I meant specifically for the .net core version, sorry for the ambiguity. 

Great to know that! We are, for now, just adding our own extension methods that mimics the original ones, but use the async calls.

**Comment by normj** [comment]
Cool, I think what we will do is add a SubscribeQueueAsync eventually that does the same as SubscribeQueue but call the service async methods.

**Comment by normj** [comment]
Closing this as this is part of a great effort we need to do for the .NET Core version to support more of the utility classes in the SDK.
