### ISSUE TITLE
 Submitted policy is over max allowed size 

### ISSUE THREAD

**Issue by dariusdamalakas** [aws/aws-sdk-net#378]
Hi,

Is there a way to control what policy is applied on the queue? [AmazonSimpleNotificationServiceClient.SubscribeQueueToTopics](https://github.com/aws/aws-sdk-net/blob/6c3be79bdafd5bfff1ab0bf5fec17abc66c7b516/sdk/src/Services/SimpleNotificationService/Custom/AmazonSimpleNotificationServiceClient.Extensions.cs#L84
) is applying custom policy which I don't see how to override easily. 

More info here: [JustSaying #211](https://github.com/justeat/JustSaying/issues/211)

Regards

**Comment by dariusdamalakas** [comment]
[ sqsClient.SetAttributes](https://github.com/aws/aws-sdk-net/blob/6c3be79bdafd5bfff1ab0bf5fec17abc66c7b516/sdk/src/Services/SimpleNotificationService/Custom/AmazonSimpleNotificationServiceClient.Extensions.cs#L151) is used to read and then update policy after queue has been subscribed. Is there a way to hook into this somehow?

Also, this does mean each call to `SubscribeQueue` is 3 HTTP calls, and if done in a loop this results in quite a lot of redundant HTTP calls.

**Comment by dariusdamalakas** [comment]
@normj , any ideas?

**Comment by normj** [comment]
This utility method is just to help out the simple case, if you need to manage the policy then you are better off just using the individual service methods.

SubscribeQueueToTopics does 2 things. Add the topic to the policy on the queue and then call subscribe on the topic to the queue. If you want to control how the policy is written then you are better off just calling IAmazonSQS.SetAttributes with the policy you want and then calling IAmazonSimpleNoticationService.Subscribe instead of using this utility method. 

And yes there is a limit on the size of the policy. I'm not sure about the exact size SQS policy but usually they are usually a few  K.
http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html

**Comment by dariusdamalakas** [comment]
@normj thanks, this does make sense. 
It tooks a while to find [Subcribe](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Generated/_bcl45/AmazonSimpleNotificationServiceClient.cs#L2719) method, this whole repository is massive at  `276.81 MiB`, and 300 different projects. 

I didnt realize that SubscribeQueueToTopics is a helper method. Closing this.

**Comment by dariusdamalakas** [comment]
The limits on SQS policy size can be found [here](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/AccessPolicyLanguage_SpecialInfo.html).

@normj any idea if these limits can be increased?

**Comment by normj** [comment]
I'm pretty sure that it is not possible to increase the limits on the policy but you are welcome to ask in the SQS forums to see if somebody from the SQS service can answer the question with more authority.

https://forums.aws.amazon.com/forum.jspa?forumID=12
