### ISSUE TITLE
[AWS Credentials] The retrieved credentials have already expired - Wrong device date/time

### ISSUE THREAD

**Issue by lukeWW** [aws/aws-sdk-net#393]
Hi, we have encountered a problem with the AWS signature. 
We're using the AWS SDK for Unity 2.1.0.1
In some cases we have users whose devices are failing to retrieve the correct credentials and the error is the following:
"The retrieved credentials have already expired ..."

We realized that the problem is due to the wrong date/time set on that devices. 

How can we avoid that, using a wrong date/time on the device the call won’t fail? 
As a quick fix we replaced all references of DateTime.Now and UtcNow in the code with our class, is there any better solution?

**Comment by PavelSafronov** [comment]
PR #427 replaced all the `DateTime.Now` and `DateTime.UtcNow` uses in the SDK with a "corrected" DateTime value, so this issue should not be occurring with the latest version of the SDK.
Resolving.

**Comment by ajithrk** [comment]
Hi,
This issue is still occurring for the latest aws unity sdk (aws-sdk-unity_3.3.131.0). Please advice.

Exception:
Amazon.Runtime.AmazonClientException: The retrieved credentials have already expired: Now = 08/15/2017 16:25:36, Credentials expiration = 07/31/2017 11:55:38
  at Amazon.Runtime.RefreshingAWSCredentials.UpdateToGeneratedCredentials (Amazon.Runtime.CredentialsRefreshState state) [0x00000] in <filename unknown>:0 
  at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials () [0x00000] in <filename unknown>:0 
  at Amazon.Runtime.Internal.Util.SdkCache+CacheKey.Create (Amazon.Runtime.AmazonServiceClient client, System.Object cacheType) [0x00000] in <filename unknown>:0 
  at Amazon.Runtime.Internal.Util.SdkCache.GetCache[String,TableDescription] (Amazon.Runtime.AmazonServiceClient client, System.Object cacheIdentifier, IEqualityComparer`1 keyComparer) [0x00000] in <filename unknown>:0 
  at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo () [0x00000] in <filename unknown>:0 
  at Amazon.DynamoDBv2.DocumentModel.Table.LoadTable (IAmazonDynamoDB ddbClient, Amazon.DynamoDBv2.DocumentModel.TableConfig config) [0x00000] in <filename unknown>:0 
  at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable (System.String tableName) [0x00000] in <filename unknown>:0 
  at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable (Amazon.DynamoDBv2.DataModel.ItemStorageConfig storageConfig, Amazon.DynamoDBv2.DataModel.DynamoDBFlatConfig flatConfig, DynamoDBConsumer consumer) [0x00000] in <filename unknown>:0

**Comment by PavelSafronov** [comment]
The SDK uses a "corrected" time, but only if it knows what the correct time is. The SDK finds out the correct time when you make a service call, the server responds with an error (incorrect time) and provides the SDK with the correct time. It's only after that point that the SDK will know the "correct" time.

It looks like this is the first call and the credentials are not being retrieved from AWS (such as from AWS Security Token Service or Amazon Cognito), so at this point the SDK hasn't made any service calls, and is therefore unware that the time is off.

Where are you retrieving the credentials from? Can you provide your source code?

**Comment by ajithrk** [comment]
Hi, thanks for replying. I am retrieving the credentials by passing the Identity pool string and the region. Attaching the code below. Help me with the correct way of retrieving the credentials and implementing it in the right way.

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using Amazon;
using Amazon.Runtime;
using Amazon.CognitoIdentity;
using Amazon.CognitoIdentity.Model;
using Amazon.CognitoSync;
using Amazon.CognitoSync.SyncManager;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;

using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.DynamoDBv2.Model.Internal.MarshallTransformations;
using Amazon.DynamoDBv2.Model.Internal;
using Amazon.DynamoDBv2.DocumentModel;

public class DynamoDBOperation : MonoBehaviour 
{
	private CognitoAWSCredentials credentials;
	private CognitoSyncManager syncManager;
	private IAmazonDynamoDB _client;
	private DynamoDBContext _context;
	public string cognitoIdentityPoolString;

	private DynamoDBContext Context
	{
		get
		{
			if (_context == null)
				_context = new DynamoDBContext(_client, new DynamoDBContextConfig { Conversion = DynamoDBEntryConversion.V2 });

			return _context;
		}
	}
	private static BatchWrite<DataEntity> DataBatch;
	void Start ()
	{
		UnityInitializer.AttachToGameObject (this.gameObject);
		credentials = new CognitoAWSCredentials (cognitoIdentityPoolString, RegionEndpoint.APSouth1);
		credentials.GetIdentityIdAsync (delegate(AmazonCognitoIdentityResult<string> result) {
			if (result.Exception != null) {
				Debug.LogError ("exception hit: " + result.Exception.Message);
			}
			// Create a DynamoDB client, passing in our credentials from Cognito.
			var ddbClient = new AmazonDynamoDBClient (credentials, RegionEndpoint.APSouth1);
				
			_client = ddbClient;
			LoadDataOP ("abc123");
		});

	}
	void LoadDataOP(string ID)
	{
		DataEntity dataEntity = null;
		Context.LoadAsync<DataEntity> (ID, (result) => {
			if (result.Exception == null) 
			{
				dataEntity = result.Result as DataEntity;
				Debug.Log("No Exception");
			}
			else
			{
				Debug.Log("Load operation failed "+result.Exception);
			}
		});
	}
}

**Comment by Andreyul** [comment]
"Corrected" time was added to provide a way for a game developer to pass to AWS SDK current time from another source (e.g. NTP) without modifying SDK source by setting `AWSConfigs.ManualClockCorrection` property.

**Comment by ajithrk** [comment]
Can you please advice on how to pass current time from another source to AWS SDK?

**Comment by PavelSafronov** [comment]
You can manually configure the time offset that the SDK uses exactly as @Andreyul mentioned:
```
DateTime correctTime = GetNetworkTime();
AWSConfigs.ManualClockCorrection = correctTime.ToUniversalTime() - DateTime.UtcNow;
```

That is assuming that you have a `GetNetworkTime` method that will give you the correct time. [This SO post](https://stackoverflow.com/questions/1193955/how-to-query-an-ntp-server-using-c) contains an implementation of `GetNetworkTime` that I was able to use, though I'm not certain if it will work with Unity, simply because that answer uses some network classes that may not be available on Unity.

If you are not able to use that approach, another approach is to make a failing SDK call at the very start of your application. For example, this snippet uses obviously incorrect credentials to make an AWS call and then sets the correct time.
```
try
{
    using (var client = new AmazonDynamoDBClient("foo", "bar", usEast1Region))
    {
        client.ListTables();
    }
}
catch (Exception e)
{
    Console.WriteLine("swallowing exception {0}", e.Message);
}
```

**Comment by receme** [comment]
@PavelSafronov I have used your first solution and it worked. :)
