### ISSUE TITLE
[SQS] When creating a queue return the QueueArn on the response

### ISSUE THREAD

**Issue by Singh400** [aws/aws-sdk-net#395]
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SQS/TSQSCreateQueueResponse.html

Currently when you create a queue, the above object is returned. I would like the QueueArn also to be returned alongside the QueueUrl.

Many thanks,
Singh

**Comment by PavelSafronov** [comment]
This is service behavior, and not something that the .NET SDK can change.
In order to retrieve the ARN of the queue, you need to call the [GetQueueAttributes](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_GetQueueAttributes.html) operation.
If you would like to suggest this change to the service team, you can post a message on the [SQS forum](https://forums.aws.amazon.com/forum.jspa?forumID=12).
