### ISSUE TITLE
Xamarin: Is SyncManager coming back? 

### ISSUE THREAD

**Issue by cnordvik** [aws/aws-sdk-net#479]
https://github.com/aws/aws-sdk-net/commit/fb93bc6ac3fbc174e80460ff89053b606d51f784

Seems SyncManager was removed? Is it not coming back? We're trying to port our Android code to iOS and really miss the SyncManager...

**Comment by normj** [comment]
You should still see SyncManager it wasn't removed. 

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/CognitoSync/Custom/SyncManager/CognitoSyncManager.cs

What version of the SDK are you using. Are you adding the reference from Visual Studio or Xamarin Studio? What I'm wondering is if the .NET Core version of the SDK is getting picked up instead of the PCL version which is the intended version for Xamarin.

**Comment by ksloginov** [comment]
@normj  we're adding reference through Xamarin Studio.

<img width="817" alt="screen shot 2016-10-31 at 23 43 10" src="https://cloud.githubusercontent.com/assets/1670172/19874200/d2284bfa-9fc3-11e6-9b66-d93bf9d33bec.png">
(selected one)

And this is how our references look like:
<img width="280" alt="screen shot 2016-10-31 at 23 42 37" src="https://cloud.githubusercontent.com/assets/1670172/19874214/ef9c493e-9fc3-11e6-9140-e2c116179abf.png">

And as a result:

<img width="285" alt="screen shot 2016-10-31 at 23 44 35" src="https://cloud.githubusercontent.com/assets/1670172/19874242/1507a600-9fc4-11e6-9c53-a8893d85e06c.png">

So we're sticking to Cognito Sync 3.1.1.0 because of that. Any suggestions?

Thanks a lot

**Comment by ksloginov** [comment]
@normj 

Alongside with the original question, we also have **2 bonus-questions** for you (sorry for overloading same thread - I can move into a new one, if it's needed):

**1)** Here's how we are setting AccessToken in java:
		
```
	setAccessToken("graph.facebook.com", token, context);
	...
        protected static void setAccessToken(String tokenType, String token, final Context context) {
            Logging.debug(TAG, "setAccessToken(tokenType:" + tokenType + ", token:" + token + ")");
            Map<String, String> logins = new HashMap<>();
            logins.put(tokenType, token);
            CognitoCachingCredentialsProvider credentialsProvider = getCognitoCredentialsProvider(context.getApplicationContext());
            credentialsProvider.setLogins(logins);
            credentialsProvider.refresh();
        }
```

Unfortunately, in C# version I can't find:
 `refresh()` method;
 `setLogins()` method;

**What would be adequate replacement for the java-code above?**
===============
**2)** `ResolveWithLastWriterWins` - it exists in java, but doesn't exist in Xamarin version of Cognito. Why? (And how to replace)

Thanks!

**Comment by karthiksaligrama** [comment]
you can take a look at https://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html on how you can federate facebook into cognito identity

**Comment by ksloginov** [comment]
@karthiksaligrama 
Thanks for your reply. In other words question first half of question **1)** can be answered:
`setLogins()` in java => `AddLogin()` in c#, right? What about `refresh()` ?

(And **0)** and **2)**)

**Comment by sstevenkang** [comment]
Hi guys.  We think cda0e0bf39c2810e9a1f01a14a55d47835e252ca should resolve the missing syncmanager problem.  Could you guys update to the latest nuget versions of Core(3.3.5) and CognitoSync(3.3.1.2) and see if the issue persists?

**Comment by ksloginov** [comment]
@sstevenkang Thank you Steven, with latest Core & CognitoSync SyncManager got back. Hurrah!
Out of curiosity, maybe you know something about #488 as well? Thanks 👍

**Comment by sstevenkang** [comment]
Of course!  Thanks for reporting the issue.  This somehow slipped through our radar =P.

**Comment by sstevenkang** [comment]
https://github.com/aws/aws-sdk-net/issues/488 is resolved.  Closing.

**Comment by niraj-bpsoftware** [comment]
CognitoSymcManager is gone again in AWSSDK.CognitoSync 3.3.1.29, AWSSDK Core (3.3.21.20). Is there any other class we are supposed to use now?

**Comment by jaimebg** [comment]
Cannot use CognitoSyncManager in lastest AWSSDK.CognitoSync version (3.5.0.26) in xamarin PCL.

The type or namespace name 'CognitoSyncManager' could not be found (are you missing a using directive or an assembly reference?)
