### ISSUE TITLE
Add synchronous methods back to API

### ISSUE THREAD

**Issue by erick-thompson** [aws/aws-sdk-net#480]
I really like the design and layout of version 3 of the SDK. However, the removal of all synchronous methods is playing havoc with my ability to use it on non-greenfield projects. While I understand that async methods are preferred, can we have the option to use the synchronous methods?

**Comment by sstevenkang** [comment]
Hi Erick.  Is the feature request specifically for .Net Core framework?  The version 3 SDK for .Net 4.5 framework support both async and sync. methods--for the most part.  Is there a specific service that you would like to see support both sync and async?

**Comment by erick-thompson** [comment]
Hey Steven,

Yes, I am talking about .net core. Right now I have a number of .net core projects that build .net core and .net 4.6.2, so I need to use the functionality that is common to both. In terms of specific services, dynamo and SQS are the two big ones for me.

Thanks!

**Comment by normj** [comment]
The reason the .NET Core version only has async is because the underlying http client available in .NET Core only supports async operations. We debated about keeping the sync methods in the .NET Core version and have them just call the async versions and then block. The problem with that is the SDK would not be falling best practice for the platform and it more importantly it could mask a potential performance problem.

**Comment by erick-thompson** [comment]
I understand. I have some applications that involve very long pipelines (LINQ/lambdas/maps/etc) that, if they aren't synchronous, involve me having to write a new TaskScheduler, as the async behavior results in more tasks than the default scheduler can deal with. Thanks for the quick response.

**Comment by normj** [comment]
Closing but appreciate the feedback.

**Comment by Dunge** [comment]
I'm porting my class library using AWSSDK.DynamoDBv2 from net4 to netstandard2.0 in order for it to be used in both net4 and netcore applications and noticed too the lack of sync methods.

The usual reply of "use async all the way down" is enraging because there's call to it from thousands of place everywhere in the project, and less than 1% of them are in an async context. It would be practically impossible to get an async context everywhere I need to launch a DynamoDB query.

I then tried the Task.Run(() => Client.QueryAsync(..)).GetAwaiter().GetResult(); method to call an async method from a synchronous one, but unfortunately it automatically deadlock, presumably because you don't have .ConfigureAwait(false) after all your await calls inside the library.

Is there any way to get this working without rewriting my whole application to keep the async context from the program main initialization up to the dynamodb queries?
