### ISSUE TITLE
Incomplete list of functions in Publish to AWS Lambda Dialog Window

### ISSUE THREAD

**Issue by bpavlov** [aws/aws-sdk-net#503]
When I am trying to upload Lambda to AWS I am not able to find its name in the drop-down list. I have to type its name and also its handler, memory, timeout and etc. (This happens for some Lambdas, not for all)
![image](https://cloud.githubusercontent.com/assets/2480572/20907518/75a8fafa-bb57-11e6-8275-702fbb348263.png)

**Comment by normj** [comment]
Can you go back to this screen and after you confirm your functions aren't showing up check the Visual Studio logs to see if there was any trouble refreshing box. The logs can be found at

C:\Users\<username>\AppData\Local\AWSToolkit\logs\visualstudio

**Comment by bpavlov** [comment]
I checked the logs and there were only "INFO" messages. Just to clarify: I am able to see some of the lambdas function. But some of them exists in AWS but are not listed in the drop-down. In other words the list is incomplete.

**Comment by normj** [comment]
Can you try the latest version of the toolkit. We made a fix get all the pages of Lambda functions from the service instead of just the first page.

**Comment by bpavlov** [comment]
Great job! Currently I am using **Preview of the AWS Toolkit for Visual Studio 2017**. I am seeing all functions.

NB: When I type the name of the function (without choosing it from the list) - handler, role name, memory (mb) and timeout (ms) are NOT populated.

**Comment by normj** [comment]
I'm gonna close this since the original issue is fixed.

We had some issues with typing in functions in the editable combo box because it would auto select partial matches as you typed and cause the wizard to get auto populated with an existing function when you are trying deploy a new function. Basically imagine you have a FooV1 function and you want to deploy FooV2. What was happening as that as soon as you typed "F" the wizard would get populated with FooV1 info which is not what we want.

I'm sure we could have kept working on it and improving it. If you feel strongly about it feel free to open a separate issue.

**Comment by bpavlov** [comment]
You are right! Actually I remember that I experienced this problem 1 year ago. I was trying to create "FooV2", but  "FooV1" data was populated. Then I had to delete "FooV1" description and event handler.

Keep up the good work!

P. S.: Sorry for the spam

**Comment by bpavlov** [comment]
With version 1.12.1.1 I have the same issue
