### ISSUE TITLE
Update LitJson in Amazon.Core to 0.9.0

### ISSUE THREAD

**Issue by Deathwing** [aws/aws-sdk-net#513]
I wanted to ask, if you guys plan to update the ThirdParty.Json.LitJson library to 0.9.0 inside your Amazon.Core.

One cool and important new feature of that version is the "SkipNonMembers" of the JsonReader, which allows it to have i.e. client classes which are a bit older than server responses in regard of their content.

i.e.
Client Player-Class has:
string name
int level

Server Player-Class (which is returned as an json from a lambda, etc.):
string name
int level
int gold

So the client will not be able to run the mapping (JsonException would be thrown), as long as he has not implemented the gold property into his class, which would be possible with the 0.9.0 version of the ThirdParty.Json.LitJson library.

Cheers!

**Comment by sstevenkang** [comment]
Howdy.  Thanks for bringing this to our attention.  It does seem like a useful feature to have.  However, our version of LitJson deviated non-trivially to support a few things including unsigned integers.  We can't guarantee if it'll happen, but we'll take a look.

**Comment by gokarnm** [comment]
Hi Robert, is the current version of LitJson used internally by the SDK breaking any scenario for you? The SDK client use custom unmarshaller classes to process responses and currently does skip any additional members returned by the server. 
If you are using LitJson in your application code, I would recommend using [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) or the latest  LitJson library directly instead of the one that's part of Amazon.Core. The one inside Amazon.Core is intended to be used internally by the SDK, it's deviated from the public version and may not be updated to the latest version.

Closing this issue, feel free to reopen.
