### ISSUE TITLE
Allow config MaxConnectionsPerServer

### ISSUE THREAD

**Issue by omerkorenn** [aws/aws-sdk-net#560]
Hi,

In the implementation of HttpRequestMessageFactory for .NET Core  at
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L173

It will be great if you will allow to set the MaxConnectionsPerServer on the HttpClientHandler through the IClientConfig.

Thanks,

**Comment by PavelSafronov** [comment]
We're looking into adding this.
Out of curiosity, what is your use-case that requires this? It appears that `HttpClientHandler.MaxConnectionsPerServer` is set to `int.MaxValue`, so specifying this value to any other value will simply limit simultaneous connections. Is this what you need?

**Comment by omerkorenn** [comment]
Yeah exactly,
We want to be able to control the overall connections to AWS Service so the connections won't explode, so it is convenient that we will be able to do so by configuring the client, and not as external implementation.
We most of the time prefer to share Service Clients in the application, than allocate them multiple times.

Thanks

**Comment by PavelSafronov** [comment]
We're looking into exposing this setting, though if you are planning on using **just** this setting to control connections, you'll likely run into other issues, like processes waiting around for a connection to become available, possibly indefinitely (if you're creating connections faster than they can be used).

The recommended approach is then not to limit the number of connections that can be made from all the clients, but to limit the number of clients that are making connections. For example, instead of uploading data to S3 from multiple locations in your application, you would have a single "consumer" thread that uploads items to S3, and all the other locations would be "producers" that simply enqueue data for this singleton.

**Comment by vellozzi** [comment]
IClientConfig.MaxConnectionsPerServer was added for .NET Core in SDK Version 3.3.84.1, NuGet package AWSSDK.Core version 3.3.13.4.
