### ISSUE TITLE
Issue for Selecting Lambda Roles

### ISSUE THREAD

**Issue by YuechiXu** [aws/aws-sdk-net#571]
![capture](https://cloud.githubusercontent.com/assets/22451559/23523781/38569ce6-ff56-11e6-8bb7-aaf524d2e17f.PNG)

When I use Publish to AWS Lambda in Visual Studio 2015,  **Role Name** drop down list doesn't show all the roles in account. I can't scroll down to get more roles.

**Comment by normj** [comment]
Out of curiosity how many roles do you have defined in your account? The control does cap the number of roles. The reason we did that was we know some accounts are very large with hundreds of roles and we feared the simple combo box would be unmanageable.

The quick fix would be to make the control an editable combo box. That way if the role didn't show up could always manually entered instead of being blocked like you are now. 

The longer solution would be having an extra search option if the role you wanted didn't show up in the list.

Would the quick solution work for you till we have time for the longer solution?

**Comment by YuechiXu** [comment]
For quick solution, where I can "make the control an editable combo box"?
Can give me some inspire?
Thanks

**Comment by PavelSafronov** [comment]
Norm was referring to us making a quick fix to the Toolkit to make the combo box editable. If this approach would unblock you, we could make this change and release a new version.

**Comment by YuechiXu** [comment]
Yes. If you can release a new version and fix this bud, that is will be great. By now, I have to upload code zip package using console. That is painful process for test code. Please fix it ASAP.
Thanks

**Comment by normj** [comment]
I pushed out a new version of the toolkit that does have a work around. Make the combo box editable didn't work because the eventing behind the control got really tricky.

But with the latest version of the toolkit if you specify the role in the `aws-lambda-tools-defaults.json` file that was created as part of the Lambda new project the toolkit will add that role to the combo box and preselect it. 

Here is an example of how to set the role arn in the `aws-lambda-tools-defaults.json` file.

```json
{
  "profile":"",
  "region" : "",
  "configuration" : "Release",
  "framework" : "netcoreapp1.0",
  "function-runtime":"dotnetcore1.0",
  "function-memory-size" : 256,
  "function-timeout" : 30,
  "function-handler": "AWSLambda1::AWSLambda1.Function::FunctionHandler",

  "function-role" : "<insert-role-arn>"
}
```

We will take a look at a better long term solution but hopefully this should get you working for now. For any change we make in the future this work around will still be valid.

**Comment by YuechiXu** [comment]
Thanks. Now this solution save my time. Thanks
