### ISSUE TITLE
Register and log in with Unity SDK

### ISSUE THREAD

**Issue by UFNaviGator** [aws/aws-sdk-net#589]
There was previously a question posted about this and a resultant feature request that was opened and then closed without resolution.  Issue #369.  

We are looking to use the Cognito Unity SDK to register and authenticate users.  It was commented on the linked post that it was not yet supported.  The original poster found a work around and closed the issue.  We would like to use standard supported methods to handle this and feel that the issue should be re-opened as a feature request.

**Comment by PavelSafronov** [comment]
The issue was closed, but the feature request is still on our backlog. (It looks like it was not properly added to [FEATURE_REQUESTS.md](https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md), I'm adding it now.) At the moment, there is no official support for this feature in the Unity SDK, so you would have to go with one of the suggested approaches from [Issue 369](https://github.com/aws/aws-sdk-net/issues/369).

**Comment by UFNaviGator** [comment]
Thanks for the quick reply and for adding it and explaining the backlog procedure!
