### ISSUE TITLE
Reading notifications received from within the mobile unity app

### ISSUE THREAD

**Issue by genuinefafa** [aws/aws-sdk-net#601]
I'm having trouble finding out how to read the notifications received by the unity app, to make it clear, what I need is:

 * If the app is suspended/closed; when open, somekind of id referencing the notification and a way to read it 
 * if the app is foreground; how can I read the message of the push notification?

SimpleNotificationService docs describes how to setup the device to receive notifications, but no exact way to read it. Not for Unity, not for the SDK as a hole. 

The [Game Example Project found here](https://github.com/awslabs/aws-sdk-unity-samples/tree/master/Chess%20Game%20Example%20Project) do something using DynamoDB, but it feels too hardcore for my use case.

Cheers!

**Comment by PavelSafronov** [comment]
You'll need to use one of the push notification services outlined in [this section](http://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html) of [the Amazon SNS Developer Guide](http://docs.aws.amazon.com/sns/latest/dg/welcome.html). Which service you use will depend on what platform you are targeting.

**Comment by genuinefafa** [comment]
@PavelSafronov notifications *are working*, I'm able to register the endpoint for each device via device token or registration id. So I'm all set there. 

What I am unable to grasp is how to read the notification data from within the app... 

If I were to use native Objective-C app, it will look something like this:
```objc
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo 
{
    application.applicationIconBadgeNumber = 0;             
    //self.textView.text = [userInfo description];
    // We can determine whether an application is launched as a result of the user tapping the action
    // button or whether the notification was delivered to the already-running application by examining
    // the application state.

    if (application.applicationState == UIApplicationStateActive)        
    {                
        // Nothing to do if applicationState is Inactive, the iOS already displayed an alert view.                
        UIAlertView *alertView = [[UIAlertView alloc] 
            initWithTitle:@"Did receive a Remote Notification" 
            message:[
                NSString stringWithFormat:@"Your App name received this notification while it was running:\n%@"
                ,[ [userInfo objectForKey:@"aps"] objectForKey:@"alert"] 
            ]
            delegate:self 
            cancelButtonTitle:@"OK" 
            otherButtonTitles:nil];

        [alertView show];          
    }    
}
```
http://stackoverflow.com/a/14873108/1098814

**Comment by PavelSafronov** [comment]
Ah, got it.
This sounds more like a generic iOS question rather than an AWS SDK for .NET question, and unfortunately this repo really isn't the best place to get iOS help. I'd recommend following up on Stack Overflow or an iOS-centric forum.

Since this isn't an issue with the AWS SDK for .NET and there is nothing we can help with, I'm closing this issue.

**Comment by genuinefafa** [comment]
Is it? It will be the same while using Android or any other platform... I wanna know when a push is received even with an open app. Do you follow my use case? Notification are pushed to the device in any state. How can I receive that JSON (for example) pushed data using the SDK?

What will happen with the SDK when SNS push a notification and the app is opened? Maybe using SQS as [explained here](http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html).

**Comment by PavelSafronov** [comment]
This is the use case of publishing notifications to devices using SNS:
1. A message is sent to Amazon SNS
2. SNS relays the message to the appropriate push notification service (for iOS it's Apple Push Notification Service (APNS), for Android it is Google Cloud Messaging for Android (GCM), others for other devices/platforms)
3. The push notification service pushes the message to the device
4. On-device API notifies your app of the message
5. Your app receives this message and notifies the user

Your question is about step 5, but once step 1 is complete the rest of the process does not involve the .NET SDK, which is why I believe that this question is beyond the scope of this repo.

**Comment by genuinefafa** [comment]
I see your point @PavelSafronov; you definitely know your ground. 

In that case, I would suggest:
1. including this behavior in the examples: It is a little bit confusing that you can receive SNS while the app in background or suspended but not while in foreground. 😞 
2. since i'm using unity, their API should be able to read push within the app (that's your point 5). I'm still not sure how (that's why I ask for an example, and do not provide it), but it has to do with [NotificationServices](https://docs.unity3d.com/462/Documentation/ScriptReference/NotificationServices.html); if anyone cares, I'll get back with more info on the matter.
