### ISSUE TITLE
DynamoDb DocumentModel difficult to create stubs

### ISSUE THREAD

**Issue by lgrosales** [aws/aws-sdk-net#604]
I'm finding the code using the DynamoDb DocumentModel (Table, Search, etc) difficult to test. Private constructors, no interfaces, impossible to create stubs of them.

Is there any plan to refactor these to make them more unit tests friendly?

**Comment by PavelSafronov** [comment]
This isn't on our roadmap right now, but I will add it to our [feature requests backlog](https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md).
If you're interested in working on this addition, we're always happy to accept a pull request.

**Comment by PavelSafronov** [comment]
Request added to backlog. Closing.

**Comment by Kralizek** [comment]
I just stumbled on this very issue. Is there a way to vote up a feature request?

**Comment by kwbauer** [comment]
This issue is fairly easily addressable by adding public constructors to the classes that are returned from the IDynamoDBContext methods. Either making the existing constructors public (only possible if their arguments are for public types) or adding another constructor (generally a parameterless one).
