### ISSUE TITLE
AWSPowerShell—Feature Request: Improve Pipeline Support

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-sdk-net#612]
The majority of AWSPowerShell Cmdlets accept (or possibly require) the parameter `Region`. When calling multiple Cmdlets in a pipeline, the region, and often other parameters, must be specified for each command. For example: `Get-CfnStack -Region us-east-1 | Get-CfnStackResource` will fail if the default AWS region is not set, requiring the user to duplicate the region specification in the pipeline: `Get-CfnStack -Region us-east-1 | Get-CfnStackResource -Region us-east-1`. This duplication is extra work, but also introduces a potential point of failure. For example: `Get-CfnStack -Region us-east-1 | Get-CfnStackResource -Region us-east-2`. A subtle typo could result in the command failing or, in extreme cases, successfully executing actions on the wrong resources.

Given this example, if the Cmdlet `Get-CfnStack` passed the `Region` parameter through, and the `Get-CfnStackResource` Cmdlet accepted the `Region` parameter as pipeline input by property name, the original pipeline would execute successfully.

There are other examples where this would prove useful. Working with S3, for instance, often requires that the `BucketName` parameter be specified multiple times in a pipeline. Similarly, due to the lack of pipeline input support, the `ForEach-Object` Cmdlet may be necessary to iterate rather than having, for example the Cmdlet natively handle piped input. In general, it would be very helpful to have the majority of common parameter values passed through Cmdlets as well as accepted as values from the pipeline by property name.

**Comment by steveataws** [comment]
I agree that needing to repeatedly specify -Region can be a pain, that's why we created the Set-DefaultAWSRegion cmdlet so that a fallback default could be set for a script or the shell, and then you only need to add -Region to a cmdlet when you need to direct the call to a different region. 

I took a quick look over the code and the Region and BucketName parameters are already attributed as 'ValueFromPipelineByPropertyName', so provided the input object in the pipeline contains matching fields then these should already bind.

That said, I think the actual problem here is that in the pipeline, the objects being passed as the output from a service api call don't carry this information (except for some S3 operations on objects, where the Amazon.S3.Model.S3Object type does contain the bucket name), therefore there is no input value field for the shell to bind to.

One solution would be for us to add the region perhaps as a note property to each object we emit to the pipeline so we're effectively augmenting the model objects handed back to us from the underlying AWS SDK for .NET (which has unmarshalled the service response to C# objects with region data). We'd likely have to make this an opt-in feature though, as it's possible we could break existing behavior, for example:

PS C:\> Set-DefaultAWSRegion us-west-2
PS C:\> cmdlet1 -region us-east-1 | cmdlet2  # user expects cmdlet2 to run in the context of us-west-2

In this scenario, having the us-east-1 region data 'flow' into cmdlet2 would cause different behavior.

Thoughts?

**Comment by bgshacklett** [comment]
Steve, my apologies for the delay in response to your last update.

I am actually curious why the region was not originally included in the .Net object model for resources that are associated with specific regions. It seems that it would be a useful piece of information in the .Net world as well as in PowerShell. That said, I would not be opposed to including a NoteProperty on the objects returned to the PowerShell CLI.

The example you raise is certainly an interesting one. I agree with you that this could cause issues for people who have written scripts which depend on the default AWS region being set in the script. I would love to see this behavior as the default in a future version, but I think the current behavior would need to be deprecated and warned about for some time before that change is made.

As for the mechanism for opting in, environment variables have served me well in the past. It's easy to add a bit of configuration to the user's PowerShell profile which would enable the Note Properties.

**Comment by vellozzi** [comment]
This will be a good feature in our PowerShell tools.  The challenge is implementing it in a backward compatible manner.

We've added this to our backlog.
