### ISSUE TITLE
C# API Gateway API examples

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-net#674]
I do not seem to be able to find any C# examples of how to use the API Gateway API to create new APIs.

I want to be able to create API Gateway proxy items from an existing list and I do not want to have to create a swagger file (need to be able to dynamically change items).

Can the AWSSDK create API Gateway proxy items? If so how?

I see Amazon.APIGateway.IntegrationType HTTP_PROXY

But the call AmazonAPIGatewayClient.CreateResource does not use Amazon.APIGateway.IntegrationType and neither does Amazon.APIGateway.Model.CreateResourceRequest

Thanks
Dave

**Comment by PavelSafronov** [comment]
The API Gateway .NET SDK can be used to perform all the available API Gateway operations. Unfortunately, we don't have examples for these operations yet.

One way forward is for you to go through the [API Gateway Developer Guide](http://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html), identify the tasks that you want to do, find the Console, CLI, or Java examples for those tasks in the guide, then "translate" those into .NET SDK operations. Since the .NET SDK is a one-to-one mapping of the service operations, this translation step should not be too complicated. The hardest aspect here will be figuring out how to use the service to do what you want.

**Comment by genifycom** [comment]
Hi Pavel,
I do not have any trouble translating from Java to C#.  I am, however, finding it difficult to find even Java examples of how to create an API, and especially an HTTP {proxy+} api.

I assume that we start ojf something like this?

                var client = new AmazonAPIGatewayClient(aws_access_key, aws_secret_key, Amazon.RegionEndpoint.USEast1);

            //Need to get the root resource ID since this is the parent of all API keys
            var req = new GetResourceRequest() { ResourceId = "root-id" };
            client.GetResourceAsync(req);

            var resource = new CreateResourceRequest() { ParentId = req.ResourceId, PathPart = "/Test", RestApiId = "" };
            client.CreateResourceAsync(resource);

            var req2 = new AmazonAPIGatewayRequest();
            var key = new CreateApiKeyRequest() { CustomerId = "", Name = "NewResource", Enabled = true };

            client.CreateApiKeyAsync(key);

Any pointers to code would be helpful.

Thanks,
Dave

**Comment by PavelSafronov** [comment]
Excellent question, but I'm afraid I don't have an answer for you.

The closest example is the [Create and Test an API with HTTP Proxy Integration](http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html) tutorial, though it shows how this is done through the Console. Still, the concepts should translate from Console to SDK (Java, .NET, etc.).

You can also try asking on the [API Gateway Forum](https://forums.aws.amazon.com/forum.jspa?forumID=199), it's likely that other users have run into the same issue and are also trying to create proxy resources through the API.


Since this is a question of how to use a particular service through their API, (as opposed to a bug in the .NET SDK), I'm going to close this issue.

**Comment by genifycom** [comment]
Further testing gives the following:

            var client = new AmazonAPIGatewayClient(aws_access_key, aws_secret_key, Amazon.RegionEndpoint.USEast1);
            CreateRestApiRequest newreq = new CreateRestApiRequest() { Name = "test-api", Description = "Generated API from SDK" };
            var result = Task.Run(() => client.CreateRestApiAsync(newreq)).Result;
            var id = result.Id; //This is the Id of the newly created API

This works fine and created the API.

Calling:
aws apigateway get-resources --rest-api-id <id from above> --region us-east-1
works fine and returns the id of the resource.

However, calling get-resources via the SDK:

            //Need to get the root resource ID since this is the parent of all API keys
            var req = new GetResourceRequest() { RestApiId = id, ResourceId = "/" };
            var result1 = Task.Run(() => client.GetResourceAsync(req)).Result;

fails with:

The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method.
Consult the service documentation for details.

aws apigateway has a Path parameter, the SDK call does not. I am assuming that ResourceId in the SDK is the same one.

Any hints here?

**Comment by PavelSafronov** [comment]
API Gateway has operations GetResource and GetResources. You're calling one with the CLI, and the other with the .NET SDK, hence the difference you're noticing here.
As for the exception you're seeing with `GetResource`, I think ResourceId should not have the leading `/` and should just have the resource id as its value.

**Comment by genifycom** [comment]
Ah, thank you Sir. I have it working now.

**Comment by buktorom** [comment]
I'm using code to create an API:
```
var client = new AmazonAPIGatewayClient(inp.aws_access_key, inp.aws_secret_key, Amazon.RegionEndpoint.USEast1);
            CreateRestApiRequest newreq = new CreateRestApiRequest() { Name = inp.name_api, Description = inp.description , Version = "01"};
            var result = Task.Run(() => client.CreateRestApiAsync(newreq)).Result;
return result.Id;
```
How do I get a root-id (ParentId for resources) that is created automatically? RestApiId I get without problems.
