### ISSUE TITLE
AWSPowershell—Get-ECSClusters : A WebException with status NameResolutionFailure was thrown.

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-sdk-net#685]
When calling Get-ECSClusters for all regions, I get a number of errors stating: "Get-ECSClusters : A WebException with status NameResolutionFailure was thrown." On the surface, this is very confusing and it's easy to think that the issue could be the local DNS servers or configuration.

## Expected Behavior
A more reasonable error should be thrown, perhaps something stating that there is no support for the service in the specified region.

## Current Behavior
Some regions show the clusters as expected. For others, there is an uncaught exception:
```
Get-ECSClusters : A WebException with status NameResolutionFailure was thrown.
At line:1 char:34
+ Get-AWSRegion | ForEach-Object { Get-ECSClusters -Region $_ }
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...SClustersCmdlet:GetECSClustersCmdlet) [Get-ECSClusters], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.Runtime.AmazonServiceException,Amazon.PowerShell.Cmdlets.ECS.GetECSClustersCmdlet
```

## Possible Solution
Is there an API that could be queried to say if a service is supported in a specific region? If so, catching the exception, then checking the api to see if it should be available might be a good start. If not, perhaps the mechanism for generating the matrix at https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ would be of some use to automate a hard coded structure like `Get-AWSRegion` uses.

## Steps to Reproduce (for bugs)
    Get-AWSRegion | ForEach-Object { Get-ECSClusters -Region $_ }

## Your Environment

* AWSPowershell Version: `3.3.84.0`
* Operating System and version: Windows `10.0.14393.0`
* Visual Studio version: n/a
* Targeted .NET platform: 
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.1066}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by steveataws** [comment]
There's no api to detect a service is present in a given region, but we can infer as such from the endpoints file that is contained inside the underlying SDK assemblies. 

One reason we don't error out if we can't find an entry in the file for a given service/region combination is that currently, as services expand into new regions or new regions get added, you don't need to update your tools to make use of the new region. This is something we'd like to keep.

One approach I've been talking about with a colleague who also queried this (in his case, he mis-typed the region name but it's also occurred with users entering an AZ name instead of a region) was to emit a warning message that we can't find an entry for the service/region in the endpoint data available at the time the module was released, but will attempt to contact the computed endpoint (and show what we computed) to try and aid debugging.

Secondly, there's also a possibility of either extending Get-AWSRegion so you can specify the service and we return the set of regions (again, from data known at build/release time) so your piping example would work. We could also add a cmdlet to list the regions for a service could also be added. My one worry is that users might think this data is 'live' so we'd have to document quite clearly that it could be based on old data depending on the version of the tools in use.

Thoughts?

**Comment by bgshacklett** [comment]
I like the idea behind your first approach. The key, here, is that there's a lack of context around what this error might mean. Providing a hint that the user should check that they've entered the region properly, and that the specific service exists in the region, would go a long way towards a quicker resolution of the issue and could prevent someone from spending time troubleshooting DNS when it is, in fact, working as expected.

I'm a bit on the fence as to whether it would make more sense to just emit a warning or if the existing exception should be wrapped. I feel like the latter would be more useful programatically, but might be a more invasive change than it seems on the surface.

**Comment by steveataws** [comment]
Sometime after this discussion we reworked the exception handling in the cmdlets to output a more meaningful message when a name resolution failure occurs, for example:

_PS C:\> **Get-ECSClusterList -region does-not-exist**
Get-ECSClusterList : Name resolution failure attempting to reach service in region does-not-exist (as supplied to the -Region parameter or from configured shell default).
The remote name could not be resolved: 'ecs.does-not-exist.amazonaws.com'.
Possible causes:
        - The region may be incorrectly specified (did you specify an availability zone?).
        - The service may not be available in the region.
        - No network connectivity.
See https://docs.aws.amazon.com/general/latest/gr/rande.html for the latest service availability across the AWS regions._

Get-AWSRegion at this time continues to use static data compiled into the underlying aws sdk for .net at the time the module was built, so isn't a reliable source of accuracy for what regions exist *right now* or what services are present there (hence the link in the error message above). We're continuing to evaluate this, but for users who want to know the exact set of available regions the Get-EC2Region cmdlet is available.

Resolving this issue as I think the immediate ask has been fulfilled. Feel free to reopen if needed.
