### ISSUE TITLE
Semantic Version or what versioning scheme do you follow

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#720]
We are shipping a transport adapter that uses AWSSDK.Core, AWSSDK.S3 and AWSSDK.SQS. Our nuspec file used to look like

```
    <dependencies>
        <dependency id="AWSSDK.Core" version="3.3.12"/>
        <dependency id="AWSSDK.S3" version="3.3.5.12"/>
        <dependency id="AWSSDK.SQS" version="3.3.1.12"/>
    </dependencies>
```

But that seems unnecessarily restrictive. We are now contemplating to change it to

```
    <dependencies>
        <dependency id="AWSSDK.Core" version="[3.3, 3.4)"/>
        <dependency id="AWSSDK.S3" version="[3.3, 3.4)"/>
        <dependency id="AWSSDK.SQS" version="[3.3, 3.4)"/>
    </dependencies>
```

But we are unsure what kind of versioning guarantees you are making. Is it safe to assume you will not break things between minors? Or do you even support Semantic Versioning and could we change it to

```
    <dependencies>
        <dependency id="AWSSDK.Core" version="[3.3, 4)"/>
        <dependency id="AWSSDK.S3" version="[3.3, 4)"/>
        <dependency id="AWSSDK.SQS" version="[3.3, 4)"/>
    </dependencies>
```

Any thoughts on that?

**Comment by normj** [comment]
Use the `[3.3, 3.4)` range. Although I would suggest setting the min in the range to the latest version at the time of your release. There have been a lot of fixes done to the SDK since 3.3 came out and by default NuGet will pull in the lowest compatible dependency that satisfies all the dependencies. 

Our versioning basically works like this for a `w.x.y.z` version number.

* w - Code compatible
* x - Binary compatible. In particular AWSSDK.Core is binary compatible with the service packages like AWSSDK.SQS
* y - New SDK feature or service update
* z - Bug fix or bumping the dependency on AWSSDK.Core for service packages so users get the latest bug fixes from core.

There are currently no plans for a 3.4, meaning a binary breaking change, so setting that to your max should give you a plenty of room.

I'll add that explanation to our README.md to make the explanation more official.

**Comment by danielmarbach** [comment]
Thanks! Great info. Yeah having that in the readme sounds nice!

**Comment by normj** [comment]
I added the info with a bit more description to the [README.md](https://github.com/aws/aws-sdk-net#versioning)
