### ISSUE TITLE
Error : this template attempted to load component assembly 'AWSToolkit.Lambda.TemplateWizards

### ISSUE THREAD

**Issue by deepakaggrawal** [aws/aws-sdk-net#735]
I am using VS2017 and I have installed AWS Toolkit but when I try to create a Lambda project then I am getting below error :

> Error : this template attempted to load component assembly 'AWSToolkit.Lambda.TemplateWizards', culture=netural,PublickKeyToken=8339e7e97bb08995'. For more information on this problem and how to enable this template, please see documentaion on Customizing Project Templates.

**Comment by steveataws** [comment]
Apologies we missed responding on this. A quick test with the latest toolkit version, 1.14.0.1, didn't show any problem and we've not heard of similar issues from anyone else over the past few months.

I'm going to close the issue due to age and lack of follow up or similar reported issues. Feel free to reopen if you are still exhibiting problems.

**Comment by infiniteloopltd** [comment]
I'm seeing the same error. 

[![httpsimage.com](https://httpsimage.com/v2/e2b3fc35-e5d5-45eb-8ad9-10e666d833bc.png)](https://httpsimage.com)

Visual Studio 2017 Professional.
