### ISSUE TITLE
UserNotFoundException on username matching preferredusername

### ISSUE THREAD

**Issue by jkdey** [aws/aws-sdk-net#761]
## Expected Behavior

User creation should allow for creation of a user with the same username and preferredusername

## Current Behavior

Throws UserNotFoundException when username matches preferredusername

## Steps to Reproduce (for bugs)

```
var request = new AdminCreateUserRequest
{
    Username = user.Username,
    UserPoolId = userPoolId,
    UserAttributes = new List<AttributeType> { new AttributeType { Name = "preferred_username", Value = user.Username } }
};

await _cognitoClient.AdminCreateUserAsync(request);
```

## Context

Currently requires additional validation in our application. Think this should either return a more informative exception, or allow users to be created with a username matching a preferredusername.

## Your Environment

* AWSSDK.Core version used: 3.3.17.10
* AWSSDK.CognitoIdentityProvider: 3.3.6
* Service assembly and version used: 
* Operating System and version: Windows 10 Version 1703 Build 15063.608
* Visual Studio version: VS 2015
* Targeted .NET platform: .NET Core 1.0.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
I don't think you should be supplying `preferred_username` value that is identical to the `username`. From what I can tell from [Cognito's api docs](http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases), `preferred_username` is an alias.  It would be redundant to set the `username` and `preferred_username`.

Either way, I agree with you that the error message doesn't seem appropriate.  The error is coming from the service itself and there's nothing much we can do on our side at SDK level.  We'll check with Cognito service team to see if sending this exception was intentional for this case.

**Comment by sstevenkang** [comment]
Hi, just wanted to give you an update.  Cognito service team confirmed that this is an issue on their end.  They have been working on a fix.  Thanks again for reporting this problem.

**Comment by jkdey** [comment]
Thank you for following up.

**Comment by sstevenkang** [comment]
Fix should be available now.  Feel free to ping this issue or create a new one.
