### ISSUE TITLE
'RegionEndpoint' does not contain a definition for 'USEast2'

### ISSUE THREAD

**Issue by moreira-daniel** [aws/aws-sdk-net#770]
I'm, using a VS 2017 console project with the version '2.3.55.2' of aws sdk. and Ohio doen't exists.
I try:
  var region = Amazon.RegionEndpoint.GetBySystemName("us-east-2");

and region is unknow.

What am I doing wrong?

**Comment by steveataws** [comment]
V2 of the SDK is deprecated and so isn't updated except for security issues. The last update to this version of the SDK was a year or so ago and won't therefore contain any service updates or new region launches since.

You should still be able to use the us-east-2 region by simply using the string constant. If you can I recommend updating to V3 of the SDK.

**Comment by moreira-daniel** [comment]
Thank you!

**Comment by Aloksriashoka** [comment]
Amazon.RegionEndpoint.GetBySystemName("us-east-2"); 
Worked for me.
