### ISSUE TITLE
PutObjectAsync?

### ISSUE THREAD

**Issue by im1dermike** [aws/aws-sdk-net#780]
I have a .net core app in which I'm trying to write a file to an S3 bucket.  I'm successfully injecting a `IAmazonS3` client as described [here](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-region-selection.html).  It appear to only have access to async methods on the client, specifically, `PutObjectAsync` and there is basically no documentation/examples on this.

I'm using the following code, but get a "The HTTP redirect request failed" error:

```
var request = new PutObjectRequest
{
    BucketName = "bucketName",
    Key = "testKey",
    ContentBody = "Sample text"
};
var response = await client.PutObjectAsync(request);
```

**Comment by im1dermike** [comment]
It looks like the `IAmazonS3` definition in this repository in the [_bcl45](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Generated/_bcl45/IAmazonS3.cs) path has the non-async methods that are referenced in all examples, but the interface in the [_unity](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Generated/_unity/IAmazonS3.cs) folder has all the async methods.  I'm guessing _unity is .net core...

**Comment by normj** [comment]
Most of our samples and documentation that has been written over the years has been written for .NET 4.5 with the sync methods since it is the most common. I agree with you that as we are expanding our scope of .NET Core support we should be using .NET Core more in our samples.

Unity has the same restrictions as .NET Core in that it is only async but the underlying SDK runtimes are different.

As far your issue with the redirect. I wonder if you are getting an issue with the SDK client that is configured for a different region then the bucket is in.

**Comment by im1dermike** [comment]
I ended up resolving my issue (actually had to do with me having the wrong region specified when injecting my instance of `IAmazonS3`... unhelpful error message).

**Comment by normj** [comment]
Glad you go it working and I agree that error message wasn't helpful and we should make that better.
