### ISSUE TITLE
Failed to install AWS Toolkit for VS2017 on Windows 10 

### ISSUE THREAD

**Issue by zindify** [aws/aws-sdk-net#826]
I'm trying to install the AWS SDK toolkit on VS 2017 but it fails.

Expected Behavior
Be able to install the toolkit

Current Behavior
It doesn't work

attached is the log I could get from the installer

[VSIXInstaller_8d9a75c2-8efd-4d4c-9a3f-3ff526f66d16.log](https://github.com/aws/aws-sdk-net/files/1603002/VSIXInstaller_8d9a75c2-8efd-4d4c-9a3f-3ff526f66d16.log)

**Comment by steveataws** [comment]
Thanks for supplying the log file. It looks as though the installer is failing due to the existence of an icon file related to one of our project types - _C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Amazon Web Services LLC\AWSToolkit.VS2010\AWSCloudFormationProject.ico_.  Was this an upgrade install? Do you have multiple versions of VS2017 installed?

We don't own the installer for Visual Studio and I think Microsoft are still encountering some teething issues with the new multi-version install. Sadly there's no fix I can think of other than to manually clean up the affected folder(s) and try again. We'd be interested to hear if you still encounter a problem afterward.

To help with cleanup, our vsix package is configured to have files placed in locations under the overall root **C:\Program Files (x86)\Microsoft Visual Studio\2017**. Each version (Community, Professional etc) will have a subfolder under here and you'll need to look at them all if you have multiple versions installed.

For each version, the vsixinstaller will place the extracted package content into a random-named subfolder beneath _Common7\IDE\Extensions_. For example on my laptop (Windows 10, VS2017 Professional) the extension is installed at _C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\044edncn.ybh_. Note that if this is an upgrade install, you may have multiple copies of the extension (VS2017 uses a deferred deletion scheme) so you'll need to check each subfolder. Delete any you find that contain our toolkit package (identified by the presence of a file named **AWSToolkitPackage.dll** for each version of VS2017 you have installed.

MSBuild targets and related files for our CloudFormation project type will be placed into _MSBuild\Amazon Web Services LLC\AWSToolkit.VS2010_. Again, for my system that means _C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Amazon Web Services LLC\AWSToolkit.VS2010_. Once again delete any instances of the _Amazon Web Services LLC_ folder you find for each version of VS2017 you have installed.

Please let us know if the installer still fails after cleanup and we'll see what we can figure out with Microsoft based on new logs.

**Comment by zindify** [comment]
Hi Steve,

Thanks for your reply. I don't have multiple versions of VS2017 installed. But I managed to solve it by removing the existing C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Amazon Web Services LLC  folder. 

The reason that this folder already exists was because I had AWS toolkit for VS 2017 installed several months ago. But It suddenly disappeared in VS2017 recently probably due to recent VS upgrade or Windows upgrade. I am not sure about the cause. That's why I tried to install it again and encounter this issue.

**Comment by leandrosaf** [comment]
For those who got here because of another file like "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\ydm1g22i.cns\AmazonCLIExtensions.dll" its basically the same solution. Delete the folders.
Thanks zindify!

**Comment by robsjunqueira** [comment]
I'm trying to install the AWS SDK toolkit on VS 2017 but it fails.
[VSIXInstaller_7a4dd86b-31ae-4e63-87d8-ada0f09ca032.log](https://github.com/aws/aws-sdk-net/files/2014502/VSIXInstaller_7a4dd86b-31ae-4e63-87d8-ada0f09ca032.log)

Attached is the log error from the installer

**Comment by briporteran** [comment]
For me the issue:
I had VS 2017 and AWS Toolkit installed and working fine.
I updated VS 2017 and AWS Explorer disappeared and AWS Toolkit no longer showed under installed Extensions and Updates
Re-installing/updating AWS Toolkit failed

And the resolution (using above comments):
I deleted C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Amazon Web Services LLC
and I also had to delete
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\xxxxx.xxx (where xxxxxx.xxx was the folder that contain AWS related dll's)
Re-installed AWS Toolkit via Extensions and Updates
And it worked

**Comment by anoj-9771** [comment]
Has anyone encountered the issue on MacOS? I'm on MacOS Catalina running VSCode V1.25.0 and am having trouble installing the CLI. I have Docker running and have not installed the Toolkit in past.

![Screen Shot 2019-12-23 at 1 09 37 pm](https://user-images.githubusercontent.com/27731256/71331367-fc2e6b00-2585-11ea-84fb-591b39a5925b.png)
