### ISSUE TITLE
CSV import of credentials fails in Visual Studio

### ISSUE THREAD

**Issue by RichardPetheram** [aws/aws-sdk-net#872]
## Expected Behavior

CSV file downloaded from IAM Management Console should populate credential fields in VS

## Current Behavior

Error box pops up with "Index out of range", plus other wording (didn't copy it all sorry)

## Context

Copying credentials from IAM Console to VS2017. Was able to cut and paste credentials from the screen.

## Your Environment

Windows 10 Pro x64
VS 2017 15.5.6
AWS Toolkit for Visual Studio 2017 - 1.12.0.9
.Net 4.5.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
I fixed an issue with csv file formats causing us an issue a while back - I don't recall the exact version now, but I see the toolkit you have is old (we're now at 1.14.1.2). Any chance you could update and try the same again to see if the problem is already fixed?

If the problem is still present, please post the header row of your csv file (not the actual key data!) into the issue so we can try and repro.

Thanks!

**Comment by jimshalo10** [comment]
Works for me in Visual Studio Community Microsoft Visual Studio Community 2017 
Version 15.5.7
VisualStudio.15.Release/15.5.7+27130.2036
 and AWS Toolkit for Visual Studio 2017   1.14.1.3 from Visual Studio Marketplace 24th Feb 2018

**Comment by steveataws** [comment]
As we think we resolved the OP's issue with a fix subsequent to 1.12.0.9, and no-one has managed to come up with a failing version of the file, I'm going to resolve this issue. Feel free to reopen, with a copy of the header row from a failing csv file, if it can be reproduced again.
