### ISSUE TITLE
/.../iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Net.IWebProxy', referenced from the method 'System.Net.Http.HttpClient Amazon.S3.AmazonS3HttpUtil::GetHttpClient(Amazon.Runtime.IClientConfig)' in 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (MT2101) (xxx.iOS)

### ISSUE THREAD

**Issue by AlonikiX** [aws/aws-sdk-net#884]
Hi there, this issue doesn't show up when I run the app on iPhone simulator, however, when I try to test it on the real iPhone device, this error occurs. 

I am using:
Visual Studio for Mac
Xamarin.Forms
Xamarin.iOS
AWSSDK.Core 3.3.21.14
AWSSDK.S3 3.3.17

**Comment by AlonikiX** [comment]
I simply solved it by adding Microsoft.Net.Http package to the iOS project, however, it largely increases the size of the app and slows down the compilation speed..... is there any better solution to this problem? thanks.

**Comment by sunchunqiang** [comment]
Hi @AlonikiX 
iOS version of Amazon.S3.AmazonS3HttpUtil::GetHttpClient should not refer to System.Net.IWebProxy. 

Can you open Object Browser, select AWSSDK.S3 in the Browse and check if Assembly AWSSDK.S3 refer to    ...\awssdk.s3\3.3.xx.x\lib\Xamarin.iOS10\AWSSDK.S3.dll instead of other folder.  If not, that means the package AWSSDK.S3  refers to a wrong  Assembly. You can uninstall AWSSDK.S3 from your project and reinstall it again to see if the issue can be fixed.

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open a new issue.
