### ISSUE TITLE
get request ID from S3 upload by AWS .net framework SDK

### ISSUE THREAD

**Issue by koranit** [aws/aws-sdk-net#924]
I have this code write in .net framwork 4.5 and need to get request ID for S3 upload
anyone have idea how to do it thank you .

Boolean uploadS3(string filePath, string fileName )
        {

            // Get ket S3
             string existingBucketName = System.Configuration.ConfigurationManager.AppSettings["S3BucketName"]; ;
            string s3Accesskey = System.Configuration.ConfigurationManager.AppSettings["s3Accesskey"]; ;
            string s3Secret = System.Configuration.ConfigurationManager.AppSettings["s3Secret"]; ;

            try
            {

                // Set S3 file premission and path
                TransferUtilityUploadRequest fileTransferUtilityRequest = new TransferUtilityUploadRequest
                {
                    BucketName = existingBucketName,
                    FilePath = filePath,
                    StorageClass = S3StorageClass.ReducedRedundancy,
                    PartSize = 6291456, // 6 MB.
                    Key = fileName,
                    CannedACL = S3CannedACL.PublicRead,
                    TagSet = new List<Tag>{new Tag { Key = "TEMP", Value = "Y"} }
                };

                // Set S3 Upload Class 
                TransferUtility fileTransferUtility = new  TransferUtility(
                    s3Accesskey, s3Secret, Amazon.RegionEndpoint.APSoutheast1);
                fileTransferUtility.Upload(fileTransferUtilityRequest);

                return true;
            }
            catch (AmazonS3Exception s3Exception)
            {
                Console.WriteLine(s3Exception.Message,
                                  s3Exception.InnerException);
                return false;
            }
        }

**Comment by Singh400** [comment]
What do you mean "request ID"?

Indy

**Comment by koranit** [comment]
I have problem in some server cannot put object to S3 and need request ID to sent to AWS support Team to see log on aws site to see what happen but I cannot get request ID for that.

I try on this for .net to get request ID but it not working 
https://docs.aws.amazon.com/AmazonS3/latest/dev/troubleshooting.html
https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/

can we print request ID by conolse log or anything else on code ?

**Comment by Singh400** [comment]
```
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogMetrics = true;
```

That works for me, hope that helps!

Indy

**Comment by sstevenkang** [comment]
When you catch and find an AamzonServiceException in the exception tree, you could grab the [RequestId](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AmazonServiceException.cs#L114) property. 

If you are not hitting the catch block ,it's probably because the AmazonS3Exceptino is buried as an inner exception.

**Comment by koranit** [comment]
@sstevenkang 

catch (AmazonServiceException s3Exception)
            {
                vError = "AmazonServiceException Error : " + s3Exception.Message + "#" + vStepError + "#" + s3Exception.RequestId;
                Console.WriteLine("AmazonServiceException Error : " + s3Exception.Message + s3Exception.RequestId, s3Exception.InnerException);
                return false;
            }

vStepError = "Step3";
                fileTransferUtility.Upload(fileTransferUtilityRequest);
                vStepError = "Step4";

output for exception is "error s3 Wak AmazonServiceException Error : A WebException with status SendFailure was thrown.#Step3# " not get request ID 

We have something missing or not ? Thank.

**Comment by sstevenkang** [comment]
@koranit   have you tried using something like Fiddler to retrieve the raw HTTP traffic?

**Comment by Singh400** [comment]
@koranit It's static configuration. So just put it before your method call.

Indy

**Comment by gokarnm** [comment]
@koranit , `AmazonS3Exception.RequestId` and `AmazonS3Exception.AmazonId2` are the properties that will be populated when the SDK receives an error response from S3. These are the properties AWS Support will need to troubleshoot S3 related issues.

 There are other cases where an `AmazonServiceException` can be thrown and either the request itself was not sent  (`WebExceptionStatus.SendFailure`), or a response was not received (e.g the request timed out), in these cases the request ID will not be populated because a response was not received.

How frequently do you see the `AmazonServiceException` with the message "A WebException with status SendFailure was thrown"? SendFailure is automatically [retried by the SDK](https://github.com/aws/aws-sdk-net/blob/29b7c31990cf5cd1d6029aacd4552513192b889a/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs#L64) .

**Comment by sstevenkang** [comment]
Resolving due to inactivity.  Feel free to open a new issue & linked this one.

**Comment by rajeshlh** [comment]
I have been asked to provide S3 RequestID for AWS Support to troubleshoot intermittent exceptions when reading an object from S3 using the .NET SDK call GetObjectAsync. The exception is below:
System.Net.Sockets.SocketException: Connection reset by peer
How do I get Request ID consistently for such S3 failures that result in IO Exception? I understand that the Request ID is a 2 piece info. The catch block for AmazonS3Exception doesn't work since the exception thrown is of type SocketException. So I cannot use the RequestID or the ResponseHeaders property of the AmazonS3Exception class. Please note that I cannot reproduce these IO Exception on demand..its intermittent in production.
