### ISSUE TITLE
ASP.Net Identity Provider and Cognito Identity

### ISSUE THREAD

**Issue by anildbest83** [aws/aws-sdk-net#936]
First this is not any issue but this is for getting the approach right.
I m not sure about what exactly i need to do, so i m trying to explain the requirement

I created a web application using ASP.NET MVC5 with ASPNet.Identity Provider, which is working fine. User data save on my local DB and authentication and authorisation working fine with .Net Provider. Even Social Signing are working fine with .Net Identity.

With .Net Identity i get user detail like this
`User.Identity.GetUserId();`

But Now i need to implement AWS Cogntio for User SignUp and SignIn. On SignUp User data will be saved on Cognito User Pool. I m not sure that with this do i need to save some user information on my local DB like token/cogntioidentity etc for further authentication and authorisation. OR how can i get user detail after login with User.Identity.GetUserId();

I am completely not getting what should be the approach/flow for this. Please advice some ideas or sample code that demonstrates the process.

**Comment by gianibob82** [comment]
You have 2 options: easy path or hard path
Easy way: use OpenIdConnect. The UI forms provided by Cognito are not great but it will save lot of time. Here's an explanation of how to implement it in aspnet core mvc https://github.com/gianibob82/aspnet-core-cognito-integration. But be aware if you deploy your website in API Gateway, OpenIdConnect nuget package has some issue with proxies and won't work. There's an open bug about this.
Hard way: implement you custom storage. I'm currently working on it in my spare time because aforementioned bug with API Gateway.
Basic links I've found:

- https://github.com/aspnet/Docs/blob/master/aspnetcore/security/authentication/identity-custom-storage-providers.md#reconfigure-app-to-use-new-storage-provider
- https://github.com/miltador/AspNetCore.Identity.DynamoDB

**Comment by ZIPSP** [comment]
Hello Did you complete the requirement? I have a similar requirement use AWS Cognito purely to sign in and sign out of asp.net core web client... 


I started on this as per below 

I already created a AWS Cognito User pool and App Client.. I followed the below article from AWS 

https://aws.amazon.com/blogs/mobile/use-csharp-to-register-and-authenticate-with-amazon-cognito-user-pools/

reached the point 

var cognito = new AmazonCognitoIdentityProviderClient(_region);
//var cognito = new AmazonCognitoIdentityProviderClient(credentials);

var request = new AdminInitiateAuthRequest
{
UserPoolId = _aWSConfig.PoolID,
ClientId = _clientId,
AuthFlow = AuthFlowType.ADMIN_NO_SRP_AUTH
};

request.AuthParameters.Add("USERNAME", "test@test.com");
request.AuthParameters.Add("PASSWORD", "P@ssword12");

var response = await cognito.AdminInitiateAuthAsync(request);

return strToken = response.AuthenticationResult.AccessToken;

1. what are the next steps so that asp.net core web client is aware the user is logged in ?? map asp.net identity to cognito token? (how to do this)? 

example the below are set 

User.Identity.IsAuthenticated

User.Identity.Name

User.Claims 

2. what other details from token need to be stored where and how in ASPNET Client so that these can be used to send in HTTPCLient request header to consume web api ?

**Comment by gianibob82** [comment]
here's a link to a full mvc solution using Cognito https://github.com/gianibob82/aspnet-core-cognito-integration

**Comment by ZIPSP** [comment]
Thanks Gianibo82, the above will use The UI form provided by AWS Cognito, so authorized page redirect to log in form provided by AWS cognito. I need to use log in form of my own asp.net core web client and authenticate against AWS Cognito user pool with the user name/pwd entered in my web client log in page.

**Comment by assyadh** [comment]
Hi,

I am currently working on an ASP.NET Core Identity Provider for Amazon Cognito. 

While this library is still in development, we appreciate any feedback!

You can find the source code here: https://github.com/aws/aws-aspnet-cognito-identity-provider

Hamza.
