### ISSUE TITLE
S3DirectoryInfo MoveTo throws "key is a directory name" esxeption

### ISSUE THREAD

**Issue by alex-jitbit** [aws/aws-sdk-net#957]
Moving directories does not work.

## Steps to Reproduce (for bugs)
```
S3DirectoryInfo source = new S3DirectoryInfo(_client, _bucketName, sourceName);
S3DirectoryInfo destination = new S3DirectoryInfo(_client, _bucketName, destinationName);
source.MoveTo(destination);
```

## Environment

* AWSSDK.Core version used: 3.3.22.5

**Comment by lrocher** [comment]
I have a similar issue.
It's look this exception happen when a subdirectory exists as a zero file size.

I suspect issue is in `public IEnumerable<S3FileInfo> EnumerateFiles(string searchPattern, SearchOption searchOption)` in file  sdk/src/Services/S3/Custom/_bcl/IO/S3DirectoryInfo.cs

[Code Line](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Services/S3/Custom/_bcl/IO/S3DirectoryInfo.cs#L663)
`
.Where(s3Object => !String.Equals(S3Helper.DecodeKey(s3Object.Key), key, StringComparison.Ordinal) 
  && !s3Object.Key.EndsWith("\\", StringComparison.Ordinal)),
`

I think second condition didn't match because s3Object.Key is not decoded and finish with `'/'` rather `'\\'`. 
In this case a new S3FileInfo is create and generate "key is a directory name" exception.

I hope it can help investigation.

**Comment by ashishdhingra** [comment]
Hi @alex-jitbit, @lrocher,

Good morning.

I was going through the issue backlog and looks like the PR contributed by @lrocher was already approved and merged. Just wanted to check if this is still an issue or if this could be closed.

Thanks,
Ashish
