### ISSUE TITLE
Won't install to VS 2017 on Windows 10

### ISSUE THREAD

**Issue by dhsass** [aws/aws-sdk-net#967]
I just installed 2017 Enterprise edition on a Windows 10 machine.  I have previous version of VS 2015 and VS 2013 installed.  I downloaded the AWS Toolkit for Visual Studio 2017 installer.  When I run it, it fails.  I'll attach the log but in short, it fails to find VS 2017 and fails with VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

## Expected Behavior
Toolkit should install successfully

## Current Behavior
Fails with a VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Install VS 2017 Enterprise.
Download and start AWS Tookit for Visual Studio 2017 installer

## Context
I can't create an AWS Serverless Application solution.

## Your Environment
* Operating System and version: Windows 10
* Visual Studio version: 2017 Enterprise

[VSIXInstaller_1586156a-0b7c-4397-a866-fee9c9a5dc59.log](https://github.com/aws/aws-sdk-net/files/2041781/VSIXInstaller_1586156a-0b7c-4397-a866-fee9c9a5dc59.log)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
Microsoft's vsix installer utility is part of your individual Visual Studio installs and I have a working theory that when you download from the marketplace to your file system and then launch the installer by double-clicking the downloaded file, the wrong version of the installer gets launched and results in the 'cannot find installed products' error. For example, the version of the installer that is distributed with Visual Studio 2015 knows nothing of how to find Visual Studio 2017 editions and if it is launched on a downloaded vsix that is declared (as ours is) to support 2017 only then it will trigger that message.

Instead of downloading the vsix file I recommend installing from within Visual Studio 2017 itself. Launch the IDE and navigate to the **Tools** menu and select **Extensions and Updates**. In the resulting dialog select the **Online** category and then search for '_AWS_'. This will bring up the entry for the toolkit. Select it and click the download or install link (I don't immediately recall which button gets shown). This will queue the install to occur when Visual Studio is restarted, so close the IDE and you should see the install process start up. On next load of the IDE, you should find the toolkit to be installed - e.g the View menu will show the AWS Explorer option and if the toolkit cannot find credentials to use it will display it's 'first run' page to guide you.

**Comment by dhsass** [comment]
Thank you.  I totally forgot about Extensions and Updates.   It gave me trouble on the first try but after a reboot it worked.  Thanks for the help.
