### ISSUE TITLE
AWS Toolkit does not install on enterprise Visual studio 2017

### ISSUE THREAD

**Issue by mostafafallah** [aws/aws-sdk-net#997]
I want to install AWS Toolkit on my visual studio 2017. The version is enterprise 2017 (15.7.4)
When I close VS, it start to install. after while it shows me these messages :

Modifying Visual Studio Enterprise 2017
Download Completed

and then it shows me this error 

Install Failed 

I attached the log file.  and then it shows me this message at last 
---------------------------
VSIX Installer
---------------------------
Package '12ed248b-6d4a-47eb-be9e-8eabea0ff119' failed to download

[VSIXInstaller_033ee914-fcc9-4cc0-9184-95f13590e069.log](https://github.com/aws/aws-sdk-net/files/2170520/VSIXInstaller_033ee914-fcc9-4cc0-9184-95f13590e069.log)
Please help me. anybody can help me ?

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
I looked over the log and from the last set of messages it looks as though the installer failed to ultimately download the package to install. Are you behind a proxy that might have interfered somehow? A vsix file, which is the distribution package for an extension, is nothing more than a zip file that is unpacked into the right locations, and registered, by the vsixinstaller.exe which is a part of your Visual Studio installation. The log shows an exception triggered in this tool due to a 'download failure'. If you can find the vsix file that was downloaded, are you able to open it (rename to .zip for example)?

There are also a lot of other error or warning messages about unrelated packages, so maybe something is  also in error in your overall VS2017 install. I suggest trying these steps to see if it helps:

1. First do a repair on your VS2017 install to see if it cleans up some of the other errors and warnings on the other packages.
2. Try and install from within VS first: go to Tools -> Extensions and Updates and select the 'online' category, then search for 'aws' and selecting the package, follow the steps you did before.
3. If (2) fails again, go to the [marketplace page for the extension](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017) and download it locally. With no running instances of VS2017, try double-clicking the downloaded .vsix file. This will trigger the vsixinstaller.exe tool to run. Make sure the vsixinstaller.exe process is launched from the util included in your VS2017 installation (VS2015, for example, has its own which can result in an error 'no applicable products' if it runs against this package).

If none of these work, ping back on the issue - it may be we need to forward the details to Microsoft (who own vsixinstaller.exe).

**Comment by mostafafallah** [comment]
Hi Steve
Thanks for reply.
When I faced this problem, I tried to install it on 3 othes laptops and all of them had the same problem. So I creted this ticket here.

I really did not your command and today I just ran again the AWS Toolkit installer and it is installed !! I really do not know why but I tried to install it on other 3 laptops and package is installed on all of other laptops ! I know it is very strange but I do not have any idea why and how ?!

May be it relate to Amazon server or something like this ?
